### ISSUE TITLE
Supply non minified version in the /dist/ dir

### ISSUE THREAD

**Issue by mplunkett5** [michalsnik/aos#100]
Can you also supply a non minified version of aos.js in your dist directory?

This would allow me to call in the the non minified version to then be minified as part of my build process. This would avoid the risk of an extra magnification causing issues.

Thanks

**Comment by michalsnik** [comment]
Hey, sure it is possible. I didn't had much time lately. But I'll start resolving existing issues now on a daily basis.

**Comment by fredDesign** [comment]
hi,
any news on that ?

**Comment by pirco** [comment]
hmm. now I ONLY see the non-minified version. is it possible to distribute both?

**Comment by michalsnik** [comment]
I'm in process of rewriting whole setup. I'll provide both full and minified version of UMD module in v3. You can check current progress here: https://github.com/michalsnik/aos/tree/next
