### ISSUE TITLE
Its not working on my project

### ISSUE THREAD

**Issue by shihab0915** [michalsnik/aos#102]
I add these two: 
`<link href="css/aos.css" rel="stylesheet">`
 `<script src="js/aos.js"></script>`
and
used
```
<div data-aos="fade-up" data-aos-anchor-placement="top-center" class="col-xs-6 ">
	<h2>Company Name</h2>
	<h3>- Tag Line</h3>
	<p>Comming Soon Page</p>
</div>




```
AFTER THAT THE ABOVE DIV HIDES. WHERE I AM DOING WRONG?

**Comment by michalsnik** [comment]
Did you actually add:
```
AOS.init();
```
somewhere after `js/aos.js`?

**Comment by michalsnik** [comment]
Duplicates #101
