### ISSUE TITLE
Content not showing up at all

### ISSUE THREAD

**Issue by rinus2107** [michalsnik/aos#110]
Hi, just wanted to say before I ask my question, you've made such an awesome plugin, thank you so much. Now my question is:

I can't seem to get your plugin to work with my code. The content I assign the data-aos tag to just stay at an opacity of 0, no matter what I do. This is my code:

<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<title>Smart Living Symposium</title>
	<script type="text/javascript">
	if (screen.width <= 1200) {
	document.location = "mobile.html";
	}
	</script>

	<link href='https://fonts.googleapis.com/css?family=Lato:400,300' rel='stylesheet' type='text/css'>
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.js"></script>
	<script src="jquery.waypoints.min.js"></script>
	<script src="bootstrap.min.js"></script>
	<script src="master.js"></script>
	<script src="aos.js"></script>

	<link href='aos.css' rel='stylesheet' type='text/css'>
  <link href='style.css' rel='stylesheet' type='text/css'>
	<link href='bootstrap.min.css' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="initial-scale=1, width=device-width, maximum-scale=1, minimum-scale=1, user-scalable=no">
	<script>
		AOS.init();
	</script>
</head>
<body>
	<div class="section1">
		<div class="backgroundIMG"></div>
		<div class="logoWit"></div>
		<div class="pijltje"></div>
	</div>

	<div class="section2">
		<div id="textLeft" data-aos="fade-left"></div>
	</div>
	<div class="section3">

	</div>
	<div class="section4">

	</div>

	<div id="menu">
		<ul>
			<li class="nav_item"><a id="homeL" href="">Home</a></li>
			<li class="nav_item"><a id="thisYearL" href="">This Year</a></li>
			<li class="nav_item"><a id="companiesL" href="">Companies</a></li>
			<li class="nav_item"><a id="studyL" href="">Study</a></li>
			<li class="nav_item"><a id="unionL" href="">Union</a></li>
			<li class="nav_item"><a id="prevYearL" href="">Previous Years</a></li>
			<li class="nav_item"><a id="contactL" href="">Contact</a></li>
		</ul>
	</div>
</body>
</html>

**Comment by rinus2107** [comment]
Uhm woww that is one messed up piece of code, sorry everything changed when I pasted it here

**Comment by michalsnik** [comment]
Hi, you have to init AOS after document is ready.
You can do so by either placing `AOS.init();` right before `</body>` or by:
```
$(function() {
  AOS.init();
});
```

**Comment by anumitaverma** [comment]
Hi, even after I added AOS.init() in my aos/js file and html file, I still cant seem to work it

**Comment by skube** [comment]
I'm having the same issue. I've added  `AOS.init()` to my `main.js`. I'm not getting any errors and all content divs where I've specified `data-aos="fade-up"` are `opacity:0` and never get triggered to be visible.

**Comment by michalsnik** [comment]
Try to add this:
```
window.addEventListener('load', AOS.refresh)
```

**Comment by skube** [comment]
I tried that (#182) but I discovered in my case the content was inside some other divs with `overflow: hidden` and `overflow-y: scroll` set. Removing these properties seems to fix the issue.

**Comment by markwaldin** [comment]
I have the same problem and is driving me crazy.  Even copied one of the working samples with no luck

**Comment by singhv18** [comment]
@skube yes, the overflow is what is causing the problem. Is there any other way to work around it because I can't really get rid of `overflow:auto;`?

**Comment by rsmease** [comment]
I ran into this 'opacity:0' issue and managed to get everything that I wanted (overflow protection + working animations) with:

html {
overflow-x: hidden
}

@skube @markwaldin thanks for bringing this up; I was convinced my problem was a React/Webpack issue until I ran into this thread.

**Comment by Raghav-Kumar-Jha** [comment]
Hello guys, 
I have used this plugin in my real project then it does not show anything, But when I come to the blank area and drag my browser then it shows the effect. But when you will run this in the separate HTML page (Like Try.html) then everything goes perfectly. 
Please resolve this issue soon. And Thanks for such a nice plugin.

**Comment by michalsnik** [comment]
Hey @Raghav-Kumar-Jha ! I'm sorry you're having troubles, but without reproducible example I won't be able to help ;/ I tested this on many different projects, browsers and scenarios and it always works for me..

**Comment by Architechnium** [comment]
This is definitely a reproducable problem for me, using the fade-up animation on an element in the viewport. when I open developer tools, which resizes the viewport, the animation then fades up. awesome program but annoying little bug

**Comment by Architechnium** [comment]
It must be a bug with the transform3D property that fade-up applies to the element, because using "fade" seems to work just fine

**Comment by michalsnik** [comment]
Have you tried to clone this repository and run `yarn dev` locally to confirm whether you get the same problem here @Architechnium? Unfortunately I will be off for few weeks so I won't be able to investigate it more.

But it looks like your layout also recalculates something on resize and AOS seem to too early refreshing position of it's elements.. You might want to add your own listener and refresh AOS manually after small delay. But it's just a guess. 

This is the code that is responsible for refreshing AOS on refresh:
https://github.com/michalsnik/aos/blob/next/src/js/aos.js#L193

**Comment by devstc** [comment]
I found this thread because I was trying to solve the problem I was having where if I refreshed (F5) the browser, the AOS animations stopped working.  This was happening in Chrome, Firefox, Edge, and IE.  In one of the browsers, I can't remember which one, the content wasn't even showing at all.   Adding the code @michalsnik posted on Jul 6, 2017 after `AOS.init();` solved my problem.  Thanks!

**Comment by Bluedeepart** [comment]
> Hi, you have to init AOS after document is ready.
> You can do so by either placing `AOS.init();` right before `</body>` or by:
> 
> ```
> $(function() {
>   AOS.init();
> });
> ```

facing same problem on my portfolio
https://www.deepart.in/.

**Comment by ddiegommachado** [comment]
Heeelp!
I created all these steps with Vue, but calss .aos-animate is not added to my div.

```
import AOS from "aos"
import 'aos/dist/aos.css'

new Vue({
  el: '#app',
  router,
  render: h => h(App),
  created () {
    AOS.init();
  }
})

<h1 data-aos="fade-up">About</h1>
```

**Comment by miduraa11** [comment]
Hello @michalsnik 
I have the same issue like @skube. It's working for first div only and the rest of it when i resize my browser. But in my case when I remove `overflow: hidden ` nothing happened, still the same problem :/

Is there any solution for this?

**Comment by gitSuyash** [comment]
### **`content not showing up on using data-aos field`**
```<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
         <link rel="stylesheet" type="text/css" href="aos.css">

   <link href="https://fonts.googleapis.com/css?family=Raleway|ZCOOL+QingKe+HuangYou" rel="stylesheet">
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="style.css">
	<title></title>
</head>
<body>
 <div id="fullpage">     
        <div class="section"><img src="la.jpg" style="height: 100vh;width: 100vw">
            <div class="cover_text"><a style="color:white">Los</a> Angeles<br><p>Here we play our <a style="color: white">souls out</a>.</p></div></div>
        <div class="section description" >
            <p style="font-size: 24px;">THE BAND</p>
            <p><i style="background-color: grey;color: white;font-size: 20px">We love Music</i></p>
            <p>We have created a fictional band website. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            <div class="bandmembers">
                <div><img src="bandmember.jpg"><div>Name</div></div>
<div><img src="bandmember.jpg"><div>Name</div></div>
                <div><img src="bandmember.jpg"><div>Name</div></div>
            </div>
        </div>
        <div class="section tours" data-aos="fade-in">
            <div class="tours_months">
                <div class="months" style="margin-top: 0px;">September <span class="sep">Sold Out</span></div>
<div class="months">October  <span class="oct">Sold Out</span></div>
                <div class="months">November  <span class="nov">10</span></div>
            </div>
        </div>
        <div class="section" data-aos="fade-in">
            <div class="places">
            <div class="tours_places">
                 <img src="sanfran.jpg" >
             <div style="background-color: #F9E79F  ">
              San Francisco<br>         
                21 November,2019  <br>      
                 <a style="background-color: black; color:white;line-height: 30px;" class="tix">BUY TICKETS</a>
                </div>
            </div>
<div class="tours_places place_two" data-aos="fade-in">
    <img src="newyork.jpg" >
             <div style="background-color: #F9E79F ; " >
              New York<br>         
                23 November,2019    <br>      
                    <a style="background-color: black; color:white;line-height: 30px" class="tix">BUY TICKETS</a>
                </div>
</div>
            <div class="tours_places place_three" >
              <img src="paris.jpg" >
             <div style="background-color: #F9E79F  ">
              Paris<br>         
                25 November,2019    <br>      
                     <a style="background-color: black; color:white;line-height: 30px" class="tix">BUY TICKETS</a>
                </div>
            
            </div>
        </div>
        </div>
    </div>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.4/vendors/easings.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.4/vendors/scrolloverflow.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.4/fullpage.js"></script>
    <script type="text/javascript">
    new fullpage('#fullpage', {
        //options here
        autoScrolling: true,
        licenseKey: 'OPEN-SOURCE-GPLv3',
    });
    </script>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
  AOS.init();
</script>
</body>
</html>`

**Comment by NetPax** [comment]
I had the same problem. In my case I remove overflow-x: hidden from my html and body tags. Works perfectly.

`html, body {
  background: #ffffff;
  height: 100%;
  //overflow-x: hidden;
  position: relative;
}`

**Comment by MustafaKhan026** [comment]
i used this on my project.but it's not working,all the browser is showing is blank in the section where i used it. 
please help me resolve this issue.

**Comment by owenfar** [comment]
> Try to add this:
> 
> ```
> window.addEventListener('load', AOS.refresh)
> ```

document.onreadystatechange = function () {

    if (document.readyState == 'complete') 
    {
        AOS.refresh();
    }
}

This is what did the trick for me. Hope it helps

**Comment by JarrettAllenYoung** [comment]
replacing 
```
<script>
     AOS.init();
</script>
```
with
```
<script>
     $(function() {
          AOS.init();
     });
</script>
```
worked for me 🤓

**Comment by whizzbbig** [comment]
how to make aos work with overflow actually i made an parllax effect website using kieth clark theory 
but i want to animate my second section with aos. but when i add data-aos property to the element to whom i wanted to animate and after that it was not there anymore by readin the comment here i notice that by removing overflow we will able to animate it from aos . but , i not want to remove overlay if i do that my header will messed up coz it parallax plss help me with that .

**Comment by deepanshupal2003** [comment]
Thanks @michalsnik 
  
    $(function() {
          AOS.init();
     });
This worked like a charm!! 😄

**Comment by whizzbbig** [comment]
I know that, and I also found the problem why the content was not showing because I defined overflow x and y on a div. can I able to use aos with them because that’s a parallax website and without them parallax website will screw up! Sent from Mail for Windows 10 From: deepanshupal2003Sent: Sunday, May 17, 2020 1:44 AMTo: michalsnik/aosCc: whizzkkid; CommentSubject: Re: [michalsnik/aos] Content not showing up at all (#110) Thanks @michalsnik$(function() {       AOS.init();  }); This worked like a charm!! 😄—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kithinga** [comment]
make sure you remove global overflow hidden.
especially body and html should not have overflow hidden if you want this to work

**Comment by sinarkk** [comment]
Im a new user to this , and reading all the comments above couldn't solve my problem , the content is not showing up
i gave like this

<script>
     $(function() {
          AOS.init();
     });
</script>

I am using bootstrap 4 and ensured there is no overflow hidden 

`<div` class="col-sm-4" `data-aos="zoom-in"><img` src="img/aboutus.jpg" `class="img-fluid"></div>`

by inspecting element i can see its opacity is set to 0 , i edited and set as 1 in inspect section , then it appears , but still no animation 

i have even tried this into script

AOS.init({
  duration: 1200,
})

but nothing seems to work


this is the only line i'm testing , source's are given as cdn reference and also i use jquery and popper js by bootstrap as cdn 

what am i missing?

**Comment by JMartinesGH** [comment]
Same issue on 2.3.1. 
elements are stuck on opacity 0. I've tried using 
`$(function () {
  AOS.init();
  window.addEventListener("load", AOS.refresh);
});`
to no success. Any help would be appreciated.

**Comment by murdskristians** [comment]
I tried every possible combination that is in this post but nothing worked.

In main.js i import both:
import AOS from 'aos'
import 'aos/dist/aos.css'

Tried on Created and Mounted state different ways:
	created () {
		AOS.init()
	},
	mounted() {
		AOS.init({
			disable: "mobile"
		});
		if (document.readyState == "complete") {
			AOS.refresh();
		}
	},

Also tried to build a project to have dist folder and importing from there, but also did not work.
Also tried to put in App.vue component with and without async:
	mounted: function() {
		import('aos').then(AOS => AOS.init());
	},

Any other working solutions?

**Comment by BigPackie** [comment]
@michalsnik  Would be nice to include into the documentation a note about overflow property problems.

**Comment by execreate** [comment]
Hi! I have the same issue, elements with AOS enabled are not showing up at all (opacity: 0) with User Agent Safari on iPhone, iPod touch or iPad mini, on everything else it seems to work quite fine.

AOS initialization:
```
new Vue({
    created() {
        AOS.init({
            disable: 'mobile',
            duration: 600,
            once: true,
        });
    },
    router,
    render: h => h(App),
}).$mount('#app');
```

Not a single workaround from this thread helps. I have `overflow-x: hidden;` on body element, tried to set `overflow-y: scroll;` too, tried to `setEventListener` on DOM with both `Aos.refresh` and `Aos.refreshHard`, I even tried to initialize AOS with timeout 3 secs. I'd be happy if you could help with this issue.

PS. I am using AOS v.2.3.4.

**Comment by BigPackie** [comment]
> 
> 
> Hi! I have the same issue, elements with AOS enabled are not showing up at all (opacity: 0) with User Agent Safari on iPhone, iPod touch or iPad mini, on everything else it seems to work quite fine.
> 
> AOS initialization:
> 
> ```
> new Vue({
>     created() {
>         AOS.init({
>             disable: 'mobile',
>             duration: 600,
>             once: true,
>         });
>     },
>     router,
>     render: h => h(App),
> }).$mount('#app');
> ```
> 
> Not a single workaround from this thread helps. I have `overflow-x: hidden;` on body element, tried to set `overflow-y: scroll;` too, tried to `setEventListener` on DOM with both `Aos.refresh` and `Aos.refreshHard`, I even tried to initialize AOS with timeout 3 secs. I'd be happy if you could help with this issue.
> 
> PS. I am using AOS v.2.3.4.

I am not sure if intended, but "disable: mobile" disables AOS on mobile devices, which means the elements should show up without animation. So I suppose it does not work whether or not this option is configured.

Note: **inline** elements cannot be animated.

I did not try Safari yet.

You can have a look at #https://github.com/michalsnik/aos/issues/336

**Comment by connie-liou** [comment]
I fixed this issue by including jQuery with my scripts, which I didn't do beforehand. I used the $(function(){...} solution with 
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>`

**Comment by eelcoverbrugge** [comment]
Same issue with bootstrap 4. Opacity is 0 and so the div is not showing up. @connie-liou adding jquery did not work for me unfortunately. Any idea?

**Comment by DRenden** [comment]
Hi, faced the same problem in webpack, it worked when I wrote:
`import AOS from 'aos';
global.AOS = AOS;`
then in footer
`$(function() {
      AOS.init();
 });`

**Comment by Jumns** [comment]
I'm using Bootstrap 4 and it's working fine on my system and github page jumns.github.io/myportfoliov1 but not on my domain name www.jnathan.com.ng. it's working on Firefox but not on chrome neither the desktop nor the mobile version. Pls help.

**Comment by GxyNomad** [comment]
> I'm using Bootstrap 4 and it's working fine on my system and github page jumns.github.io/myportfoliov1 but not on my domain name [www.jnathan.com.ng](http://www.jnathan.com.ng). it's working on Firefox but not on chrome neither the desktop nor the mobile version. Pls help.

I just checked on Chrome and it's working fine for me. How did you fix it?

**Comment by Jumns** [comment]
Try this :
$(document).ready(function () {
  AOS.init({
//code here
  });
});

**Comment by Sevicode** [comment]
> replacing
> 
> ```
> <script>
>      AOS.init();
> </script>
> ```
> 
> with
> 
> ```
> <script>
>      $(function() {
>           AOS.init();
>      });
> </script>
> ```
> 
> worked for me

Thanks, this fixed the opacity problem for me, you saved me ! :dancers:

**Comment by Carlosm99** [comment]
Nothing of the above has worked for me! Unfortunately!

But I found a solution.
```
<head>
    <link type="text/css" rel="assets/css/aos.css">
    <script src="assets/js/aos.js"></script>
</head>
<body>
    <div data-aos="fade-up">
         Hello
    </div>
    <script>
        AOS.init();
    </script>
</body>
```

**Comment by NomanKader** [comment]
I solved by removing height:100% from body , html{ }.

**Comment by Prithibee13** [comment]
When I use Bootstrap collapse toggle system, aos not work(data-aos= fade-up) . I use like this code as a previous question but did not work. my code on jquery toggle
$('#bt1').click(function ()
            {
                $(".collapse").collapse('hide');
                AOS.init();   
            });


Help me solve this.

#TIA

**Comment by maksym1015** [comment]
Hello, @michalsnik 

I used AOS to my Create React App.
But it works on the visible component but doesn't work properly on the invisible component.

When I inspect the site it didn't apply to the aos-animate class name to the invisible component.

Ofc, I all did
import AOS from "aos";
import "aos/dist/aos.css";

  useEffect(() => {
    AOS.init({
      startEvent: "DOMContentLoaded",
      offset: 200,
      duration: 3000,
      once: true,
    });
  }, []);


Already, read the above solutions but have not found the solution.
Hope you solve this problem ASAP.

Max

**Comment by krishna-kush** [comment]
> Hi, you have to init AOS after document is ready. You can do so by either placing `AOS.init();` right before `</body>` or by:
> 
> ```
> $(function() {
>   AOS.init();
> });
> ```

in my case it worked by putting it after closing body tag not before, right before closing html tag. I'm using react btw.

**Comment by akankshhha** [comment]
Putting the right links in the right places is mandatory. 

css link goes in the head section, init & js link go in a script tag, just before the closing of the body tag.

**Comment by abhiramkg2000** [comment]
I have added fade-left animation on my website. but it is not working as the fade-left CSS is not getting added to my div and I am getting only plain fade animation on my div. please help

**Comment by EhsanShahbazii** [comment]
hi. add styles in your head tag:

 `<link rel="stylesheet" href="your path/aos-master/dist/aos.css" />`

then add script before </body> tag then init AOS:

`<script src="your path/aos-master/dist/aos.js"></script>`
  `<script>`
    `AOS.init();`
  `</script>`

good luck

**Comment by Edward1784** [comment]
This will definitely work inshallah.
```
document.addEventListener("mousemove", e => {
    AOS.init();
    AOS.refresh();
});
```

**Comment by NimaCodez** [comment]
> I tried that (#182) but I discovered in my case the content was inside some other divs with `overflow: hidden` and `overflow-y: scroll` set. Removing these properties seems to fix the issue.

@skube
hey dude, the problem is that i need to use overflow-x:scroll; in my project.. isn't there any way that i can use it?

**Comment by Konar91** [comment]
I've been having this problem on mobile when using dynamic react components, Aos disabled prop and fade-up.

The component kept 0 opacity and was aos transformed.

On the component that is being bugged by data-aos use this:

@media (max-width: {Your disabled width}) {
    opacity: 1 !important;
    transform: none !important;
  }
  
  It worked for me.

**Comment by ashurohilla** [comment]
> Uhm woww that is one messed up piece of code, sorry everything changed when I pasted it here



> 

the same issue i am suffering from all the content where i use the data-aos tag is gone and not more visible when i inspected than i found that a opacity of zero is there so how can i handle this ?

**Comment by Jaroca124** [comment]
If you still have the opacity: 0; issue, be sure to check that there are no "height: 100%" or "overflow: hidden" styles set on your html, body tags. Removing these fixed the issue for me, hope this helps!

**Comment by ntn20b** [comment]
I spent a lot of time for the solution, if it's still relevant: 
html{
height: auto;
}

**Comment by Tauqeer180** [comment]
> replacing
> 
> ```
> <script>
>      AOS.init();
> </script>
> ```
> 
> with
> 
> ```
> <script>
>      $(function() {
>           AOS.init();
>      });
> </script>
> ```
> 
> worked for me 🤓


Also Worked For Me, Thanks

**Comment by alimazhar4** [comment]
I have been facing this same problem on my Next JS website. Although removing overflow-x:"hidden" from html and body tags does fix the issue but I have to keep overflow-x:"hidden" on both tags. Otherwise a white space appears on the left side of the screen until all the fade-left animations haven't activate. 

Another thing I have noticed that the animation does work normally for viewport width > 600px. But the moment when screen viewport width becomes 600 or less, the animation work only when the affected element have have appeared half way the screen. You may check it through the inspection window, if it's the same for you. 

For the time being, just like[ DamianAexolI's answer](https://github.com/michalsnik/aos/issues/110#issuecomment-1119452948), I have added the following media query to the affected elements/divs:
```css
@media only screen and (max-width: 600px) {
        transform: none !important;
        opacity: 100% !important;
    }
```

I know this might not be the perfect solution for some people as they might want the animations on mobile screen too. 

If it works, you can also do:
```js
AOS.init({
      // ....
      disable: "mobile",
    });
```

**Comment by tanvi1110** [comment]
aos animate is not working on the div I select the animation. it is working fine when I decrease the size of window but not on desktop screen. And I am working with nextjs

**Comment by lavert** [comment]
I only had this issue when adding the data-aos attribute with jQuery, despite not getting any console errors. Adding the data-aos directly to the HTML did NOT cause the problem.

I replaced the jQuery with a Javascript forEach() function to add the data-aos and it worked as expected. I tried all the other solutions on this page above and none of them worked. For me, adding the data-aos to a list of elements with jQuery is what caused the issue. Replacing the jQuery with vanilla JS solved it.

**Comment by TinyHandsome** [comment]
Hi. I had the same issue. But I fixed it by remove `overflow-x: hidden;` in **html**

**Comment by date-oil-rich** [comment]
https://csser.space/questions/attempting-to-implement-scroll-based-animation-on-my-webpage The truth is known

**Comment by Express-router** [comment]
@markwaldin https://toisostringpublicized.github.io/rnK0HD4Y2WO3Pja2/
