### ISSUE TITLE
Start animation on window focus

### ISSUE THREAD

**Issue by dongepulango** [michalsnik/aos#113]
Not sure if I can explain this, but if the element is already in view from the start (example is like the header) I want to start the animation only when the window is already focused. So if I open the site on a new tab for example, the animation will not start until I focus the window. Hope that make sense.

**Comment by michalsnik** [comment]
Hey, I might know what you mean.

I think you can use Page Visibility API (https://www.w3.org/TR/page-visibility/) in order to achieve this, like so:
```
const windowFocusedEvent = new CustomEvent('windowFocused', {});

function windowFocusListener() {
  if (!document.hidden) {
    document.dispatchEvent(windowFocusedEvent);
  }
}

document.addEventListener('visibilitychanged', windowFocusListener);
document.addEventListener('DOMContentLoaded', windowFocusListener);

AOS.init({
  startEvent: 'windowFocused'
});
```

I didn't test this code, but you should get a raw idea now. Feel free to reopen this issue if you have more questions.

**Comment by dongepulango** [comment]
Thank you! This works great.
