### ISSUE TITLE
issues with fade-left on smaller causing a horizontal scroll

### ISSUE THREAD

**Issue by makestudio-alan** [michalsnik/aos#118]
When using fade-left on a mobile and tablet I have noticed a issue where at least 100px is added to the right of my container thus causing a horizontal scroll,  fade-right seems to be ok as in no extra margin.

Any ideas?

Thanks

**Comment by makestudio-alan** [comment]
Quick update, it seems that adding the following css fixes the issue:

[data-aos] {
    overflow: hidden;
}

**Comment by michalsnik** [comment]
Hey, this is a well known scenario. I explained it for example here: #73
