### ISSUE TITLE
Amazing work !!!!

### ISSUE THREAD

**Issue by zzseba78** [michalsnik/aos#122]
Just to say this, amazing amazing script, the performand it's superb, and triggered in perfect time, flexible and versatile solution. Amazing.
Thanks for your work !!!!!

**Comment by michalsnik** [comment]
Hi @zzseba78 ! It's really kind to hear that you like it :)
This is the kind of issue that every OSS maintainers secretly count on :D

**Comment by beardsavvy** [comment]
+1, thanks for building this excellent tool. Great work, keep it up!
