### ISSUE TITLE
TypeError: document.querySelector(...) is null

### ISSUE THREAD

**Issue by thefirstcritic** [michalsnik/aos#127]
When I load my test page in Firefox, I get this error (and no animation):  TypeError: document.querySelector(...) is null

<!DOCTYPE>
<html>
<head>
<title>AOS Test</title>
<link rel="stylesheet" href="dist/aos.css">
<script src="dist/aos.js"></script>
<script>
  AOS.init();
</script>

</head>

<body>

</body>
</html>

Do I need to load jQuery first or something?

**Comment by michalsnik** [comment]
Hey, you don't need jQuery at all.
All you have to do is to make sure you init AOS after your DOM is ready.
You can do so by placing `AOS.init` in script tag right before `</body>` tag, or by wrapping it around:
```
document.addEventListener('DOMContentLoaded', function() {
  AOS.init();
});
```

This should fix your problem.

**Comment by carlos-mg89** [comment]
What if I do need JQuery along AOS library? Would it be possible to fix this error in that case?

Thanks in advance :)

**Comment by michalsnik** [comment]
Yes you can use it alongside jQuery. Your problem wasn't related to jQuery itself, your problem was with the execution order. AOS has to be put at the end of body tag.

**Comment by carlos-mg89** [comment]
That's true! Thanks a lot for this great project :) It did work as I wanted and it's super smooth.
