### ISSUE TITLE
Add to NPM

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [michalsnik/aos#13]
Hi there!

Besides bower, would be possible to add this project to NPM?

Thanks.

**Comment by michalsnik** [comment]
Hi @rafael-renan-pacheco

Sure, I'm aware of that and I'm going to publish this very soon.

First I'm going to make it compatible with different module systems (#11) and then I'll also publish this on npm.

Stay tuned

**Comment by rafael-renan-pacheco** [comment]
Sweet :smile: 

Thank you very much, and congrats on this amazing project! :+1:

**Comment by michalsnik** [comment]
Thank you @rafael-renan-pacheco !

I just published AOS on NPM. Have fun using it :)
https://www.npmjs.com/package/aos
