### ISSUE TITLE
Animation distance

### ISSUE THREAD

**Issue by Evenbeeld** [michalsnik/aos#131]
Hi Michalsnik,

First of all, super awesome and easy to use JS. Really love it.
I have one question though. Is there a way to change the distance of the animation?

I wanted to make it a bit shorter. But can't seem to find out how to do this.

Thanks in advance.
Kind regards,
Philippe

**Comment by michalsnik** [comment]
Hey @Evenbeeld, I'm glad you like it!

If you look into `scss` sources you'll see there is `$aos-distance` variable, that you can override in your styles.

Hope this answers your question :)

**Comment by xApep** [comment]
Hi. 
I have the same issue. I've chnage this variable to 0 but it still has to much distance. While monitoring with firebug it triggers animation 200px above the view, in other words when my bottom view port is 200px above aos it gets triggered.

**Comment by ryancoutinho** [comment]
Hi Michal,
Awesome JS! I just started using it in Wordpress and am loving it.
However, when I try to change the distance with the variable it stays at 100px.

Also when I try to get the css from the URL and place it locally and try to modify the distance directly in the animation.
For instance:
 [data-aos='fade-up'] {
  transform: translate3d(0, 500px, 0); }

It remains 100px. can you please help me  (I didn't understand the compiling of the scss).
I also installed scss compiler in wp with no luck.

Kind regards
Ryan

**Comment by b-ramdin** [comment]
Hey Ryan you'll defo need to understand how to compile scss. The code that needs editing is on the _animations.scss file at the top
// Animations variables$aos-distance: 100px !default;

If your going to do this you can't use the aos.css file anymore. You need to import the 3 partial files and output from a style.scss which make the style.css
Hope it helps

**Comment by ryancoutinho** [comment]
hi ramdin,
i solved it thanks a lot for your reply.
