### ISSUE TITLE
Custom easing?

### ISSUE THREAD

**Issue by drawcard** [michalsnik/aos#132]
Hi, is there any way to add a custom easing? I am looking for an option to add "bounce" / "elastic" physics as demoed here: http://easings.net/

**Comment by michalsnik** [comment]
Hey, sure you can.

Like so:
```
body[data-aos-easing="your-easing"] [data-aos],
[data-aos][data-aos][data-aos-easing="your-easing"] {
  transition-timing-function: cubic-bezier(.455, .03, .515, .955);
}
```

Then you can use it like any other easing by providing `your-easing` name instead.

If you wonder where did it come from, take a look at: [https://github.com/michalsnik/aos/blob/master/src/sass/_easing.scss](https://github.com/michalsnik/aos/blob/master/src/sass/_easing.scss)
