### ISSUE TITLE
Flip image background after fade in 

### ISSUE THREAD

**Issue by luizabentivoglio** [michalsnik/aos#136]
How can i do the flip of background-image after the fade in caused by scroll? thank you in advance

**Comment by michalsnik** [comment]
I'm not sure if I get you correctly. But you can write your own animations. Check out codepen examples in Readme to find out more. I prepared few just to show the basics, but you can do much more.

**Comment by luizabentivoglio** [comment]
Sorry, my english is not very good...i want double animations on single element, not a single custom animation. 1) fade in on scroll and 2) after delay flip the image with another. Is there a method with aos to do that? If not, ok, i will search a method to do that, no problem... In my case if i use the delay to use double animation with flip this not work because this show me first  **the end-image**, do the flip from the start-image, and then show me again the end-image (the flip is ok, but i want that start with the start-image)

**Comment by michalsnik** [comment]
There is no way to do sequential animations by default
