### ISSUE TITLE
How to disable aos animation in ie

### ISSUE THREAD

**Issue by rtpltech** [michalsnik/aos#141]

**Comment by michalsnik** [comment]
Hey @rtpltech, there is a `disable` method that accepts function as a value, there you can add logic for detecting IE and you should be good to go.

**Comment by enolife** [comment]
**To disable aos on internet explorer**

Add the script below on your html file. 
Or add the disable method and function if you already have the AOS.init script on your html file.

```
<script>
        AOS.init({

          // disable on internet explorer
            disable:  function msieversion() {
                return !!(window.navigator.userAgent.indexOf("MSIE ") > 0 || navigator.userAgent.match(
                    /Trident.*rv\:11\./))
            }

        })
    </script>
```
