### ISSUE TITLE
Start a animation with javascript function

### ISSUE THREAD

**Issue by quentin35** [michalsnik/aos#148]
Hi

Thanks for your amazing work :-)

I'd like to start a specific animation with a javascript function ( event listener : click )

How can I do this ? 

Thanks for your help :)

**Comment by georgetrad** [comment]
@quentin35 

If you don't want to initialize AOS on `DOMContentLoaded `event, you can pass your own event name and trigger it whenever you want. AOS is listening for this event on document element.

AOS.init({
startEvent: 'someCoolEvent'
});

**Comment by michalsnik** [comment]
Hey @quentin35, thanks! Unfortunately this is not that kind of library @quentin35, the only workaround might be what @georgetrad proposed, but that would init animation on all elements at once.
