### ISSUE TITLE
Scrolling in overflow block

### ISSUE THREAD

**Issue by webcredo** [michalsnik/aos#15]
It not work when animated items in  overflow block

**Comment by michalsnik** [comment]
Hi, thanks for calling an issue. Could you please provide me with an example on codepen? so I can verify it straight away and then put it on a roadmap.

**Comment by webcredo** [comment]
something like this http://codepen.io/webcredo/pen/PzNmWe

**Comment by michalsnik** [comment]
Hi @webcredo,

AOS currently doesn't work inside other block than window. It checks position of elements based on window viewport.

It seems like I already explained it here #9
