### ISSUE TITLE
Custom startEvent Not Triggering AOS

### ISSUE THREAD

**Issue by DougHucker** [michalsnik/aos#150]
Hello, I've a custom event triggering AOS.init. Basically I'm waiting until the DOM is loaded, and removing a loading animation, then trying to initialize AOS. It seems my event is firing but not triggering the animations until I resize the window. I've tried adding the refresh below. No dice. Any thoughts? All AOS assets and this code are loading in the header as well.

```
jQuery(function($) {
	
	AOS.init({
		startEvent: 'myEvent',
		disable: 'mobile'
	});
	
	var $myLoader = $(".spinner");
		
	$( window ).on( "load", function() {

		$myLoader.fadeOut("slow",
			function() {
				$myLoader.remove();
				$(document).trigger('myEvent');
			});
		
		});
});
```

**Comment by michalsnik** [comment]
Hello @DougHucker, it should work. For me it looks like in the moment you're triggering `myEvent` elements are not in good place (their calculated positions are changing or smth).
Try to wrap this trigger in additional `setTimeout` just for test purposes, so we can check if that's the case.

**Comment by michalsnik** [comment]
Ok, I got this @DougHucker. You have to trigger this event natively, that means:
```
document.dispatchEvent(new Event('myEvent'))
```
Hope that helps you :)
