### ISSUE TITLE
disable option doesn't work on asynchronously loaded items

### ISSUE THREAD

**Issue by CHEWX** [michalsnik/aos#152]
Hi,

The `refresh` or `refreshHard` method doesn't seem to check disabled items.

So when working with infinite scroll, the new items are appended but are blank, because `AOS` has already initiated on page load which disables `data-aos` elements that are on the page from load. I'd need to call a method that disables new items too by checking the initial instance of `AOS` in the infinite callback function, but there isn't.

Currently hacked a `removeAttr('data-aos')` currently as a work around.

Thanks,
Tom

**Comment by michalsnik** [comment]
Hey @CHEWX, sorry for the late answer. So what you're asking is to add proper support for `disable` option for asynchronously loaded elements, so that this option is being reflected on them as well. Do I get it correctly?

**Comment by michalsnik** [comment]
It's fixed on `next` branch. Will be released soon :)

**Comment by CHEWX** [comment]
Cool, nice to know!

**Comment by michalsnik** [comment]
I'm closing this issue now. You can follow current readme and install `aos@next` to get this option working on asynchronously loaded content :) If you'll experience any problems let me know.

Cheers!
