### ISSUE TITLE
Fade out anchor

### ISSUE THREAD

**Issue by jereldp** [michalsnik/aos#153]
love this - almost exactly what i was looking for. now, i'm trying to have the anchor animate out when the section it covers has ended. is this possible?

**Comment by michalsnik** [comment]
Hey @jereldp, unfortunately it's not possible. Right now I'm only checking the top offset of elements. There is however one PR regarding something you might be interested in https://github.com/michalsnik/aos/pull/41 I have to finally get back to this.
