### ISSUE TITLE
View port Bug on Mobile/Tablets

### ISSUE THREAD

**Issue by EmyXOR** [michalsnik/aos#156]
While the plugin works fine on PC browsers when it comes to mobile it's buggy.
On mobile/tablets after scrolling down to see the AOS effects on view there is a horizontal bar appearing - and you can drag the website left or right and the UI layout breaks.

I've tested on iPhone 7 Safari & iPad Safari.

**Comment by EmyXOR** [comment]
@michalsnik 

**AOS UI FIX** #156

**01. The first selector CSS is not needed when Bootstrap 4 is used**
**02. The second CSS selector fixes the horizontal bar created on the container while animations are in place - on phones and tablets the site layout would break**

*, *:before, *:after {   -moz-box-sizing: border-box;  -webkit-box-sizing: border-box; box-sizing: border-box; }

.aos-all {
    max-width: 100% !important;
    width: 100% !important;
    width: 100vw !important;
    overflow: hidden;
    margin: 0;
}

**Comment by colingourlay** [comment]
Here's a wee something I've just release that might help out: https://github.com/colingourlay/root-units

**Comment by michalsnik** [comment]
I think we already agreed somewhere else that it's not necessarily issue in AOS itself. It's just how horizontal transform works, and that there should be `overflow-x: hidden` on parent container or body. I'll put this simple solution in the upcoming FAQ.

**Comment by kangadi190** [comment]
![Screenshot_2019-04-28-05-55-21](https://user-images.githubusercontent.com/46488177/56855917-40775600-697a-11e9-9a63-753fa8c64452.png)
How to fix it?
Before loading the navbar isn't responsive.

**Comment by thexmanxyz** [comment]
@michalsnik The `overflow-x: hidden;` was a great hint for fixing navigation related issues on mobile (e.g. sticky navbar `fixed-top` in BS4). Big thanks!

**Comment by arrahmanbd** [comment]
Simply add those line on your stylesheet and see magic

```
* {
  margin: 0px;
  padding: 0px;
  overflow-x:unset;
} 
```
