### ISSUE TITLE
Doesn't work when div has overflow hidden style

### ISSUE THREAD

**Issue by aidia** [michalsnik/aos#157]
Hi,
can you tell, how the script can trigger animations when content is inside div which has overflow hidden style and inside it is another div with overflow-y scroll?
In this situation, scroll bar scrolls div not body. Body is not scrollable.

**Comment by michalsnik** [comment]
Hey @aidia , AOS doesn't work for other scrollable containers at the moment. It only works for body scroll.

**Comment by ronaldohoch** [comment]
Any idea to implement it?
Any help?

**Comment by michalsnik** [comment]
It's a good extra feature, but I would give it a big priority ATM. If you'd like to tackle it however @ronaldohoch feel free to submit PR

**Comment by ronaldohoch** [comment]
Can you give me the way? i will try :)

**Comment by tskaneva** [comment]
Any development on that matter? I'm facing exactly this - I want to scroll only on a section of my website and I can't achieve it. Bummer, since I really like the simplicity of the library.
