### ISSUE TITLE
aos.css:1 Uncaught ReferenceError: Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by nathanaelphilip** [michalsnik/aos#16]
Getting this in this console. I installed via npm and referenced the css file in the /dist folder.

**Comment by michalsnik** [comment]
Hi @nathanaelphilip , could you please paste the code example that causes this issue?

**Comment by nathanaelphilip** [comment]
Hi @michalsnik, it’s giving that error right out of the box.

**Comment by michalsnik** [comment]
The error itself suggests that you're trying to require css file inside your javascript.
Styles should be added to head section normally, or by importing them in your current styles.
You could also use webpack + css-loader to bundle them using javascript.

Please paste how you reference aos styles and script in your project, so I can tell you more and see if there is actually an issue.

**Comment by michalsnik** [comment]
I just tried to use it freshly as Node, AMD and even ES6 module and it's working fine (JavaScript part).
- as Node module
```
var AOS = require('aos');
AOS.init();
```
- as ES6 module
```
import AOS from 'aos';
AOS.init();
```
- as AMD module
```
<script src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.1.11/require.min.js"></script>
<script>
      require(['./node_modules/aos/dist/aos.js'], function(AOS){
          AOS.init();
      });
</script>
```

Speaking of styles I'm loading them directly in `head` section using simple `link`.

**Comment by nathanaelphilip** [comment]
ok, I’ll do some more testing and let you know. Thank you!

**Comment by nathanaelphilip** [comment]
I used NPM to install and then have this in my app.js file

```
var aos = require('aos');
```

and it’s saying it can’t find that module. I’ve checked my node_modules folder and it seems like it’s installed. Originally I was just referencing the file from the node module in a `<script src=""> tag.

**Comment by michalsnik** [comment]
Hi @nathanaelphilip, which version of AOS have you installed? Make sure it's the newest `1.2.1` and it should work. There was a missing `main` section in `package.json` and I added it to `1.2.1` release.

**Comment by nathanaelphilip** [comment]
Upgrading to 1.2.1 seems to have fixed the issues. Thanks!
