### ISSUE TITLE
AOS hidding content to google 

### ISSUE THREAD

**Issue by ArGaspar** [michalsnik/aos#161]
Hi,

I would like to know if there is any way to dissable animation for google bots because all the content beeing animated is hiden for google, I have check it on the Search console visiting my website as google.

Regards.

**Comment by michalsnik** [comment]
Hey @ArGaspar, thanks for pointing this. I think it's something that I should address. But for now you should be able to do something like this:
```
AOS.init({
  // ... your config
  disable: function() {
    return /bot|googlebot|crawler|spider|robot|crawling/i.test(navigator.userAgent);
  }
});
```
This should disable AOS when most popular bots are entering your page. Let me know it that helped you :)

**Comment by mtshare** [comment]
@michalsnik @ArGaspar 
Not working properly. Google doesn't execute Javascript.
You should do something like that:

```html
<noscript>
    <style>
        *[data-aos] {
            display: block !important;
            opacity: 1 !important;
            visibility: visible !important;
        }
    </style>
</noscript>
```

**Comment by ArGaspar** [comment]
@michalsnik  nice!! now google can see blocked content, it does not show exactly as it its on the webpage but thats no a problem, the thing is, as you can see on the right in the picture the section " as a visitor would see the web" its not showing content so Im afraid of having bad indexation because of different content, Google is very clear in documentation about different content  ![google](https://user-images.githubusercontent.com/17679063/26975804-b5c4cfce-4cf7-11e7-971f-44bd09aed6dd.png)
@mtshare your solution is good for google but It lose fade in effect so there is not too much point on using the library just to move an object a little bit.

Thanks guys for your help!.

Regards.

**Comment by torian257x** [comment]
@ArGaspar so what is your final verdict? you pull out of that library or not? different solution?

**Comment by ArGaspar** [comment]
> @ArGaspar so what is your final verdict? you pull out of that library or not? different solution?

Hey 👋, yes I removed the library. Consider this was a long time ago and I do websites as a hobby, maybe the library is more SEO friendly now or you can find a workaround. Either way, I'll appreciate your comments.
