### ISSUE TITLE
Feature Idea - Bounce

### ISSUE THREAD

**Issue by kristenzirkler** [michalsnik/aos#164]
Hi there! Just wanted to make a suggestion for a new animation. Id like an element to be visible on page but jump or bounce or wiggle when the user scrolls to the element. I love the library and thank you!!!

**Comment by michalsnik** [comment]
Hey @kristenzirkler ! Thanks for the suggestion, however I'd like to keep animations as simple as possible and those not very often used leave for the users to add in their projects on their own. You have an example of how to create your own animations in readme (there is even example codepen)  :)
