### ISSUE TITLE
Item not animating on mobile/tablet unless I scroll

### ISSUE THREAD

**Issue by mffallon** [michalsnik/aos#167]
I have a link that is not animating unless I initiate a scroll on mobile/tablet.

There are other elements with animation properties near it that animate just fine on page load (elements are above the fold) I even tried adding the "top-bottom", which is surely the case when the page loads. 

http://www.nfmt.com/orlando2017/default2017.aspx

<a href="" class="btn btn-lg btn-reg ghost" 
                data-aos="fade-up" 
                data-aos-once="true"                 
                data-aos-anchor-placement="top-bottom">Register Today for Free!</a>

**Comment by georgetrad** [comment]
Have you tried setting this option?

`AOS.init({
      startEvent: 'load'
    });`

**Comment by mffallon** [comment]
Thank you!

**Comment by georgetrad** [comment]
@mffallon You're welcome. It worked?

**Comment by mffallon** [comment]
Yep! Did the trick for mobile/tablet issues I had - thanks again.
