### ISSUE TITLE
Not working for bootstrap tab

### ISSUE THREAD

**Issue by brain00021** [michalsnik/aos#169]
I was using your amazing aos plugin to creative animate.
but if I tried to use on bootstrap tab simple, just only display the page can working but another tab content I have to resize Window screen to make your plugin working again. 
Can you help me to fixed this problem ? :(

**Comment by nicole-brooks** [comment]
I just had this problem and fixed it using AOS.refresh() - I had been playing around with it but it wasn't being called before the page had actually changed views. Once I put it inside a very short timeout (10ms was plenty), it refreshed the page correctly and fixed all the animations that otherwise required a page resize to fix.

**Comment by michalsnik** [comment]
Hey, please add:
```
window.addEventListener('load', AOS.refresh)
```
and you should be good.

**Comment by theofficialnar** [comment]
Where do I put AOS.refresh() for it to work?

**Comment by nicole-brooks** [comment]
I put it in the functions that triggered the view change - in my case, I was toggling a filter in AngularJS and set it up in a function like so:

````ctrl.toggleRemediationFilter = function() {
        ctrl.remediationToggle = !ctrl.remediationToggle;
        $timeout(function() {
            aos.refreshHard();
        }, 10);
    }
```

Basically, just set it to refresh (or hard refresh, as I ended up needing) just after the tabs have changed.

**Comment by ijakaric** [comment]
@nicole-brooks Thank you very much!

**Comment by tejassrivastava** [comment]
I Found this solution to be working in React/NextJS.
Whenever the user switches bootstrap navs tab.

```
 useEffect(()=>{
        if(typeof window !== 'undefined' && typeof document !== 'undefined'){
           
            let tabEl = document.querySelector('button[data-bs-toggle="tab"]')
            tabEl.addEventListener('hidden.bs.tab', function (event) {
             
                AOS.refreshHard();
            })
            tabEl.addEventListener('shown.bs.tab', function (event) {

                   AOS.refreshHard();
               })
            	
         }
      })
```
Bootstrap Version : 5.1.0
React Version : 17.0.1
