### ISSUE TITLE
Not working on Safari 4, 5

### ISSUE THREAD

**Issue by Arpi123** [michalsnik/aos#174]
Hi, Thank you for plugin! It's great, the only issue that it's not working on Safari 4 and 5.1(windows). All elements get "opacity:0". Can you please offer a solution for that? Thanks in advance

**Comment by michalsnik** [comment]
Hey @Arpi123 Thanks! Unfortunately AOS does not and won't support Safari 4 and 5.1, these are very old browsers and according to http://caniuse.com/usage-table their usage sums up to to barely `0.03%`. If you want to fix it on them you can use `disable` option:
```
AOS.init({
  disable: function() {
    // This weird line should return true for safari <= 5 and false for anything else
    // Based on http://browserhacks.com/
    return /a/.__proto__=='//';
  }
});
```
