### ISSUE TITLE
Safari 10.1 only works first time

### ISSUE THREAD

**Issue by Jordgubbsbruk** [michalsnik/aos#176]
Trying to configure the scroll effect to trigger once and with a simple center-bottom anchor.

This works great in Edge and chrome. However it does not work with Safari. It does trigger them once, but it works the first time on the page. If one would refresh the page it seems like the offset for the anchors gets messed up and doesn't follow the scroll at all. Wonder if it is something that is messed up by a CSS-position relative or anything like that?

This doesn't occur in Edge or chrome.

**Comment by acahir** [comment]
Found the same problem in Safari 10.1.1. Initial view works, but when page is reloaded, most sections do not display until bottom of page is reached. Then when scroll up content is shown.

**Comment by cschweda** [comment]
+1.

Safari is broken. 10.1.

No animation at all.

**Comment by michalsnik** [comment]
Hey guys, I think I already saw similar issue. Please add:
```
window.addEventListener('load', AOS.refresh)
```
and let me know if your problem still occures :)

**Comment by janstieler** [comment]
Hi,
it solves the problem for me on Safari 10.1.1 (11603.2.5).

Thanks and best wishes,
Jan

**Comment by kaustav-mnm** [comment]
I have added the code to the HTML, But it didn't resolve the problem.
