### ISSUE TITLE
Triggering a custom JS function on scroll

### ISSUE THREAD

**Issue by pauldpritchard** [michalsnik/aos#177]
I have a scenario where I need to trigger a custom JS function as AOS detects that an element has scrolled into view. For example, beginning a slideshow or playing a video when it appears.

Is there a way to trigger this through AOS? Something like `data-aos-function="beginSlideshow"`?

Or, is there a compiled but uncompressed version of aos.js I could customize myself?

**Comment by michalsnik** [comment]
Hey @pauldpritchard, there is no such a functionality and I'm only shipping compressed version of bundled aos. In order to customize it you'd have to create a fork and do so there. Plus there is already another issue #17 with this proposition.
