### ISSUE TITLE
data-aos-delay greater than 3000

### ISSUE THREAD

**Issue by MalickWebbergate** [michalsnik/aos#179]
Hi there!
Just wanted to combine a sequence of animation but i can set a delay greater than 3000ms.
There is a way to set this values/limit heigher?

Thanks in advance.

**Comment by michalsnik** [comment]
Hey, you can generate all the needed delays based on this https://github.com/michalsnik/aos/blob/master/src/sass/_core.scss

By default I'm generating delays up to 3000ms in order to not make the styles too long, but you are free to extend it however you like :)

**Comment by rainb3rry** [comment]
Thank you @michalsnik

**Comment by danieldanielecki** [comment]
To be very honest, I've faced the need to have larger number and not too much happy about the default setup too :(
