### ISSUE TITLE
Issues with react?

### ISSUE THREAD

**Issue by JoelsCode** [michalsnik/aos#18]
I've been trying to implement this with Meteor and React.js is there something that might prevent it from working on this frameworks?

**Comment by michalsnik** [comment]
From version 1.2.1 there shouldn't be problem, AOS is now available as UMD, but to be hones I didn't try it in Meteor application yet.

However Meteor announced native support of node modules in version 1.3 so you should be able to use AOS without problems. Try something like this after installing AOS using npm:

```
import AOS from 'aos';
AOS.init();
```
