### ISSUE TITLE
css - transition-delay: 0; - Invalid Property Value

### ISSUE THREAD

**Issue by rwilsond** [michalsnik/aos#180]
Any reason why "transition-delay: 0;" is specified and not "transition-delay: 0s;"?

Technically it is invalid CSS to omit the 's'.

**Comment by michalsnik** [comment]
No reason at all, probably just an oversight. Thanks for catching this @rwilsond !

**Comment by michalsnik** [comment]
Fixed in upcoming `3.0`: https://github.com/michalsnik/aos/tree/next
