### ISSUE TITLE
Only firing on window resize

### ISSUE THREAD

**Issue by skube** [michalsnik/aos#182]
I'm finding I can only get AOS working when I resize the browser, and only with elements that are currently in the viewport. Scrolling to a blank element and it remains blank.

I've tried initiating and using refresh to no avail...
```
AOS.init();
window.addEventListener('load', AOS.refresh);
```

**Comment by michalsnik** [comment]
Hey @skube, Is it possible that something is expanding content on your page after `load` event on window? Solution with `window.addEventListener('load', AOS.refresh);` should usually fix all the issues with elements not animating.

**Comment by skube** [comment]
I discovered in my case the content was inside some other divs with `overflow: hidden` and `overflow-y: scroll` set. Removing these properties seems to fix the issue.

**Comment by rajesh4295** [comment]
Finally solved this issue by calling refresh method inside scroll listener on parent container .
For angular, add below code in app.component.ts -> ngOnInit()

```
$(".parent-container").on('scroll', function () {
      AOS.refresh();
 });
```

**Comment by eidsza1** [comment]
Try using
```
$(window).on("load", function () {
	AOS.init();
});

```
what is equvalent to

`window.addEventListener('load', AOS.init());`

**Comment by akii09** [comment]
> I'm finding I can only get AOS working when I resize the browser, and only with elements that are currently in the viewport. Scrolling to a blank element and it remains blank.
> 
> I've tried initiating and using refresh to no avail...
> 
> ```
> AOS.init();
> window.addEventListener('load', AOS.refresh);
> ```

This Worked for me thankyou

**Comment by jillii** [comment]
@rajesh4295's answer was the only thing that worked for me.

> Finally solved this issue by calling refresh method inside scroll listener on parent container .
> For angular, add below code in app.component.ts -> ngOnInit()
> 
> ```
> $(".parent-container").on('scroll', function () {
>       AOS.refresh();
>  });
> ```

Isn't this a tremendous strain on the page, though? 

Why does this issue happen in the first place?
