### ISSUE TITLE
How should I import AOS with webpack ?

### ISSUE THREAD

**Issue by PedroEsperanca** [michalsnik/aos#184]
I've tried:

```
import { AOS } from 'aos';
```

```
import * as AOS from 'aos';
```

the error is always:
`Cannot find name 'aos'`

**Comment by PedroEsperanca** [comment]
```
import * as AOS from 'aos/dist/aos.js';
```

did it

**Comment by michalsnik** [comment]
You should be able to simply: `import AOS from 'aos'` this is how I use it and it works fine :)

**Comment by greenchapter** [comment]
I also tried to run aos with webpack and I imported aos in my entry.js like that

`import AOS from '../../../node_modules/aos/dist/aos.js'`

than I added at the and of my HTML file this

`<script> AOS.init({ easing: 'ease-in-out-sine' }); </script>`

But I also get `Uncaught ReferenceError: AOS is not defined`

**Comment by marianoj** [comment]
You need to use import AOS from 'aos'
The import works OK for me but I still get the not defined issue

**Comment by onetrev** [comment]
Similar to what was [noted here](https://github.com/michalsnik/aos/issues/269#issuecomment-383520030), to stop the "AOS is not defined error" I too just had to add the `require` line above the init like so:
```
var AOS = require('aos');
AOS.init();
```
Otherwise as @michalsnik said you should just be able to import AOS as per the docs, `
import AOS from 'aos`'. But I wonder if the var setup line needs to be added to the documentation? Not sure why some folks need that and some do not. But I'm far from a webpack expert.

**Comment by zlinker89** [comment]
this work fine.... only add

`import AOS from 'aos';`
 `import 'aos/dist/aos.css';`

`AOS.init();`

**Comment by koistav1212** [comment]
Where to write import AOS from 'aos' ?
In my Javascript or html or css plzz specify the position..

**Comment by emre-edu-tech** [comment]
In my situation at first
`import AOS from 'aos';`
and
`AOS.init();`
were in different files. Then I put the import statement in the same file with AOS call and now it seems working fine.

**Comment by s17-git** [comment]
i get this error in my browser console when i try : `import AOS from 'aos'`
`Error resolving module specifier “aos”. Relative module specifiers must start with “./”, “../” or “/”.`

**Comment by s17-git** [comment]
i understand my problème, it was i forgot run  :  `npm run build`

am using npm with webpack

**Comment by akshaykadambatt** [comment]
For me the problem was not installing types;
```npm install --save @types/aos```

**Comment by Jayanth-Raavan** [comment]
> this work fine.... only add
> 
> `import AOS from 'aos';` `import 'aos/dist/aos.css';`
> 
> `AOS.init();`

where should I add this? can I add it app.module.ts or should I create new file?

**Comment by heritierbagumire** [comment]
import AOS from 'aos'; 
// and to access this aos package you use 
import 'aos/dist/aos.css';

//in yourexaple component you do this 

const exampleComponent => () {
useEffect( () => {
AOS..init()
}, [])
}
