### ISSUE TITLE
Question: Anchor Placement in default init settings

### ISSUE THREAD

**Issue by nathanaelphilip** [michalsnik/aos#19]
is it: `'anchor-placement'` or `anchorPlacement` ?
I’ve tried both, but neither seem to work.

**Comment by michalsnik** [comment]
I didn't explain it well in documentation, I see this now..

As global setting you can use:
- offset
- delay
- easing
- duration
- disable
- once
- startEvent

So `anchor` and `anchor-placement` are not yet available for setting as default.

**Comment by nathanaelphilip** [comment]
ok, awesome. thanks!
