### ISSUE TITLE
Mobile disable ruins the layout

### ISSUE THREAD

**Issue by stmalk** [michalsnik/aos#190]
Hello, I'm using  `disable: 'mobile'` option to disable aos on mobile devices for my website, so it disables everything, but all elements that were fading in/sliding in etc now are completely invisible in the layout. They stay at their "pre-animation" positions as if they were animated, instead of being present where they have to be with aos off. Is there any way to disable mobile aos use without ruining the layout for all elements? 

Thank you

Quick update: Problem solved by initiating AFTER the layout, not before it. Thanks.

**Comment by Dzordzu** [comment]
I hope this issue will be noticed and marked in the documentation. Loads of unnecessary questions are asked 'cause of that.

**Comment by njgorton** [comment]
By "after the layout", do you mean with script tag at the end of the body? I'm not getting the disable to work at all, either with 'mobile' or window.innerWidth < 1000... It's not however, disappearing as the OP was troubling with, but simply keeps animating regardless of vp width.
