### ISSUE TITLE
White screen on speed tests and performance tests

### ISSUE THREAD

**Issue by vergedesign** [michalsnik/aos#196]
Hello, im getting a white screen when doing a speed test using gtmetric, pingdom and google page speeds, its as if the content doesnt load in the screenshot even though all files etc have loaded?

Any idea why this happens? Is it a bug?

**Comment by michalsnik** [comment]
These tools seem to not trigger necessary events, that AOS is listening to in order to initialise and perform all animations. Therefore I don't think it's a bug. Just the way it is..
