### ISSUE TITLE
Add .aos-animated after the element animates

### ISSUE THREAD

**Issue by dongepulango** [michalsnik/aos#198]
I want to keep my own CSS `transform`and `transition` after the element animates. Is it possible to add class to the element after it animates so I can override the styles? 

Example I have cards that I want to zoom in quick when you scroll past it, but after I want to have a `box-shadow` when you hover over it with smooth and slow transition.

Thanks in advance.

**Comment by michalsnik** [comment]
Hey @dongepulango Given low interest for this feature request in the past year I'm going to close it. Thanks for sharing an idea though! I appreciate it :)

**Comment by omzy** [comment]
+1

I think this is a good feature request. With the `animated` class added we can enable our own custom transitions without having to wrap it in another div.

For completeness it would also be good to have an `animating` class that is applied whilst the animation is taking place.

**Comment by dkjensen** [comment]
+1
