### ISSUE TITLE
Separate in/out triggers

### ISSUE THREAD

**Issue by cupojoe** [michalsnik/aos#199]
It would be great to have a different trigger for the out animation, so you can scroll animate something in and then continue to scroll to animate it out.

**Comment by t22james** [comment]
FYI you can simulate this currently by using a wrapping element and a custom 'out' animation... something like:

```
<section id="section-1"  data-aos="custom-f-out" data-aos-anchor-placement="bottom-center" data-duration="500">
	<div data-aos="fade" data-aos-anchor="#section-1" data-aos-anchor-placement="top-center" data-duration="500">
		My Content
	</div>
</section>
```

```
[data-aos="custom-f-out"] {
  opacity: 1;
  transition-property: transform, opacity;
  &.aos-animate {
    opacity: 0;
  }
}
```

**Comment by michalsnik** [comment]
The main principle of this library is to keep things simple. It's not a library for everything, but rather for most cases :)

**Comment by bluehaus** [comment]
Hey guys, I am looking into trying to have this work without success... anyway I can get some suggestions? 
Thx in advance!
