### ISSUE TITLE
Animations not firing

### ISSUE THREAD

**Issue by nathanaelphilip** [michalsnik/aos#20]
Hi! I hope my many questions aren’t discouraging. I think this plugin is great and will be very useful.

I’m working on this site: http://prd.studiohelm.com.au/ and the bottom 2 images (right before the footer) are not firing properly. Would you mind checking into it and letting me know if I’m doing something improperly?

**Comment by michalsnik** [comment]
Hi, there seems to be an issue with initializing AOS. Like the event DOMContentLoaded is fired before position of all elements is know. You can add:
`AOS.refresh()` on window load and it should resolve your issue.

One more thing: I'm seeing that you use `anchor-placement="bottom-center"`, it means that the element will appear when bottom side of element hit center of viewport. After refreshing AOS on window load positions are calculated properly and items are animating later. You may want to change this anchor to `top-center` or remove it get better effect :) I hope this is helpful in your scenario.

**Comment by nathanaelphilip** [comment]
I used the imagesLoaded plugin to make sure all the images were loading and then fired `AOS.refresh()`. That seems to smooth things out quite a bit. Thanks again!
