### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by JPOak** [michalsnik/aos#200]
Just giving this a go. Seems to be working. Really easy to use. Wondering if it is still being maintained...I get a bunch of errors in my linter about semi colons. But not such a big thing.

Thanks for publishing.

**Comment by michalsnik** [comment]
Yes @JPOak it is :) Linters are set to follow personalised taste, you should not lint code of any packages you use, otherwise you'll get bunch of pointless warnings depending on your config :) One prefers to use comas, other not. Cheers
