### ISSUE TITLE
how to animate elements after become below horizontal line

### ISSUE THREAD

**Issue by jemmeli** [michalsnik/aos#201]
Hi,

when i scroll to bottom i have 2 blocs one comes from right to left & the other comes from left to right and  meet in the middle, the page is long when i reach the footer I scroll to top the 2 element reverse  animation  i want to not be able to see the animation reversing when i scroll top 

Thnak you in advance .

**Comment by michalsnik** [comment]
I'm not sure how I missed this issue... You can use `once` setting - then if you'll scroll down again, the elements will already be in their final positions without animating again. Other than that I'm not sure we can do anything else without hacking. I hope this addresses your concern. If not feel free to reopen and share example codepen, to better illustrate the case :)
