### ISSUE TITLE
aos-animate class doesn't apply

### ISSUE THREAD

**Issue by risha700** [michalsnik/aos#202]
Hello there!, 
I really appreciate your lib which has made things easy; for now it's been couple of days I'm trying to fix that issue about " 'aos-animate' class isn't applied while only class applied is 'aos-init' which makes the element invisible " although I have couple of aos animation working correctly  but were preset before.
briefly: aos-data attribute works on some normally "which has been there long time ago" but any new element I try to add aos-data it goes invisible as the only class applied aos-init.
fixing: made sure of the last version linked, tired to refresh and refreshHard on load, Aos.init(); is placed before /body tag. 
any advise pls!

**Comment by Rst0000** [comment]
Hi! I had same issue and I found this fix: https://github.com/michalsnik/aos/issues/182 and it works well for me

**Comment by bfan1256** [comment]
It would be great if you can close this @risha700 thanks!

**Comment by michalsnik** [comment]
Seems like there is a solution ☝️ If it doesn't work for you feel free to reopen this issue @risha700 :)

**Comment by risha700** [comment]
Thanks Guys
