### ISSUE TITLE
Animations with Delay not working on localhost

### ISSUE THREAD

**Issue by surjithctly** [michalsnik/aos#203]
Hello,

I don't know whats happening, after a lot of debugging, I found that, animations with delay is not working when running inside localhost/simple.html

But when I run via file:/// it works.  Pretty strange!

Code  demo/simple.html 

```
<div class="aos-item" data-aos="fade-up">
        <div class="aos-item__inner"><h3 data-aos="fade-up" data-aos-delay="1000">1</h3></div>
</div>
```
The first fade works on both, but the `h3` fade with delay is not working on localhost :( 

Any help.

~Surjith

**Comment by surjithctly** [comment]
I also found that this issue is happening on chrome only. Mozilla it works fine.

I'm on Windows 8.1 / 64bit

**Comment by michalsnik** [comment]
Unfortunately I wasn't able to reproduce this issue. It seems to be working fine in either of those scenarios. Perhaps it's related with your specific case, the way you load scripts etc. Feel free to reopen this issue if you prepare an example code that should contain the problem (above one works fine).
