### ISSUE TITLE
IE 11 issue with aos.js

### ISSUE THREAD

**Issue by rchin** [michalsnik/aos#204]
I'm receiving the following error when I run AOS.init(); 

Unable to get property 'disable' of undefined or null reference

This only happens in IE11 works as expected in firefox and chrome. I don't see the error when browsing the demo site, but I still get the error above when I reference the aos.js script hosted on CDN for the demo site. What am I missing?

**Comment by laurelstreng** [comment]
I'm also having this issue, only in IE11

**Comment by rchin** [comment]
Hi @laurelstreng, I solved my issue by moving Tag Manager code after aos.js loads. For some reason, it only conflicted in IE.
