### ISSUE TITLE
Can't trigger animation

### ISSUE THREAD

**Issue by adamdc90** [michalsnik/aos#205]
Hi, trying to have a div fade up on "entry" of viewport.

However all it does is hide the div.

In the head I've referenced the aos.js file as:
    <script type="text/javascript" src="js/aos.js"></script>

Below that:
<script>
AOS.init({
easing: 'ease-in-out-sine'
});
</script>

On the div which I want to animate:
<div class="wrap aos-init aos-animate" aos="fade-up" >

Can anybody tell me what I could be doing wrong?

**Comment by andmckvr13** [comment]
try setting the script tags at the end of the body. you may also need to add a delay property to the AOS.init.

**Comment by andmckvr13** [comment]
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Sample</title>
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">

    <link rel="stylesheet" href="aos_sample.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <div class="text" data-aos="fade-up">
      hello
    </div>
    <div class="sampleText" data-aos="fade-down">
      hello
    </div>
    <script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
    <script>
    AOS.init({
      offset: 200,
      duration: 600,
      easing: 'ease-in-sine',
      delay: 100,
    });
  </script>
  </body>
</html>

**Comment by michalsnik** [comment]
Hey, put:
```
AOS.init({ easing: 'ease-in-out-sine' });
window.addEventListener('load', AOS.refresh);
```
right before `</body>`
