### ISSUE TITLE
With Bootstrao only works when resizing window

### ISSUE THREAD

**Issue by sgdanielsanchez** [michalsnik/aos#206]
I have this code:
```
       <div class="col-sm-6 imagealign">
            <br>&nbsp;<br>&nbsp;<br>
            <div data-aos="fade-up">
            <img src="im/Athletes.svg" style="width:85%; height:auto;">
            </div>
        </div>
```

Only after I resize the window the classes begin to change and the effect to apply. I've tried adding:

```
$(window).on('load', function() {
  AOS.refresh();
});
   
```
but I cant make it work

**Comment by sgdanielsanchez** [comment]
This is the code:
`        <div class="col-sm-6 imagealign">
            <br>&nbsp;<br>&nbsp;<br>
            <div data-aos="fade-up">
            <img src="im/Athletes.svg" style="width:85%; height:auto;">
            </div>
        </div>`

**Comment by michalsnik** [comment]
If this doesn't work, then there has to be something else on your page causing AOS to have problems with calculating trigger positions. I wasn't able to reproduce this issue ;/ Please feel free to reopen it by providing example codepen that has similar problem :)
