### ISSUE TITLE
Animations sometimes trigger, other times don't

### ISSUE THREAD

**Issue by anchorwut** [michalsnik/aos#208]
First of all, huge thanks for your wonderful library! It's incredibly handy!

I have a series of identical container divs, stacked vertically, each one filling the viewport (width:100vw; height:62.5vw;). Inside the container div I have others sub-divs with text, images etc. Those sub-divs have an data-aos class to trigger an animation. Sometimes it happens (so I know it's set up properly) but other times the content just remains hidden - seemingly at random. I've tried changing the offset from 120 to 0 or 300, but it doesn't help.

Here's the extra wrinkle that I'm certain is causing the problem. I'm using [Scrollify](https://projects.lukehaas.me/scrollify/) to produce scroll-snapping, so when you scroll it snaps from div to div. I'm pasting the settings for the Scrollify script below. When I change "setHeight: false" AOS behaves properly (all animations trigger), but then Scrollify doesn't do the snapping exactly as it should

Any advice would appreciated.

```
<script src="https://projects.lukehaas.me/scrollify/script/jquery.scrollify.js"></script>
    <script>
    $(function() {
      $.scrollify({
          section : ".scrolltohere",
          sectionName : "section-name",
          interstitialSection : "",
          easing: "easeOutExpo",
          scrollSpeed: 1100,
          offset : 0,
          scrollbars: true,
          standardScrollElements: "",
          setHeights: true,
          overflowScroll: true,
          updateHash: true,
          touchScroll:true,
          before:function() {},
          after:function() {},
          afterResize:function() {},
          afterRender:function() {}
        });
    });
  </script>
```

**Comment by michalsnik** [comment]
Hey @anchorwut Sorry for replying just now..
Scrollify calculates height of their sections and thus the trigger points for all AOS elements are becoming obsolete. Make sure you refresh AOS on render and resize:
```
$.scrollify({
  ...,
  afterResize: AOS.refresh,
  afterRender: AOS.refresh,
});
```

I believe this should solve your issue :) If not - feel free to reopen this topic.
