### ISSUE TITLE
Consider to use IntersectionObserver

### ISSUE THREAD

**Issue by snc** [michalsnik/aos#21]
Maybe IntersectionObserver can be used in the future, this was recently added to Chrome 51.

https://www.youtube.com/watch?v=LXbtIeHIQJA
http://rawgit.com/WICG/IntersectionObserver/master/index.html
https://github.com/Fyrd/caniuse/issues/2425

**Comment by michalsnik** [comment]
Hi @snc,

I'm aware of that and keep it in mind :)

Unfortunately for now I can't use this solution due to cross browser compatibility :/ Plus I'm not sure if this will help to achieve some of the features that I already implemented, calculating offest is a little more complicated considering all possible settings than just observing viewport.

Thanks for your message anyway! :)

**Comment by rjgotten** [comment]
@snc 
@michalsnik 

I'd suggest using a polyfill that already matches the IntersectionObserver contract and then switching on use of the native IntersectionObserver, but **ONLY** once the Chrome devs fix their implementation to operate according to (draft) spec.

Currently there's a very annoying bug with observers that use the default configuration of `[ 0 ]` for the array of threshold points. Threshold intervals are supposed to be open-start with closed-end, i.e., the default configuration should translate to two intervals:  `( ... , 0]` followed by `( 0, ...)`. However, Chrome incorrectly implements the reverse: `( ..., 0 )` followed by `[ 0, ... )`.

This means Chrome enqueues change records at *exactly* a zero intersection ratio, while it's *supposed* to enqueue them at a greater-than zero intersection ratio.  In turn, this causes simple `ratio > 0` checks for visibility to intermittently fail, whenever after a scroll an element is on the cusp of becoming visible. (I.e. it has a coincident edge with the viewport and thus an exact zero intersection ratio.)

It's incredibly annoying to work around as well.

**Comment by graingert** [comment]
https://github.com/WICG/IntersectionObserver/blob/gh-pages/polyfill/README.md

@michalsnik fyi intersection observer can calculate any intersection and next week will be available in all good browsers.

**Comment by artursopelnik** [comment]
+1

**Comment by aaronransley** [comment]
Dropping in to bump this. AOS is our favorite drop-in solution for animating on scroll, but it would be nice if it used IntersectionObserver in evergreen browsers, and perhaps polyfilled older browsers?

**Comment by willryanuk** [comment]
Wanted to bump this as well. AOS is absolutely brilliant, but a future version which used the efficiencies of IntersectionObserver might be quite a neat approach.
