### ISSUE TITLE
AOS only working with zoom

### ISSUE THREAD

**Issue by jvitoroc** [michalsnik/aos#210]
When I scroll to my form with zoom 100%, it does not work, but when I put zoom 33% the form appears, but I cant scroll

Here is my code: 
`<form data-aos="fade-up" data-aos-anchor-placement="top-center" class="contact-form">`

![Uploading ae.PNG…]()
![ae2](https://user-images.githubusercontent.com/25753747/29496923-d4a85ca4-85b3-11e7-9b2f-f0c438db1614.PNG)

**Comment by hapiscalin** [comment]
I do have same issue with this scrolling won't work but if I zoom out or in once the animation activates.
