### ISSUE TITLE
when I add animation to the topmost element it's not animating even once

### ISSUE THREAD

**Issue by mohananagavenkat** [michalsnik/aos#212]
In html file for the uppermost element I applied Aos animation but It's not animating, where as below one's are working. Even I had put offset to 0. still no use.

**Comment by xApep** [comment]
I think that's because of the offset. I had the same issue and i figure out if I set

```
    setTimeout(function() {
        AOS.init({
            duration: 1000,
            offset: 200
        });
    }, 100);
```

it works like charm.
