### ISSUE TITLE
Anchor placement as option in the default configuration?

### ISSUE THREAD

**Issue by Jugibur** [michalsnik/aos#216]
In the docs it says the anchor placement can be set in the default config without prefix "data-aos" – but is this true?
I'm not able to get it running.
Have tried: 
-  ` placement: 'bottom-bottom'`
and
-  `anchorPlacement: 'bottom-bottom'`

Can't find any hint about this in the code so perhaps it isn't possible to set as default.

**Comment by b-strauss** [comment]
I also encountered this. Anchor placement is not read from the options object.

**Comment by michalsnik** [comment]
You're right. Anchor placement is an `inline-only` option. The documentation is going to be simplified and updated in upcoming v3: https://github.com/michalsnik/aos/tree/next so I'm closing this issue for now :)
