### ISSUE TITLE
Feature request: Add more then one class to "data-aos"

### ISSUE THREAD

**Issue by Jugibur** [michalsnik/aos#217]
This would be great for having different animations for different Breakpoints / Viewport sizes.

i.e.: Sometimes a slide in isn't always the best way if there are other elements next them. So then a simple fade would be the best way. On other screens there might be no element next to them and a slide-in would be great.

**Comment by michalsnik** [comment]
That's why AOS allows you to add your own custom animations and have full control over them using CSS and it's breakpoints :)
