### ISSUE TITLE
Some Animation Doesn;t Work

### ISSUE THREAD

**Issue by tabibintang** [michalsnik/aos#218]
I don't know why but always stuck on some element and the next animation doesn't work

But If I inspect the element from my browser, then I close the inspect feature, it make the animation work again (without doing anything on inspect element, just open and close). I'm really don't understand what's wrong

Is it a bug or something?
Please help
Thanks in advance

**Comment by digelim** [comment]
+1

**Comment by lucasdc** [comment]
+1

**Comment by brickmaker** [comment]
+1

**Comment by Sladix** [comment]
I just experienced a similar issue where the animations worked fine until some point where all the next ones didn't triggered.
I had some img with empty src in the last animated element. Adding an src solved my issue.
So maybe malformed/empty attributes can break AOS ?

**Comment by jmartsch** [comment]
I had exactly the same problem as @Sladix 
After correcting the image src AOS worked again on ALL elements

**Comment by shamirkaaa** [comment]
+1

**Comment by LuckyLam34** [comment]
@jmartsch How did you solve the issue? I notice after removing all images the animation works so fine.
The issue I'm experiencing is that the animation won't work if the browser is not in fullscreen mode.

**Comment by jmartsch** [comment]
@LuckyLam34 Please read my previous comment on this.
My problem was an invalid src attribute (src was empty) because of lazyloading images. After adding a correct src path everything worked fine as you can see here https://www.p-jentschura.de/de/ueber-uns/historie/

**Comment by LuckyLam34** [comment]
@jmartsch in my case only by removing all the img tags the animation will work. Do you have any ideas?

**Comment by bfan1256** [comment]
@LuckyLam34 , the `src` attribute cannot be empty and neither can the `alt` attribute. Try this:
```html
<img src="/path/to/image">
```
and exclude the `alt` attribute.

**Comment by LuckyLam34** [comment]
@bfan1256 removing the alt att didn't work but your trick was a great suggestion. Thanks :)

**Comment by bfan1256** [comment]
Great! I'm glad it worked @LuckyLam34 !

**Comment by michalsnik** [comment]
Images may cause further content to be placed below their initial positions in which they were initialised by AOS before loading those images. In result trigger points do not match, and it might seem that animations are not working. What might also work for you is refreshing all calculated position after window load event:
```
window.addEventListener('load', AOS.refresh);
```
Feel free to reopen this issue if the problem still occurs.

**Comment by shriyajuneja** [comment]
Animations on images are being triggered way before they come in view, hence it appears they are not working , AOS.refresh on load doesn't solve the issue for me
