### ISSUE TITLE
dist directory missing .map files

### ISSUE THREAD

**Issue by dariusj18** [michalsnik/aos#224]
Both the aos.css and aos.js files point to map files which are not in the dist folder

**Comment by OVigilante** [comment]
The file aos.js.map continues to be called in aos.js on dist directory.
Is it needed the .map file or not?
If not, can be removed from the aos.js on git repository?

**Comment by michalsnik** [comment]
I'm going to release v3 in this week probably as beta, and this problem is addresses there. You can already check the `next` branch :)
