### ISSUE TITLE
Release Mutation Observer version?

### ISSUE THREAD

**Issue by BrunoCartier** [michalsnik/aos#225]
Hey,

When do you think you will be able to release the last version of the script (using the Mutation Observer API)?
It would make audit tools happy and stop warning in console, so it would be really nice.

**Comment by michalsnik** [comment]
Hey, sorry for such a long overdue. You can check `2.3.0` - it contains the update :)

**Comment by artursopelnik** [comment]
+1

Here a great example with aos:
https://codepen.io/artursopelnik/pen/qYwxeQ
