### ISSUE TITLE
Flip animation possible bug in safari

### ISSUE THREAD

**Issue by alexr101** [michalsnik/aos#235]
I noticed a possible bug with flip animations in safari. When you're scrolling down you can see the content of the animation just linger there waiting for you to scroll down. You can actually experience this in the demo page, under the fip animations.
[](http://michalsnik.github.io/aos/)

Is this how it's supposed to work?
I already created a fork, and a fix that I can merge if that's not the case. thanks!

**Comment by likoharo** [comment]
Change 100deg for 90deg in the css, and you will not see it...

**Comment by michalsnik** [comment]
This issue is fixed on `next` branch. I'm going to release v3 beta during this weekend.
