### ISSUE TITLE
Safari Bug: Anchor position gets inaccurate on longer pages

### ISSUE THREAD

**Issue by Jugibur** [michalsnik/aos#237]
I've found that Safari (V. 10) moves the "offset" of an animation anchor up the longer a page get.
So on very long pages a bottom anchor can move from bottom to top. Strange...

**Comment by michalsnik** [comment]
Hey @Jugibur I tried to reproduce this problem, but with no luck.. It was probably caused by too early initialization of AOS. It might be solved with:
```
window.addEventListener('load', AOS.refresh)
```

If this problem still occurs, feel free to reopen this issue and provide an example codepen that replicates it.
