### ISSUE TITLE
AOS and Dynamically loaded elements

### ISSUE THREAD

**Issue by HuwJanus** [michalsnik/aos#240]
Great library, but Iv found a problem:

I have AOS initialized and working fine, however, dynamically loaded content (Using jQuery.Load) breaks AOS and elements are not animated on the loaded content. AOS is set to watch the container, and it does, but only up until I load some new content.

Iv added a refresh() in the callback on the load() function but to no avail, and Iv even tried to re-initialize AOS in that location, so that the content has been loaded. This doesn't work.

Any advice/ideas would be much appreciated.
Regards, Huw

**Comment by Tusko** [comment]
+

**Comment by luckyrabbitllc** [comment]
Just ran into this same issue.

**Comment by manuel-84** [comment]
refresh is not working for me too, so I made this:
  
```js
var x = document.getElementsByClassName('aos-animate');
for (var i = 0; i < x.length; i++) x[i].classList.remove('aos-animate');
window.dispatchEvent(new Event('resize'));
```

**Comment by michalsnik** [comment]
Hey @HuwJanus I tried to reproduce this issue using exactly jQuery load, but with no luck. It seems to be working fine. Please try 2.3.0 and let me know if you still experience the same issue. If yes - please reopen this issue and provide an example codepen/sandbox that reproduces it.
