### ISSUE TITLE
AOS not working with react create app

### ISSUE THREAD

**Issue by Defite** [michalsnik/aos#242]
Hi. As I've said in title - can't make it work in any component in React Create App. For example:

```
import React, { Component } from 'react';
import AOS from 'aos';

import './App.css';
import '../../../node_modules/aos/dist/aos.css';

class App extends Component {
constructor(props, context) {
    super(props, context);
    AOS.init();
  }

  componentWillReceiveProps() {
    AOS.refresh();
  }

render() {
    return (
      <div className="App" data-aos="zoom-in">123</div>
   );
}
}
```

This will simply hide my div. I use latest version of AOS.

UPD. If I run `npm ru build`, aos works well with static html.

**Comment by kozubenko** [comment]
You should run init function on componentDidMount method in your root component and link styles to global css file

**Comment by Defite** [comment]
Linking to global css is not working at all :(

**Comment by Defite** [comment]
Ok, I solved it. AOS styles were messed by css modules localIdentName, so adding aos-animate class did nothing.

**Comment by GeorgeGoodall** [comment]
is it not possible then to use css modules while also using aos then?
