### ISSUE TITLE
can not link css in create react app

### ISSUE THREAD

**Issue by kozubenko** [michalsnik/aos#243]
Hello.

I use create-react app.
My init function is implemented like this:

```
 componentDidMount () {
    this.initAnimation();
  }

  initAnimation = () => AOS.init({ duration: 700, delay: 100, easing: 'ease-in-sine' });
```

But I have problem with link css.

1. If I link it to root html it does not work. I did it like in guide.

`<link rel="stylesheet" href="/node_modules/aos/dist/aos.css" />`

2. Also I tried to import it to my global css file:

`@import "~aos/dist/aos.css";`

But in source in devtools I see root html in this css file, please help me to understand a reason.

![1](https://user-images.githubusercontent.com/28056478/32510187-5aaf4e8e-c3f8-11e7-98b2-efb0143775ef.png)

Thank you.

**Comment by Yhozen** [comment]
I'm using react and I just added `import 'aos/dist/aos.css'` at the beginning of the App.js

**Comment by michalsnik** [comment]
Hi @kozubenko There was already another issue posted about React, and it's already solved: https://github.com/michalsnik/aos/issues/49
Check it out :)
