### ISSUE TITLE
"Once" setting causes animations to stop

### ISSUE THREAD

**Issue by krhansen** [michalsnik/aos#246]
Whenever I add the "once" setting it causes animations to stop working. I've tried adding it as the default:
`AOS.init({
once: true,
});`

And I've tried adding it to individual elements like this: data-aos-once="true" or data-aos-once=true. 

Either way causes some of the animations not to work. 

On this site: [http://test.ncacu.org/](url) all of the sections have data-aos="fade" set. On my monitor the "check out our great rates" section is completely out of view. When I scroll down it is visible but doesn't fade in. The following three sections do fade in. 

This problem also occurs if any part of the "apply for a loan" section is visible in regard to the featured products section (colored circles section). In other words, if any part of the "apply for a loan" section is visible, the products section is visible but doesn't fade in. In this scenario all of the following sections fade in as expected.

Anyone else having this problem? Am I doing something wrong?

Thanks in advance for any help!

Kurt

**Comment by michalsnik** [comment]
Hey @krhansen It seems like it might be a problem with AOS being initialized too early.

Try adding:
```
window.addEventListener('load', AOS.refresh);
```
And feel free to reopen this issue if it doesn't help :)

**Comment by Bdur604** [comment]
Hi michalsnik, 

I got same problem when i add once: true . Animation stop working. above solution you gave didn't work for me. Can you please help on this.

Thanks

**Comment by adt-mgpark** [comment]
I solved this issue by adjusting the script location.

before
```
-- html
...
  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
</head>

-- js
AOS.init({
    once: true,
  });
```
after
```
...
  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init({
      once: true,
    });
  </script>
</body>
```
