### ISSUE TITLE
Ajax and AOS

### ISSUE THREAD

**Issue by MohOulabi** [michalsnik/aos#249]
Hello,
Am facing a little problem here
When I try to call the body or any div that contains AOS using ajax.
AOS breaks.
I tried to add AOS.refresh() to the ajax or to a delayed jquery that runs after the ajax is called.
I couldn't find a soltuion :(
I need help in this issue because it will change the who performance of my website.
Thank you for everthing

**Comment by jmartsch** [comment]
Please describe this problem better. It is hard to understand what you are doing. What does "AOS breaks " mean?
I implemented it with Ajax and it is working fine.
Here is the jQuery Code that I used:
```
$.ajax({
            url: this.href,
            // headers:{
            //     'X-Requested-With' : 'ajax'
            // }
        })
            .done(function (data) {
                $('#ajax').html(data);

                $(pagination).html(
                    $('#ajax').find('.pagination').html()
                );
                var $content = $('#ajax').find(container);
                $(container).append($content.html());
                AOSrefresh();
                autoHeightAnimate($(container), 500);
            })
            .fail(function () {
                $(next).removeClass('disabled is-loading');
                $(e.target).off('click');
            });
```

**Comment by MohOulabi** [comment]
When I called the body as data in  .done function
I tried to call AOS.refresh();
but every div that has AOS in it.
the animation breaks and wont happen any more when I scroll.
I don't know why :(

What I basically did 
I removed the body on load
in done function I wrote this


.done(function (data){
setTimeout(function(){
$('.page').html(data);
AOS.refresh();

},1000);
});

$('.page') is the div that will call the whole page 
The page is called correctly, everything is there with class names and data-aos
but the animation isn't working at all

**Comment by MohOulabi** [comment]
I had a script that removes the body and recall it using ajax (to improve the page loading speed ) I couldn't find a way to retrieve the animation

**Comment by michalsnik** [comment]
You can't remove `body` @MohOulabi. AOS sets imporant `data-aos` attributes on body that are required for it to work properly. You should rather replace it's content, or better some div's content.
The ajax itself seems to work fine and newly added items are animated correctly.
