### ISSUE TITLE
Animation distance

### ISSUE THREAD

**Issue by dawidtokarz** [michalsnik/aos#251]
Hi guys,

I'm using AOS script in one of my projects and there is an image set as position fixed in the bottom of a page. (with AOS animation in use). Element should entirely dissapear with animation (fade-down). It is almost working properly, but I don't know how to set more distance for that specific element (it is not hidding completely). Any idea?

**Comment by dawidtokarz** [comment]
Ok, I figured it out. I just added transform: translate(0, -500px) for specific animation (fade-down).

**Comment by bfan1256** [comment]
Nice @dawidtokarz , if you have found the solution. Can you close the issue! That would be very helpful for @michalsnik ! Nice man!

**Comment by baffleinc** [comment]
If you are using SCSS, before you import aos's scss you can define a variable like so: `$aos-distance: 25px;`

This would reduce the distance of all animations to 25px.
