### ISSUE TITLE
Aos is not working on mobile

### ISSUE THREAD

**Issue by memoseis** [michalsnik/aos#252]
Hi!

I'm new working on this. Currently, I'm using your library on my website: www.guillermoseis.com 

Everything seems to work perfectly. Desktop and mobile inside my browser. However when I check the website on my phone the animations are missing. I already installed twice the library and check the console however, I coudn't fix it. Maybe you could enlight me if I'm doing something wrong or it's a bug.

Thank you a lot!

**Comment by memoseis** [comment]
I already found the error! LOL thanks!

**Comment by nik72619c** [comment]
im facing the same difficulty...plzz help ! :)

**Comment by sanjeevdhiman** [comment]
solution ! working perfect in mobile screen horizontal scroll
html, body{
overflow-x:hidden;
}

**Comment by Nomaan786** [comment]
> I already found the error! LOL thanks!

How you get it ?
