### ISSUE TITLE
Used in a loop?

### ISSUE THREAD

**Issue by mlangone** [michalsnik/aos#258]
I have a if while wordpress loop that is displaying some content in a grid 3 divs per row.  is there a way to have the animation  for each div fire almost numerically?

example:

1  2  3
4  5  6
 7  8

So 1 fires then a delay then 2 fires etc?

`    <?php if( have_rows('specific_service') ): ?>
        <div class="row">
            <?php while( have_rows('specific_service') ): the_row();?>
                <?php $link = get_sub_field('service_page_url'); ?>
                    <a class="service-link large-4 medium-4 small-12 columns " href="<?php echo $link; ?>">
                        <div class="text-center">
                            <div class="outer-service-box">
                                <h2 class="service-type"><?php the_sub_field('service_type'); ?></h2>
                                <p class="service-description"><?php the_sub_field('service_description'); ?></p>
                                <p data-aos="fade-up" data-aos-anchor-placement="top-bottom" data-aos-offset="200" data-aos-delay="300" class="the-checkmark"></p>
                            </div>
                        </div>
                    </a>
            <?php endwhile; ?>
        </div>
    <?php endif; ?>`

**Comment by jongc** [comment]
You can have a counter in the loop that increments the delay for you like...

```php
<?php if ( have_rows( 'specific_service' ) ): ?>
	<div class="row">
		<?php $delay_count = 0; ?>
		<?php while ( have_rows( 'specific_service' ) ): the_row(); ?>
			<?php $link = get_sub_field( 'service_page_url' ); ?>
			<a class="service-link large-4 medium-4 small-12 columns " href="<?php echo $link; ?>">
				<div class="text-center">
					<div class="outer-service-box">
						<h2 class="service-type"><?php the_sub_field( 'service_type' ); ?></h2>
						<p class="service-description"><?php the_sub_field( 'service_description' ); ?></p>
						<p data-aos="fade-up" data-aos-anchor-placement="top-bottom" data-aos-offset="200" data-aos-delay="<?php echo $delay_count * 300; ?>" class="the-checkmark"></p>
					</div>
				</div>
			</a>
			<?php $delay_count++; ?>
		<?php endwhile; ?>
	</div>
<?php endif; ?>
```

**Comment by mlangone** [comment]
Thank you

**Comment by bfan1256** [comment]
I'm glad you've solved it @mlangone @jongc . Could you close the issue so that there aren't as many for @michalsnik? Thanks guys!
