### ISSUE TITLE
关于AOS在angular2里引入可以出一二教程。

### ISSUE THREAD

**Issue by xueyuman** [michalsnik/aos#259]
我的Aos在angular2里引入后没有作用

**Comment by bfan1256** [comment]
You have to add an `app.js`
Inside `app.js` add:
```javascript
AOS.init()
```
In `.angular-cli.json` add:
```
"scripts": [
            "assets/path/to/aos.js",
            "assets/path/to/app.js"
        ]
...
```
Then it will work.

**Comment by bfan1256** [comment]
This issue should be closed as a solution has already been proposed. @xueyuman please close this issue.
