### ISSUE TITLE
AOS stopped working after https migration

### ISSUE THREAD

**Issue by jplozgom** [michalsnik/aos#267]
Hi. I installed my SSL and redirected all my traffic to https and after this AOS doesn't work. Elements with animations don't appear, elements without animation appear.

any idea?

thanks

**Comment by Dzordzu** [comment]
Can you show us a log from web console?

**Comment by padhyakash** [comment]
@Dzordzu same thing happened to me too, AOS working fine on my local machine but not working on my dev server and getting init error like: **ReferenceError: AOS is not defined**

**Comment by michalsnik** [comment]
I'm closing due to long overdue. It looks though that you were loading AOS with `http` link, and thus it wasn't loading on `https` connection. Feel free to reopen if you'll experience further issues regarding this topic.
