### ISSUE TITLE
Animations Do Not work during scoll on Mobile Web@Work Browser

### ISSUE THREAD

**Issue by osmosisfilms** [michalsnik/aos#273]
When loading a web page with AOS, on a mobile device with the Web@Work browser, the animations only activate when the scroll is at complete stop. In other words, the animations effectively do not work if the user is continuously scrolling. 

Has anyone seen a similar issue and have a solution?

**Comment by michalsnik** [comment]
Hey, please try to:
```js
AOS.init({
  startEvent: 'load'
});
```
or add:
```js
window.addEventListener('load', AOS.refresh);
```

This should solve your problem. If not feel free to reopen this issue :)

**Comment by luisgabriel84** [comment]
in any viewport between 360px and 737px animations dont work
