### ISSUE TITLE
Make data-aos-once="ture" the default 

### ISSUE THREAD

**Issue by wilcarter15** [michalsnik/aos#275]
I read through the README.md and it all made sense.  I understand that the default value for 'data-aos-once' is false and so all animation will reset every time.  I want to change the default from false to true but I am having a hard time finding/figuring out where to do that.  Am I missing something obvious?

I don't think I need to show you any code, simply need to be pointed in the right direction.  I tried searching everywhere I could think of for the answer.

Thanks in advance!

**Comment by rafayhingoro** [comment]
just simply use that 
```

AOS.init({
   once: true
})
```

**Comment by wilcarter15** [comment]
perfect!!  Thanks a bunch!

**Comment by nileshkikani** [comment]
Thanks its help me to disable animation on each load.

**Comment by AdrianKnapp** [comment]
THANKSSSSSS!!!!!!!!!

**Comment by silfrido-porta** [comment]
eleven does not deactivate the animation. Any suggestion?

**Comment by ArnoNymeier** [comment]
Hi silfrido-porta , this works for me :-)
```
<script>
AOS.init({ once: 'true'
	});
</script>
```
