### ISSUE TITLE
Using AOS with vh dimensions

### ISSUE THREAD

**Issue by colinmacleod** [michalsnik/aos#277]
I have a design that uses vh dimensions to scale with the height of the viewport.

AOS doesn't seem to like this.

This fiddle demonstrates the situation: https://jsfiddle.net/e9kL84rc/3/

There are 2 headings with animations. Between them is a div scaled to 80% of the viewport height.

The second animation does not show, no matter how far you scroll down.  

Any ideas?

**Comment by colinmacleod** [comment]
OK - after some more digging, it's actually the height: 100% in the body it doesn't like

**Comment by Bagera** [comment]
Your <body> is just as tall as your viewport in your example. If you set min-height instead it will grow with the content or just don't set it if you don't need it. It's no fix for aos not working below <body> but it's a fix for not getting stuff outside of body

**Comment by colinmacleod** [comment]
Yes, indeedy. Thanks for the explanation. I found just removing the 100% height from html was enough to fix it: https://jsfiddle.net/e9kL84rc/6/
