### ISSUE TITLE
resolve-url-loader cannot operate: CSS error

### ISSUE THREAD

**Issue by erwin16** [michalsnik/aos#278]
using resolve-url-loader, got an error 👍 

`(Emitted value instead of an instance of Error)   resolve-url-loader cannot operate: CSS error
  ENOENT: no such file or directory, open '/Users/yves/Developments/WIP/VUE.JS/le-choro-des-charentes%20webp
ack/node_modules/bootstrap/dist/css/bootstrap.css.map'
  at Object.fs.openSync (fs.js:646:18)`

After checking aos/dist/aos.css , discovered a comented line which is faulty one .. ( I don't know why actually ...)

    **/*# sourceMappingURL=aos.css.map*/**

removing this line , building  is oK .... 

Do you understand why ? Is this commented line necessary in the css file ?

I asked also bholloway at [bholloway/resolve-url-loader
 ](https://github.com/bholloway/resolve-url-loader/issues) why this  commented line is taken in account during webpack compilation phase...

**Comment by erwin16** [comment]
can someone answer this question ?  why this commented line ....

**Comment by michalsnik** [comment]
Hey, please try 2.3.0. I removed source maps there :)

**Comment by IzaGz** [comment]
same trouble, should i remove that line?
