### ISSUE TITLE
Bouncing elements when at top

### ISSUE THREAD

**Issue by noisypope** [michalsnik/aos#282]
When I put aos on elements that are at the top of the page they move to the top of the page, getting hidden for seconds and then bounce to their original position. Someone knows why this is happening? 

Example of my page: noisypope.com

**Comment by Scordavis** [comment]
Try to set body in height: 100%;

**Comment by noisypope** [comment]
I tried, but wasn't that

**Comment by noisypope** [comment]
Now I've just discovered it happen to me when I have the developer tools open on Chrome... any ideas way ?

**Comment by michalsnik** [comment]
Hey @noisypope. Can you provide an example codepen/sandbox that reproduce this issue?

**Comment by Alaamasoud** [comment]
@michalsnik 
I have exactly the same problem , i tried to skip the first section from getting the style but still had this issue .

http://staging.bluewave.c2g4.concepts2go.com/nl-NL/recruitment-cases

**Comment by michalsnik** [comment]
I see it's still happening on your page. And I think it's because of the sticky header - it's height is being automatically calculated, and affects position of boxes below, that's why item's are `bouncing`. Set fixed height on header and all should be fine ;)
