### ISSUE TITLE
AOS and tabs : don't work

### ISSUE THREAD

**Issue by testy60** [michalsnik/aos#284]
Hello,

I use AOS on my website but there is a problem with pages that contain tabs. Indeed the height of the page is reduced when you move from one tab to another, so the animations AOS are impacted. A solution please ? To see an example, click here (the animation is at the bottom of the page, then click on the "news" tab) : https://www.cotizup.com/pour-cochise

Thank you !

**Comment by michalsnik** [comment]
Hey @testy60. After changing the documents' height you should call `AOS.refresh()` and it should work fine then :)
