### ISSUE TITLE
Mysterious code in aos.js

### ISSUE THREAD

**Issue by uboubo** [michalsnik/aos#287]
What's the purpose of

`,r=/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp` etc?

**Comment by tedgeving** [comment]
Looks like it is for mobile detection, similar to:
https://github.com/hgoebl/mobile-detect.js/blob/master/mobile-detect.js

**Comment by michalsnik** [comment]
Exactly ☝️
