### ISSUE TITLE
re-initiating AOS animation when revealing hidden elements conflicts with anchor position

### ISSUE THREAD

**Issue by mariodermez** [michalsnik/aos#289]
In order to trigger a div to - for example - fade-in it has a default anchor point position and depending on the scroll offset it will animate. But if you're running many divs that some of them need to be hidden (by using some JS and display:none) and load them later (by clicking eg. "Load more" button) that means that if you re-initiate AOS again (using the script below) the just-revealed div will animate after it has been already shown on the screen which obviously doesn't look nice as you want the default to be hidden and not be visible with wrong animation.

So my opinion is that when a new div appears on the screen ( the on-screen-code  was hidden with display:none) it needs to be hidden (this time using opacity). In the background you need to calculate its new position according to the applied code (eg. anchor position etc) and if the offset is already far from the point that it would trigger the div to animate (if the div was visible in the first place) then it needs to remain hidden and have it animate when you scroll back to the top and then back down again. 

```
 <script>
        $(function() {
      AOS.init({
        easing: 'ease-in-out-sine'
      });
    
      $('.js-load-more').on('click', function() {
        var $content = $(this).next('.js-more-content');
        
        $content.animate({
          height: 750,
        }, 500);
      });
    
      onElementHeightChange(document.body, function(){
        AOS.refresh();
      });
    });
    
    function onElementHeightChange(elm, callback) {
        var lastHeight = elm.clientHeight
        var newHeight;
        
        (function run() {
            newHeight = elm.clientHeight;      
            if (lastHeight !== newHeight) callback();
            lastHeight = newHeight;
    
            if (elm.onElementHeightChangeTimer) {
              clearTimeout(elm.onElementHeightChangeTimer); 
            }
    
            elm.onElementHeightChangeTimer = setTimeout(run, 200);
        })();
      }
    </script>
```

**Comment by michalsnik** [comment]
Hey @mariodermez Thanks for posting this issue, however I think this is an edge case and I won't give it a high priority given other more direct things  that I have to work on. I'm going to close this issue for now and mark as `won't fix`. The main principle behind this library is `simplicity` and it's not built to cover all possible cases (and specifically not crazy dynamic ones).

If you however have a decent solution in mind and are willing to submit PR for further consideration - feel free, I'm always happy to see contributions :)
