### ISSUE TITLE
The demo site download button links to an old version of AOS

### ISSUE THREAD

**Issue by adamhughes86** [michalsnik/aos#29]
I know this isn't directly an issue with the plugin but thought it would be the best place for it.

I'd recommend updating the link to always get the latest. At the moment if someone downloads from there and reads the docs stuff won't work.

**Comment by michalsnik** [comment]
Hi @adamhughes86, thanks for point this out.
I fixed it already, and now button directs to the newest version.

FYI I'm going to work on a new demo with more examples soon :)
