### ISSUE TITLE
AOS causing odd hopping effect on normal hover CSS attributes, only with fixed navi

### ISSUE THREAD

**Issue by kevin-akita** [michalsnik/aos#291]
I've been developing a site lately that is using a fixed navigation bar at the top of the website, when the DOM activates an animation via an element that has the aos animation tags in the tag class, the navigation bar hops about a 1 pixel up and down. Once this happens once, it'll continually bounce 1 pixel everytime a clickable link is hovered over, until you scroll back to the top of the page. 

I've disabled the AOS library to confirm that it was the cause, but Im at a loss as to why this might be happening. 

EDIT: I've managed to fix the issue on my end with a rewrite of the html code and css. 

It seems that this is an issue regarding <a> anchor attributes when being hovered over on fixed navigation bars if there has been a css animation rendered by AOS in the DOM. The odd thing is that it only affects the <a>:hover status when there is a transition applied to it with css.

**Comment by michalsnik** [comment]
Hey, you can also check 2.3.0, we've changed some styles there and it might've fix your issue by the way too :)
