### ISSUE TITLE
Transforms replacing existing transforms

### ISSUE THREAD

**Issue by rctneil** [michalsnik/aos#294]
Hey,

Really like the AOS library. Make sit super simple to add incoming build in animations to elements in no time. The one issue i've come across that I can't seem to find a solution for is as follows:

Say I have an element that is vertically centered using the following:

```
.element {
position: relative;
top: 50%;
transform: translateY(-50%);
}
```

This is perfect but as soon as the animation is attached, the animation transforms overwrite the transforms I put on the element originally.

Is there someone of adding the animation ones additionally or another way of working around this?

Thanks,
Neil

**Comment by adaamcollins** [comment]
The best thing to do is add the `data-aos` tags to a parent or child div that has no transforms on it.

**Comment by michalsnik** [comment]
Yeah, @adaamcollins solution is the way to go. Alternatively you can add your own custom animation that will respect your initial transform. Please take a look at codepen example with custom animations in readme for more informations :)

**Comment by JoaoVitorEsposte** [comment]
This solution really works! I was having the same issue, thanks a lot for that!
