### ISSUE TITLE
[Question] AOS + animate.css

### ISSUE THREAD

**Issue by Drewkan** [michalsnik/aos#295]

**Comment by missmatsuko** [comment]
What's the question?

**Comment by Drewkan** [comment]
Sorry, i don't know what happened.

The question is if i can make AOS work easely with Animate.css somehow

**Comment by a-mojica** [comment]
[ Duplicate of #7 ]
Hey @Drewkan, regarding your question, please see issue #7.

**Comment by michalsnik** [comment]
Closing in favor of #7 
I just published proposition for the API that would allow to use any animation library with AOS :)
