### ISSUE TITLE
Link not working with aos code on the div

### ISSUE THREAD

**Issue by jeroenrotty** [michalsnik/aos#296]
The issue didn't happen before, I believe this must be a Chrome 65 thingy.

When my page is loading the links work, not when the animation is done.

![image 2018-03-08 at 9 49 30 am](https://user-images.githubusercontent.com/7323966/37141932-e8df4f98-22b6-11e8-8e7f-d0b44f820368.png)

Any workaround? It just works in Firefox ...

**Comment by Hambern** [comment]
+1

**Comment by michalsnik** [comment]
Hey @jeroenrotty. Please try `2.3.0` and if this problem still happens feel free to reopen this issue and we'll try to figure it out :)
