### ISSUE TITLE
Restart animation on button click?

### ISSUE THREAD

**Issue by akshay575** [michalsnik/aos#297]
Hi,
Can I restart the animation on a div or some other element on a button click? I tried to call the method AOS.refresh() and AOS.refreshHard() but it didn't work. 
Any help is much appreciated.

**Comment by michalsnik** [comment]
Hi @akshay575 Unfortunately you can. This is an `on scroll` animation library and it's not possible to fire animations again without some not recommended hack, like removing and adding again `aos-animate` class...

**Comment by HironTez** [comment]
You can remove the "aos-animate" class from your object. If it's high enough, the animation will restart.
