### ISSUE TITLE
DOMNodeRemoved event deprecated

### ISSUE THREAD

**Issue by maztch** [michalsnik/aos#300]
aos uses DOMNodeRemoved event listener and it's deprecated. Is there any future upgrade to mutation events? (https://developers.google.com/web/tools/lighthouse/audits/mutation-events)

**Comment by LebCit** [comment]
Hello,

In **aos.js** search for the following :
`DOMNodeRemoved`
and change it to :
`childList`

Hope this helps 😃
SYA ✋

**Comment by michalsnik** [comment]
Hey, this has already been updated. Please take a look at version `2.3.0` :)
