### ISSUE TITLE
Chaining animations in certain order- is it possible?

### ISSUE THREAD

**Issue by dlewand691** [michalsnik/aos#301]
Wondering if it's possible to chain animations together in a specific order? I'm trying to animate 3 stacked divs in an "inside out" approach:

#2: Top div: fade-up 2nd
#1: Middle Div: flip-up 1st
#3: Bottom div: fade-down 3rd

Thanks!

**Comment by michalsnik** [comment]
Hey, you can use `data-aos-offset` for that, e.g.:
```html
<div data-aos="fade-up" data-aos-offset="200">1<div>
<div data-aos="flip-up" data-aos-offset="100">2<div>
<div data-aos="fade-down" data-aos-offset="300">3<div>
```
If they are on the same horizontal position, they will animate sequentially regarding their offset :)
Other sequences are not supported and would probably require some dirty hacks.
