### ISSUE TITLE
How do you set anchor-placement globally?

### ISSUE THREAD

**Issue by Mikewalker24** [michalsnik/aos#305]
Dashes aren't valid in object properties. I don't see this documented anywhere.

`AOS.init({
      anchor-placement: 'top-top',
    });`

**Comment by michalsnik** [comment]
Hey @Mikewalker24 Indeed it's not supported as global setting yet. I'll add it in the next version (3.0).

**Comment by RanmeetSingh774** [comment]
plz tell me that how to target a particular CSS selector for animation settings.

**Comment by michalsnik** [comment]
What do you mean @RanmeetSingh774 ? You can use `data-aos-*` attributes on any DOM element to override global settings.

**Comment by RanmeetSingh774** [comment]
I want to modify the animation setting  of particular selector plz tell me
how i can .. i can only able to modify the animation setting of all page.

**Comment by michalsnik** [comment]
If overriding AOS setting on specific DOM node by using data attributes is not enough than I'm sorry, but there are no other built-in option to support it. You could however use plan JS to achieve it programatically:
```js
const yourElement = document.querySelector('.your-element');
yourElement.dataset.aos = 'fade-up';
yourElement.dataset.aosDuration = 600;
```
This way you get to choose the selector however you please @RanmeetSingh774

**Comment by michalsnik** [comment]
Global `anchorPlacement` setting has been added on `next` branch

**Comment by michalsnik** [comment]
I'm closing this issue now. You can try new setting by following readme and installing `aos@next`.
