### ISSUE TITLE
AOS with React 

### ISSUE THREAD

**Issue by YongPilMoon** [michalsnik/aos#307]
Hi there. I am using aos with create-react-app. It's perfectly work in my dev server. But when i run it after deploy in s3 it doesn't work in spacial case.  In nomal case is okay but when i refresh the browser on the page the animated component included the component doesn't show. Even after i scroll the page still it  dosen't show. Do you know any reason?? Thanks.

My aos setting is like this.
```javascript

componentDidMount() {
        AOS.init();
}

class SalesToolSecFourth extends Component {
    render() {     
        return (
            <section data-aos="fade" className="sales-section-fourth row">
                <div className="sales-section-fourth__content">
                    <div className="sales-section-fourth__title">
                     ....
                </div>
            </section>
        );
    }
}
```

**Comment by Khadosh** [comment]
try using AOS.refresh on

  componentWillReceiveProps() {
    AOS.refresh();
  }

**Comment by michalsnik** [comment]
Hey @YongPilMoon 

You should probably refresh AOS once everything is set. During initialization AOS calculates positions of elements and then only compare those with scroll distance on scroll. So when those positions have changed after initialization you'll need to refresh AOS manually.

If you'll still have problems with it, feel free to reopen this iussue.
