### ISSUE TITLE
Elements not showing up on Chrome.

### ISSUE THREAD

**Issue by Panoplos** [michalsnik/aos#309]
Love this library, but it mysteriously is not working correctly, as elements are getting animated after they are already scrolled past.

You can see here the problem: https://credify.one

Any insight on how to fix this issue, as we will have to use something else if not...

**Comment by Panoplos** [comment]
Note that it looks like this is conflicting with Slick, per the referenced issue.

**Comment by Panoplos** [comment]
Note that I was able to get this to finally work by calling `AOS.refresh()` after all of my other JS code.

**Comment by michalsnik** [comment]
Hey @Panoplos I'm glad you solved it. You can also add:
```
window.addEventListener('load', AOS.refresh);
```
Or use `startEvent`:
```
AOS.init({
  startEvent: 'load',
});
```
