### ISSUE TITLE
AOS works on desktop view, but does not work on mobile view

### ISSUE THREAD

**Issue by luminawastaken** [michalsnik/aos#310]
Hello, I been experiencing this issue and I do not know what is wrong:

I load the web site and the animations works, but if I change it to mobile view they work once, but if refresh they don't work.

I have this tags on my html document, on the head I have:

`<link href="//cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">`

and on the bottom with all the scripts:

`<script type="text/javascript" src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>`

the next line after I have:

`<script>
      AOS.init();
</script>` 

Even if I try to access the site from my phone, the animations do not show.
I tried using a AOS.refresh(); but that doesn't work. Also I noticed that all my html tags 'data-aos' disappear on the mobile view.

website: [http://www.duncantransportation.com](http://www.duncantransportation.com)

**Comment by sksarath** [comment]
I have gone through your website and found that you are disabling the animation on mobile. remove this "AOS.init({ disable: 'mobile' });" in bs-animation.js

**Comment by luminawastaken** [comment]
Ohhh such a dork! I didn't even notice this js file being pulled.

Thank you! works now!

**Comment by manogaranesteve** [comment]
It's work !
