### ISSUE TITLE
Animation Complete

### ISSUE THREAD

**Issue by mohsinnasim3** [michalsnik/aos#314]
Hi, I am not sure do you have any event on animation complete, cause i am working on it and i need to trigger my custom function on animation complete, can you help me out with this issue?

**Comment by michalsnik** [comment]
Hey @mohsinnasim3 This will be possible in v3, that is coming soon :)

**Comment by michalsnik** [comment]
You can track progress here: https://github.com/michalsnik/aos/issues/17
