### ISSUE TITLE
Offset increases with every instance

### ISSUE THREAD

**Issue by ashhitch** [michalsnik/aos#318]
I am having an issue where I have around 5 -6 bands of content on a page and as you scroll down the images fade up with AOS, however,  with each image it loads in later each time. 
If I add enough bands of content it will stop loading the later ones altogther. 

I have tried setting the offset to 0 globally

`AOS.init({
      offset: 0
    });`

**Comment by michalsnik** [comment]
Hey @ashhitch 

It beasue of AOS being initialized too early. You can fix it by either adding:
```
window.addEventListener('load', AOS.refresh);
```

Or by using `startEvent`:
```
AOS.init({
  startEvent: 'load',
});
```
