### ISSUE TITLE
Animation does not work when `data-aos-once` is true

### ISSUE THREAD

**Issue by vovagusarov** [michalsnik/aos#319]
Hi, animations do not work with `data-aos-once="true"` or when 
```
AOS.init({
    aos-once: true;
});
```
All works fine with this option either `false` of without it at all.
Using the latest version of the library.
Thanks!

**Comment by LebCit** [comment]
Hello,

It should be : 
```
AOS.init({
    once: true,
});
```
Note that if you want to add more settings, each setting **must be followed by a comma** `,`
**not** a semicolon `;` for example the global settings : 
```
AOS.init({
    offset: 200,
    duration: 600,
    easing: 'ease-in-sine',
    delay: 100,
});
```
Hope this helps 😃 
SYA ✋

**Comment by vovagusarov** [comment]
Hi @LebCit, thank you for your response.
```
AOS.init({
    once: true
});
```
Does not work for me too. The script just does not work when it is enabled.
All other options seem to work.
No errors in console.

**Comment by megant** [comment]
One of my elements does not do any animation when once is true, others do.

**Comment by sastava007** [comment]
I want my element to animate each time I scroll so I made once:false but still it's not working.
Can someone please help me with this?

**Comment by nadeem-khan** [comment]
This is still happening. The element in which you add data-aos-once="true" does not animate, rest work fine:

`<div className="col-lg-6 col-sm-12 aos-init aos-animate" data-aos-once="true" data-aos="fade-left" data-aos-offset="200" data-aos-easing="ease-in-sine">`

There seems to be a bug related to this parameter.

**Comment by Abhinav-Agarwal021** [comment]
Hello,
It is working fine when using

`import AOS from 'aos'
import 'aos/dist/aos.css';

useEffect(() => {
        AOS.init({
            duration: 2000,
            once: true
        });
    }, []);`

**Comment by Abhinav-Agarwal021** [comment]
>Hello,
>It is working fine when using
> 
> ```
>import AOS from 'aos'
>import 'aos/dist/aos.css';
>
>useEffect(() => {
>AOS.init({
>duration: 2000,
>once: true
>});
>}, []);
> ```
>
> Thanks!

**Comment by engmmagdy** [comment]
**This is work for me :**
 
Update the AOS CSS and JS version and try to remove "aos-animate" class from the element and add this 

```
  AOS.init({
       duration: 800,
       once: true
   }); 
```
