### ISSUE TITLE
Doesn't work with Edge or latest IEs

### ISSUE THREAD

**Issue by lmartins** [michalsnik/aos#32]
I was hoping this would work with the latest versions of Edge and Internet Explorer 11 but that doesn't seem to be the case.

Always returns an error `Object doesn't support property or method 'includes'` as seen here:
https://www.dropbox.com/s/rg8xrhbb7dt72o2/Screenshot%202016-06-28%2016.37.03.png?dl=0

**Comment by michalsnik** [comment]
Hi @lmartins, good catch! Thanks

Check out newest version `2.0.2` - it should work fine on Edge.

However I'm working on IE11 now as there is something wrong anyway, I'll let you know when it's fixed.

**Comment by michalsnik** [comment]
Good news @lmartins,
I did some work and now AOS works on IE >= 10.

Previous browsers doesn't have transition support so I'm gracefully disabling AOS, so it doesn't affect not supported browsers anymore :)

Check out newest AOS `2.0.4` and have a good evening.

Thanks for your contribution!

**Comment by lmartins** [comment]
Thanks @michalsnik I just confirmed it's running fine IE11+.
