### ISSUE TITLE
Mutation issue on firefox

### ISSUE THREAD

**Issue by djalma81** [michalsnik/aos#320]
Hello,

I'm receiving 3 erros on mozilla firefox(last version)

1. https://developer.mozilla.org/en-US/docs/Tools/Debugger/Source_map_errors
2. https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects
3. Mutation isn't approved. Use MutationObserver.

It is possible to solve theses issues ?

Thanks in advance.

BR

**Comment by LebCit** [comment]
Hello,

1. You can grab the latest `.map` files [here](https://github.com/michalsnik/aos/commit/2419bb5c19c5d7784a4bae883df599e1fca4ff83)
2. I'm not having this issue using the last firefox version
3. In `aos.js` search for the following : 
`DOMNodeRemoved`
and change it to : 
`childList`

Hope this helps 😃 
SYA ✋

**Comment by michalsnik** [comment]
Hey @djalma81 Please check 2.3.0. We've updated the MutationObserver and removed source maps there.
