### ISSUE TITLE
Give different animation for desktop and mobile. 

### ISSUE THREAD

**Issue by josuevalrob** [michalsnik/aos#322]
Hi. 

In the desktop version, I have 4 elements, 2 in one row and 2 in the other one. 
On the mobile, I have one for a row, so 4 rows. 

I want to give one animation for the mobile version and another one for the desktop version?. How can I do that?

**Comment by fvrod** [comment]
Hi Josue,

From the top of my head and without trying you can use jQuery to detect the viewport width and remove a class and add another or probably you can do it with media queries by overriding the default css animations.

One of these options might work, if not the two..

Cheers

**Comment by Jonathlee** [comment]
use different animation on different breakpoints in CSS.

**Comment by michalsnik** [comment]
Hey @josuevalrob. As @Jonathlee said you can create custom animation and use breakpoints there. Example code here https://github.com/michalsnik/aos/issues/315
Please also take a look at codepen with custom animations linked in readme.

**Comment by josuevalrob** [comment]
thanks!
