### ISSUE TITLE
disable: 'mobile' not working

### ISSUE THREAD

**Issue by kaspar-allenbach** [michalsnik/aos#324]
If I write `disable: 'mobile'` as an option in AOS then the website just shows nothing on mobile devices. Every animated object is simply in its initial state befor animating.

What's the idea behind this?

**Comment by michalsnik** [comment]
Hey @kaspar-allenbach Can you please provide more information. What device are you using and how do you initialize AOS?

**Comment by kaspar-allenbach** [comment]
Hmm. It's quite hard to provide more infos. I build the whole thing with webpack. Ant 99% of every issue is related to webpack. Unfortunately I had to deploy and removed AOS altogether. But I'll try again on the next build
