### ISSUE TITLE
Looking for DOM changes is broken in 2.3.0

### ISSUE THREAD

**Issue by Fuchsiii** [michalsnik/aos#328]
In 2.3.0 AOS does not animate elements anymore that came into the DOM via AJAX, i had to revert to 2.2.0 which works fine.

**Comment by michalsnik** [comment]
Hey, thanks for posting this issue. 2.3.0 was released recently and there were some changes in Mutation Observer that might've caused it. Can you please provide more information? What browser are you using, also can you share the snippet of your code that you experience the issue with?

**Comment by DanielQuero** [comment]
I have the same bug, in 2.3.0  the element dissapears as it should but doesn't appear back, tried on Chrome and Firefox in a vue project. Works perfect on 2.2.0

**Comment by Fuchsiii** [comment]
i just checked browsers i have on hand and it happens for me in Chrome, Firefox, Opera, Safari, Edge, IE11 (all latest). 

My code for AOS is quite simple:
```javascript
AOS.init({
  duration: 1200,
  once: true
});
```

And my AJAX code is basically getting html via a XMLHttpRequest and loads it in to the DOM with ether jQuery .replaceWith() or .html() depending on the case.

I tried with once: false but that does nothing for this problem.

**Comment by michalsnik** [comment]
I'm trying to reproduce this issue but with no luck. Perhaps you @Fuchsiii could create codepen?
I have created this one: https://codepen.io/michalsnik/pen/RJyGbe
And it seems to be working fine on 2.3.0 🤔

**Comment by michalsnik** [comment]
Any luck @Fuchsiii ?

**Comment by michalsnik** [comment]
Alright, I think nailed down the problem. Will release an update in `3.0.0-beta.4` in the next hour, as well as in `2.3.3` :) New mutation observer does not return changed nodes in a flat NodeList, instead it contains root nodes and the rest is nested, so I have to do a recursive search for any AOS element inside the payload and then trigger refresh. Sorry for the confusion guys, and thanks for understanding!

**Comment by michalsnik** [comment]
Guys, please try `aos@2.3.3` or `aos@next`. I fixed issue with MutationObserver in both of these versions :) If you'll still have some problems, please reopen this issue and let me know! :)

**Comment by Fuchsiii** [comment]
@michalsnik :/ sry i was on sick leave the last two weeks... but im happy to announce that 2.3.3 works perfectly fine again. Thanks for the great work!
