### ISSUE TITLE
The problem with using Aos and Remodal

### ISSUE THREAD

**Issue by Ivan4537** [michalsnik/aos#330]
Hello. I will describe my problem.
I have a "Callback" button on my site, when I click on it, using the Remodal plugin, a modal window with fields for filling is called. I connected aos.js to <body> so that when loading the site, there would always be a smooth appearance animation. The fact is that when you connect aos.js and call the modal window, the page of the site is scrolled exactly (or roughly) to the middle. Without an aos.js connection, the modal window, when called, does not scroll down the page, but starts exactly at the position of the page on which it was called. This problem becomes even worse if the page of the site is very short - the modal window is called somewhere at the bottom of the page and half of the modal window is chopped off. In the mobile version of the site the same problem - when you call the modal window, the page scrolls down. I tried to remove the call button and the "body" of the modal window for the <body> tag - this does not help.
What else can I give you to help you solve this problem? I will give you some screenshots.
![screenshot 1](https://user-images.githubusercontent.com/15707064/40531419-0f7f54e6-6005-11e8-86c7-fbefb2c2a5f4.png)
![screenshot 2](https://user-images.githubusercontent.com/15707064/40531420-0fa68f0c-6005-11e8-81d1-ff44c7f38751.png)
![screenshot 3](https://user-images.githubusercontent.com/15707064/40531421-0fcf360a-6005-11e8-9640-19d679a538cd.png)
![screenshot 4](https://user-images.githubusercontent.com/15707064/40531424-0ff3d2e4-6005-11e8-8535-e3bf3b34b229.png)
![screenshot](https://user-images.githubusercontent.com/15707064/40531425-1025edd8-6005-11e8-9e83-66090d480a9c.png)

**Comment by michalsnik** [comment]
Have you tried adding `data-aos` attribute on other element? Perhaps styles that are initially being applied to this element causes remodal script to miscalculate something?
