### ISSUE TITLE
data-aos="fade-right" not working in Safari

### ISSUE THREAD

**Issue by unyoyomic** [michalsnik/aos#334]
Hello, I have 4 images in a row and i want them to fade right. I've put a data-aos-delay="150" on the second, data-aos-delay="300" on the third and data-aos-delay="450" to the fourth. They work in Chrome, but not in Safari. In Safari the last image is not showing up in an animation, it just appears. Could you please take a look?

**Comment by ayesha582** [comment]
same issue here, AOS not working in safari.
