### ISSUE TITLE
Does AOS override animations in :hover selector?

### ISSUE THREAD

**Issue by halverson** [michalsnik/aos#335]
Hi everyone!

I have used AOS to animate portfolio items into view as the user scrolls down on my site. But since I added it, my hover effects on the same portfolio items no longer trigger when the mouse moves over them.

Apologies if this is a known issue, I couldn't find anyone talking about it (at least not in a way that I understand).

Here is a Codepen showing the issue: https://codepen.io/halverson13/pen/ERaLxW

If you disable AOS the hover effect starts working again.

Thanks for any assistance!

**Comment by bubbaspaarx** [comment]
Hi there. I second these issues. I have a button with a background transition that doesn't work when using the aos animations. but as soon as I remove the AOS animations it works fine

**Comment by michalsnik** [comment]
Hey, it's because you try to transition `transform` which is already being used by AOS animation. If you want to change properties that AOS uses to animate elements on scroll, you can either use more specific selectors, or preferably wrap the element with another tag, and use AOS on it :)

**Comment by YorickLane** [comment]
> Hey, it's because you try to transition `transform` which is already being used by AOS animation. If you want to change properties that AOS uses to animate elements on scroll, you can either use more specific selectors, or preferably wrap the element with another tag, and use AOS on it :)

great! it work for me . thank you very much michalsnik

**Comment by karthick-potter** [comment]
use !important. It'll fix the issue

**Comment by Pradeep2898** [comment]
> use !important. It'll fix the issue

using !important disable AOS.

**Comment by salby966** [comment]
> Hey, it's because you try to transition `transform` which is already being used by AOS animation. If you want to change properties that AOS uses to animate elements on scroll, you can either use more specific selectors, or preferably wrap the element with another tag, and use AOS on it :)

that's work for me

**Comment by eduinfonet** [comment]
You can use id instead of using class as a selector. This same problem has occurred to me. But when I have used id then the problem has been solved.

**Comment by codesterLalit** [comment]
Well, I am using aos effect in image with absolute position. So, wrapping around another element, using id or using !important are not working for me.

**Comment by JudyTrillz** [comment]
> use !important. It'll fix the issue

If you use !important, Your own transition will take the same time as the animation duration, which will be longer than you want..
