### ISSUE TITLE
How to change how much object translates?

### ISSUE THREAD

**Issue by fordben90** [michalsnik/aos#344]
How do I change how much y translation is happening on fade-up? All other variables seem to be defined, but I wasn't seeing anything about the translating.

**Comment by petebarr** [comment]
+1

**Comment by baffleinc** [comment]
+1

**Comment by baffleinc** [comment]
If you are using SCSS, before you import aos's scss you can define a variable like so: `$aos-distance: 25px;`

This would reduce the distance of all animations to 25px.

**Comment by michalsnik** [comment]
Hey @fordben90, just like @baffleinc said, there is `$aos-distance` scss variable, that you can override if you import directly `.scss` file:
```scss
$aos-distance: 40px;
@import 'aos/src/sass/aos.scss';
```

**Comment by marzique** [comment]
I've needed to change distance for fade-down animations just for particular item.

so I just added this css:

```
.your-item-selector[data-aos=fade-down] { // or another animation type you have
  -webkit-transform: translate3d(0,-30px,0); // or another value you need
  transform: translate3d(0,-30px,0); // or another value you need
}
```

**Comment by NoailletasJordan** [comment]
thanks @marzique. was exactly what I was looking for.
