### ISSUE TITLE
once: true, tried everything in the comments, still not working

### ISSUE THREAD

**Issue by danmcnaney** [michalsnik/aos#347]
Trying to get once: true to work unsuccessfully. I've moved the init script to make sure it loads later, added jquery script (and plain js version) to refresh aos, tried adding data-aos-once="true" to individual elements. None of it works for me, the animations are just disabled (content is visible).

**Comment by michalsnik** [comment]
Have you tried refreshing AOS on window load?
```
window.addEventListener('load', AOS.refresh);
```
If this doesn't help, can you please provide and example codepen that reproduces your issue?

**Comment by danmcnaney** [comment]
Discovered the issue, I was adding aos-init and aos-animate classes as well, based on I guess misreading the documentation (which looks to be recently updated). All set here.

**Comment by ArunSharmaLearning** [comment]
thanks @michalsnik
