### ISSUE TITLE
After I added the CDN links my text disappeared 

### ISSUE THREAD

**Issue by sruli1** [michalsnik/aos#348]
I wanted to incorporate the fade in property to a website I'm working on so I added the fade in div and wrote some text. Next I added the CDN links and the text disappeared from my website. Is there an additional step I missed? I'm new to coding so I apologize if this is a stupid question.

**Comment by danmcnaney** [comment]
Did you add the AOS Init script?

`  <script>
    AOS.init();
  </script>`

**Comment by sruli1** [comment]
No, how do I do that?

**Comment by danmcnaney** [comment]
You just copy/paste that text into the bottom of your page. There are other settings you can put in between the <script> tags, check out the documentation, but that's the main thing to initialize it.

**Comment by michalsnik** [comment]
I think that concludes this issue, placing script before closing `body` tag should solve it. Please read the Readme @sruli1
