### ISSUE TITLE
Fade-out

### ISSUE THREAD

**Issue by timotheegoguely** [michalsnik/aos#35]
As you have _zoom-in_ and _zoom-out_, I think adding _fade-out_ in the fade predefined animations could be useful in some cases.

**Comment by michalsnik** [comment]
Hi @timotheegoguely, thanks for reaching out.

Please notice that both of animations `zoom-in` and `zoom-out` works the way that they start with `opacity: 0` and ends with `opacity: 1`, the only difference is that one of them starts with different scale. They are both about showing an element.

The animation you're proposing will hide an element, which is not what I want to do with this library.

**Comment by janstieler** [comment]
Hi,
I'm actually have yet also the situation that I need a fadeout on scroll.
> The animation you're proposing will hide an element, which is not what I want to do with this library.
What will you not with your library? That Elements will be hidden? Sorry really strange position.
I like your library but because of this, I have to use another one or I have to write my own function yet.

**Comment by JonS7** [comment]
I found you can actually do this by writing you own transition for when the .aos-animate class is applied, and leaving data-aos empty...
`<div class="fade-out" data-aos></div>`
`.fade-out.aos-animate {opacity: 0}`

**Comment by C1V1L14N** [comment]
Hi, your library is very nice and a handy tool for sure. To be honest, like the people above, I was very surprised there wasn't a fade out option. It makes sense to me that everything you can do should be able to be done in reverse.

**Comment by voltmer1** [comment]
> Hi, your library is very nice and a handy tool for sure. To be honest, like the people above, I was very surprised there wasn't a fade out option. It makes sense to me that everything you can do should be able to be done in reverse.

I TOTALY agree! The option to fade-out elements would be very useful.

**Comment by welbinator** [comment]
> I found you can actually do this by writing you own transition for when the .aos-animate class is applied, and leaving data-aos empty... `<div class="fade-out" data-aos></div>` `.fade-out.aos-animate {opacity: 0}`

I dunno perhaps I misunderstand but that's not working for me, because for whatever reason the .aos-animate class is being added right away, before I even scroll, so as soon as the page loads the element has opacity of 0. I was under the impression this would cause it to fade out when you start scrolling, basically the opposite of the standard AOS fade-in where it fades in when you scroll

**Comment by devSahinur** [comment]
@JonS7 

Thank you
