### ISSUE TITLE
AOS not working when div on top of screen

### ISSUE THREAD

**Issue by mariodermez** [michalsnik/aos#353]
Like I mentioned in a previous issue the code only works if you use anchor placements. The other thing is that  when a div is almost at the top of the screen it should make an initial animation without having to scroll up or down. This is what happens on your website. In my case this doesn't happen. If I add an anchor placement (as it doesn't work other way) the animation will never run until I scroll up or down. So why this is working on your website and not on mine?

**Comment by michalsnik** [comment]
Let's continue discussion in one issue
