### ISSUE TITLE
AOS on page bottom (footer)

### ISSUE THREAD

**Issue by Crunky** [michalsnik/aos#354]
AOS works fine until in the website footer. Most the content does not appear, if you manipulate the browser size e.g. it appears afterwards.

Any Ideas what cause the issue?
Thanks

**Comment by michalsnik** [comment]
The default offset is probably higher than the footer itself. Hence the problem. You might want to add `data-aos-offset="0"` on footer. Let me know if this helps @Crunky :)

**Comment by michalsnik** [comment]
Feel free to reopen this issue, if above solution won't work @Crunky ;)

**Comment by Crunky** [comment]
Thanks. looks like this is realy in relation with this issue. In some cases it fixed the problem but in some it does not. I can reproduce it if i add some paddings to to footer element it work fine :) In my case i have to add paddings about 100px at top and bottom, a bit too much for an footer ;)

**Comment by scottshefler** [comment]
I'm also having this issue on sites near the bottom of the page and footer. I have the offset set to 0 and the sections and footer are definitely in view. Sometimes when it doesn't work the elements are almost at the top of the screen so not sure it's an offset issue. Thanks for your help and great animation library!

**Comment by tipsclick** [comment]
i am facing issue. if i zoom only then it works. i used offset=0 but no luck. i tried placement=bottom-bottom but no luck.  still no idea why it not getting triggered.
