### ISSUE TITLE
Conflict with parallax header

### ISSUE THREAD

**Issue by demo38** [michalsnik/aos#359]
I have a site that I'm working on with a parallax style header that uses the following jQuery (window).scroll(function() for positioning, but on that page, AOS doesn't calculate the timing / positioning for the fade ins correctly. Instead of AOS fading in elements towards the bottom of the screen as the user scrolls down (like normal), they are fading in towards the middle or top of the screen (if at all) for elements below the header.

`$(window).scroll(function(){
            $(".row.parallax-header").css("margin-top", 0 - $(window).scrollTop() / 2);
            $(".page-title").css("margin-top", 190 - $(window).scrollTop() / 1.25);
        });`

Any thoughts on being able to separate the two scripts so they calculate independently?

**Comment by michalsnik** [comment]
Hey @demo38 You should be able to separate those two. Make sure that styles of your parallax-header don't change positions of elements below and you should be safe. Put the header inside other container which height won't change and the problem should disappear.

**Comment by demo38** [comment]
Thanks @michalsnik I do have a set height on the container for the header so that nothing changes below. I'm using imgLiquid on the header as well, though disabling that doesn't make a difference with the AOS timing, so there's probably something in my CSS.

Here's what I'm seeing on the front-end for a visual (showing the jQuery enabled / disabled to compare): https://screencast.com/t/g6gfREH3U

Using Foundation / and ACF in WordPress, along with absolute positioning transform for centering the varied lengths on page titles.

I essentially have:
`
	    	<div class="row fullWidth parallax-header">
				<div class="page-title">
					<h1><?php the_title(); ?></h1>
				</div>
			    <div class="imgLiquidFill imgLiquid small-12 columns bg">
			        <?php $header_banner = get_field( 'header_banner' ); ?>
					<?php if ( $header_banner ) { ?>
						<img src="<?php echo $header_banner['url']; ?>" alt="<?php echo $header_banner['alt']; ?>" />
					<?php } ?>
			    </div>
			</div>`

With the SCSS:

`.row.parallax-header {
  height: 526px;
  position: relative;
  text-align: center;
  .bg {
    position: fixed;
    z-index: -1;
  }
  .page-title {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 100%;
    h1 {
      color:#fff;
      font-family: $league;
      font-size: 90px;
      font-weight: normal;
      text-align: center;
      text-transform: uppercase;
    }
    img {
      display: block;
      margin: 0 auto;
      max-width: 620px;
    }
  }
  .imgLiquid {
    display: block; 
    width: 100%; 
    height: 526px; 
    overflow: hidden;
  }
}`

And, jQuery of:
`AOS.init();`
`$(window).scroll(function(){
            $(".row.parallax-header").css("margin-top", 0 - $(window).scrollTop() / 2);
            $(".page-title").css("margin-top", 0 - $(window).scrollTop() / 1.25);
        });`

**Comment by michalsnik** [comment]
Alright @demo38 So what's causing the problem I think, is that you manipulate the `margin-top` property of `.row.parallax-header` and it causes elements below to have different offset from top of the page than initially while AOS was initializing. You might wan't to change your script to not cause it. Also `margins` are properties not to be animated, as they cause calculations of layout to be performed by CPU, and not GPU - resulting in poor overall performance and junky scroll.
You might try: https://dixonandmoe.com/rellax/
It uses transforms to achieve nice and performant parallax effect and would probably solve your problem.

Feel free to reopen this issue, once you'll confirm that AOS elements have the same offset position from top after you scroll down a bit as they initially had and you'll still experience the same problem (which is unlikely :))

**Comment by demo38** [comment]
Thanks @michalsnik I really appreciate your help - retooling a bit to animate top instead of margin-top worked perfectly.
