### ISSUE TITLE
Not responsive in bootstrap

### ISSUE THREAD

**Issue by Gurdeep001** [michalsnik/aos#36]

**Comment by michalsnik** [comment]
Hi @Gurdeep001 
Could you please provide more informations, and perhaps some example, so I can verify it quickly? :)

**Comment by Randore** [comment]
@Gurdeep001 I guess you are using bootstrap classes, so I suggest you not to include bootstrap class for the animated element.
Example:
`<div class="col-md-4">`
        `<div class="row">`
                    `<div class="animated-elem" data-xxx> </div>`
         `</div>`
     `</div>`

**Comment by michalsnik** [comment]
It might be the case @Randore.

@Gurdeep001  I'm closing this for now, if you'll prepare demo presenting the issue feel free to reopen this topic.
