### ISSUE TITLE
issue using CSS to control aos delay in conjunction with y-axis animations and resized elements

### ISSUE THREAD

**Issue by stacybirdy** [michalsnik/aos#365]
I'm using [http://brm.io/jquery-match-height/](http://brm.io/jquery-match-height/) to resize elements to match the height of their neighbors. This plays nice with AOS in some scenarios, but not if you use CSS to determine the delay **in combination with** a **vertical** movement effect (ie fade-up, slide-up.... other animations like fade, fade-left, etc _do_ work)

Use case: on large screen there are rows of 4 elements that need to animate in one after the other from left to right, lets say with delays of 100, 200, 300 and 400 respectively. On slightly smaller screens it switches to 3 per row, and on mobile only 2 per row. Since each item's delay will be screen-size-dependant, I have to set it in CSS with transition-delay VS inline with the data-aos-delay attribute.

If you resize the window once the animation has completed, the heights all adjust and start showing correctly. I tried a few timing fixes I found in other forums, such as implementations of things such as window.addEventListener('load', AOS.refresh); but didn't have any luck.

Is there a way to achieve that output inline without resorting to CSS? If not, any thoughts on how to resolve this little css/vertical/resize bug?

simplified demo: [https://codepen.io/stacybirdy/pen/PBbwgy](https://codepen.io/stacybirdy/pen/PBbwgy)

**Comment by michalsnik** [comment]
Hey! Perhaps you could use CSS grid or flexbox instead of jquery-match-height?

**Comment by stacybirdy** [comment]
oh trust me i'd LOVE to -- but have to support down to ie9 :/

**Comment by stacybirdy** [comment]
In case anyone else is working within these restraints -- I found that simply changing the startEvent from 'DOMContentLoaded' to 'load' solves it, I guess because it allows everything to calculate/load in before initializing. Woo!
