### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mirror' of undefined

### ISSUE THREAD

**Issue by RostislavBerezhnoy** [michalsnik/aos#366]
Hello,

I'm having the following problem. Errors sometimes appear in the browser console: "Uncaught TypeError: Cannot read property 'mirror' of undefined". The webapp crashes. The more I scroll, the more I have the same errors. Can you please tell me how to fix it?

I'm using AOS v.3.0.0-beta4 + react v.16.4.1.

The last stable AOS v.2.3.2 isn't working correctly for me. When I'm using AOS.init({disable: true}) and mapping an array, asynchronous elements with "data-aos" don't appear on the view, but they do in AOS v.3.0.0-beta4. That's why I'm using it.

![1](https://user-images.githubusercontent.com/9082153/42961058-4cd83ed6-8b96-11e8-9c1a-6dec291c6021.JPG)

**Comment by michalsnik** [comment]
Hey @RostislavBerezhnoy ! Thanks for posting this issue. Could you perhaps prepare an example codesandbox that reproduces this issue? I couldn't reproduce it. Also what system and browser version are you using?

**Comment by RostislavBerezhnoy** [comment]
Here is my sandbox: https://codesandbox.io/s/3r9rylpv71

I haven’t managed to reproduce the error in the console, but I managed to reproduce the slowdown of animation that causes the crash. The problem doesn’t appear at once, but in a couple of minutes. I’ve made a video with this problem. You need to start watching at 2:30. The video: https://youtu.be/jPZEsZfna24

Here is my project where I have the same problem with animation and errors appear in the console.
The project: http://irkswimming.azurewebsites.net
The video of the error: https://youtu.be/1tgnwVXc3Fg

When I start the local project, the error in the console refers to aos.js like the screenshot in the first post.

I use Windows 10 and Google Chrome 67.0.3396.99

**Comment by RostislavBerezhnoy** [comment]
Hey,

I've managed to reproduce the error in the console https://codesandbox.io/s/74olr2yo36
The video: https://youtu.be/PqJNQk74Y9Y

**Comment by RostislavBerezhnoy** [comment]
Is there anyone alive out there?!

**Comment by michalsnik** [comment]
Alright @RostislavBerezhnoy I think I know what's going on.
You're initializing AOS on every page render, and it attaches event listeners each time, so after navigating the page for a while - you have a giant leak that causes the slowdown and tries to execute functions on elements that already disappeared from the page.
This case hasn't been figured out yet, but you don't acutally need to initialize AOS so many times. It should have been initialized only once on your page - in the root component and the problem would disappear.

**Comment by RostislavBerezhnoy** [comment]
@michalsnik So how can I display animations of a component on one page and reuse this component on another page, where animations are turned off?
