### ISSUE TITLE
AOS init must load close to last to work

### ISSUE THREAD

**Issue by simmonsr** [michalsnik/aos#367]
Anyone else finding that AOS.init() must be loaded close to last in priority of other JS?

If I load it toward the top here it will not work.

![screen shot 2018-07-20 at 12 35 57 pm](https://user-images.githubusercontent.com/5002814/43016767-7ec6db9a-8c19-11e8-961b-ed8e0a9585f2.jpg)

**Comment by michalsnik** [comment]
What version?

**Comment by zedentox** [comment]
Does your elements with `data-aos` are loaded by javascript ? Or are they in the source code already ?

**Comment by simmonsr** [comment]
3.0.0 beta v.4. Working it with Owl Carousel.

@zedentox data-aos elements are loaded via hardcoded HTML.

**Comment by simmonsr** [comment]
actually Owl elements are loaded via JS. Sorry :D

**Comment by simmonsr** [comment]
To some degree anyway...

**Comment by zedentox** [comment]
Elements with `data-aos` have to be in the page before calling `AOS.init()`, I think.

**Comment by simmonsr** [comment]
If I put it below of Owl JS scripts, works fine. So just need to keep it that way 👍
