### ISSUE TITLE
elements in carousel not animating onload ---  html:not(.no-js) detected 

### ISSUE THREAD

**Issue by robotchips** [michalsnik/aos#368]
I have aos installed (followed installation steps and attempted to mirror placement of js and css)
Carousel h2 and p tag should animate. The rest of the pages are loading correctly and animated however the I've noticed html:not(.no-js). Unsure why this is...  

I have: 
$(function() {
  AOS.init();
});
$(window).on('load', function() {
  AOS.refresh();
});
	
in my script file

## Specifications

  - AOS version: 
  - OS: macOS
  - Browser:Chrome

## Expected Behavior
SHould animate the h2 and p tag on load. 

## Steps to Reproduce the Problem
http://wfrh4hn.preview.optimasites.com/

1.
2.
3.

**Comment by michalsnik** [comment]
I opened the page and those elements are being properly animated @robotchips.
As for the `html:not(.no-js)` - it's there to disable AOS styles for bots that crawl the page so they index them properly. You usually add `no-js` class on HTML and have simple javascript code to remove this class. If the class is still there - it means that the javascript is disabled or wasn't executed, hence nothing will animate :)
