### ISSUE TITLE
AOS not firing in safari for SVG animation

### ISSUE THREAD

**Issue by ArunK22** [michalsnik/aos#369]
## Specifications
  - AOS version: 1
  - OS: MAC
  - Browser: Safari

## Expected Behavior
Fade-left and Fade-right animation should fire on page load

## Actual Behavior
It just fades in on page load. No left right animation is happening.

## Steps to Reproduce the Problem
Check this codepen link on SAFARI browser.
https://codepen.io/ArunK_UI/pen/mjwLdo

**Comment by michalsnik** [comment]
AOS doesn't support animating SVG elements and wasn't built with them in mind @ArunK22
