### ISSUE TITLE
Simple Fade-in effect ?

### ISSUE THREAD

**Issue by a-foutoyet** [michalsnik/aos#37]
Hi, first, thanks for this awesome lib, that's very cool.
I've searched for simple Fade-in (without move up/down/left/right) effect but I didn't find it.
Do you know if it's possible to add it ?

**Comment by michalsnik** [comment]
Hi @a-foutoyet , you're right. There's no `fade-in` animation, but if you set `data-aos="fade"` it should work :) Try this and let me know it worked for you.

In future release I'll add it specifically under `fade-in` name as well, it's a good catch. Thanks!

**Comment by a-foutoyet** [comment]
You're right ! I've tried "fade-in" that doesn't work but "fade" works like a charm. Thanks for your feedback !
ps : that init + function feature is dope !

**Comment by michalsnik** [comment]
Thanks @a-foutoyet , glad to hear that :)
