### ISSUE TITLE
Wrapped Link Bug

### ISSUE THREAD

**Issue by cmiolla** [michalsnik/aos#370]
## This is:

- Bug

## Specifications

  - AOS version: 3.0.0-betta.3
  - OS: MacOS 10.13.6
  - Browser: Safari  11.1.2 - Chrome Version 67.0.3396.99 - Firefox - 60.0.2

## Expected Behavior

 You should be able to use clink on a button wrapped inside an animation before or after the AOS animation triggers. 

## Actual Behavior

Links wrapped inside an AOS animation are un-clickable before the animation triggers.

## Steps to Reproduce the Problem

1.
2.
3.
HTML: 
<body>
<nav id="secondary-nav" data-aos="newColor" data-aos-anchor="#change-secondary-nav"   data-aos-mirror="true">
    <ul id="menu-secondary-menu" class="menu nav-menu">
      <li><a href="">Follow Us</a></li>
      <li><a href="">Call</a></li>
      <li><a href="">Apply Now</a></li>
    </ul>
</nav>

<section class="red">
   Bla bla bla
</section>
<section class="green">
   <div id="change-secondary-nav"></div>
   Bla bla bla
</section>
<section class="blue">
   Bla bla bla
</section>

</body>

_____________________________________________________________________

CSS: 
#secondary-nav {
  position: fixed;
  top: 40px; 
  right:40px;
  width: auto;
  display: inline-block;
  font-size: 1.25em;
  letter-spacing: .025em;
  z-index: 100;
  ul{
        list-style: none;
        text-transform: uppercase;
        text-align:left;
        width: auto;
        padding: 0;
        li {
          display: inline-block;
          list-style: none;
          margin:0 0 0 0;
          padding: 0;
          &:nth-child(1):after{
            content: " / ";
            margin:0 5px 0 5px;
          }
          &:nth-child(2):after{
            content: " / ";
            margin:0 5px 0 5px;
          }
          a {
            transition: ease-in-out;
            transition-delay: .5s;
            opacity: 1;
            &:hover{
              opacity: .5;
            }
          }
        } 
  }
}

[data-aos="newColor"] {
  color: #fff;
  transition: ease-in-out;
  a{
   color: #fff;
   transition: ease-in-out;
  }
  &.aos-animate {
    olor: #838383;
    a{
      olor: #838383;
      transition: ease-in-out;
     }
  }
}

section {
    width: 100%;
    height: 100vh;
    color: #fff;
}

.red{background: red;}
.green{background: green;}
.blue{background: blue;}

## Detailed Description

I have a set of fixed navigation links that change color when a user scrolls to a desigated trigger point.  
The links are un-clickable unit the AOS animation triggers. I'd like the links to be always be clickable. 

## Possible Solution

I think the bug is somewhere inside the data-aos="" tag

**Comment by michalsnik** [comment]
Hello @cmiolla Sorry for late reply!

Due to other concerns AOS disables pointer-events on all AOS elements until the animation.
You can override it by using:
```
pointer-events: auto;
```
