### ISSUE TITLE
aos@next missing scss files?

### ISSUE THREAD

**Issue by webdevnerdstuff** [michalsnik/aos#371]
## This is:

- Feature request
- Question

## Detailed Description
When running 
`npm install --save aos@next`
It does not include the src file that has the scss files in it. I would love to use the scss files like you can with the master branch version.

## Possible Solution
Include the src files into the npm package. Thank you.

**Comment by michalsnik** [comment]
Oh, it should be there! Thanks for catching it @webdevnerdstuff !

**Comment by michalsnik** [comment]
`v3.0.0-beta.5` has it included. Enjoy :)

**Comment by webdevnerdstuff** [comment]
@michalsnik Thanks for the update! I'll check it out next time I have a chance.
