### ISSUE TITLE
Add new sass variable

### ISSUE THREAD

**Issue by tonymihay** [michalsnik/aos#377]
Hi @michalsnik,

Could you pls replace the 'aos-animate' class in your sass files with a variable in order to have a possibility to override it.
At the moment the 'data-aos-delay' attribute is not working with the animate.css library and it can be fixed by changin the 'aos-animate' class on 'animated'.

**Comment by michalsnik** [comment]
Sorry @tonymihay But I'd rather not mix AOS's styles with custom ones that you get by integrating with other libraries. It might cause more confusion and problems in the end. You should rather handle delay yourself.
