### ISSUE TITLE
bad auto recalculation/resizing of objects

### ISSUE THREAD

**Issue by darogha** [michalsnik/aos#378]
## This is:

- Bug

## Specifications

  - AOS version:2.3.1
  - OS: Every OS
  - Browser:Chrome(maybe other browsers also react same to this bug, i haven't tested them yet)

## Expected Behavior
It should work normally as it works on windows(pc) when resizing the chrome(browser) window
## Actual Behavior
when the page is opened on mobile device, some of its parts maintain their styling as they are expected but top of the page(nav bar) behaves abnormally.

## Steps to Reproduce the Problem

1.goto https://darogha.gitlab.io/portfolio on mobile(phone) on chrome.
2. on page fully loaded, pinch in the screen to zoom out the screen. the page will zoom out.
3.scroll down slowly to the end of page and observe the behaviour and animations that nav bar will auto adjust it self to te window size and second nav will show up now as it should normally do
4.scroll up to the top slowly and observe behaviour of page that it will reach to it state when ti was loaded

## Detailed Description
animations go just the way they are supposed to be on PC even when the window is resized.
but when page is opened on mobile devices, it seems like AOS treats nav bar of page according to som other prespective and rest of page according to some other prespective. this makes the page look very unmanaged on mobile devices while it works perfectly on PC/Laptops
## Cause of Bug
I suspect this bug occurs due to refresh() or refreshHard() in aos.js

**Comment by michalsnik** [comment]
Please try `aos@next` and let me know if this problems still occurs @darogha I just tested this on my iphone and it looks fine 🤔

**Comment by djneill** [comment]
@michalsnik  I tried the aos@next and still get the same reaction. I have two pages both giving near identical effects. On mobile and tablet sometimes the nav bar is being pushed to the right, some devices are keeping it onscreen but you can still scroll left and right. The effects are laggy until you reach the lower half of the page when it falls back into its container. On desktop everything is top notch.
Tested on chrome & samsung browser, galaxy S8+, iPhone 8+, samsung galaxy tab, macbook.

http://dninstalls.com/

http://dninstalls.com/vidb/

Edit: I've also tried adding these classes from another issue, no resolution though.
CSS
.aos-init:not(.aos-animate):after {
position: fixed;
}
HTML
< div class="aos-init" data-aos="zoom-in-up" data-aos-duration="3000" >

**Comment by darogha** [comment]
@michalsnik i tried it as you suggested but problem presists. i've tried testing it on almost every phone in my approach and results are same. even i tried it on chrome's device toggler's devices
but results are same, don't know why your phone is treating it just the way it's meant to be
