### ISSUE TITLE
How to apply AOS on individual slides within a slideshow?

### ISSUE THREAD

**Issue by tamcai** [michalsnik/aos#379]
## This is:

- Question

## Specifications

  - AOS version: 2.0.0
  - OS: OS 10.13.6
  - Browser: Safari 11.1.2

## Expected Behavior

When applying AOS (ex. data-aos="fade-left") to each element within an LI within an UL of a slideshow, all slides should animate accordingly. 

## Actual Behavior

However, when I try to apply the AOS (ex. data-aos="fade-left") to each element within an LI within an UL of a slideshow, ONLY the first slide animates when in viewport. However, the subsequent slides do not animate anything and are blank slides. I plan to include more elements within each LI such as images, etc, etc. For now, just sampling with the title. I'm assuming it's DOM-related since they are technically all on the same pane.

## Steps to Reproduce the Problem

http://tamcai.com/help-aos/

![screen shot 2018-08-15 at 7 00 22 pm](https://user-images.githubusercontent.com/33553241/44177800-7a8b1b00-a0bd-11e8-8590-31833d3688ad.jpg)

**Comment by kavasey** [comment]
@tamcai check this issue if it helps #155 
You'll have to get a slider plugin that adds active class to the current slide and follow through from reference to get it working. I'll suggest you look into Swiper or Jquery one like slick slider.
I checked casually at touchslider which you happen to be using and don't see those features.

**Comment by tamcai** [comment]
Thank you @kavasey. Checking out that previous ticket now. Thanks again. :)

**Comment by korragnarok** [comment]
@tamcai  Did you figure this out and could possibly share code to how you solved it? I have been trying to figure this out for 3 days now and finally found someone else asking the same question! Lol
