### ISSUE TITLE
Feature: Events

### ISSUE THREAD

**Issue by nathanaelphilip** [michalsnik/aos#38]
Would it possible to fire some events when things happen? Like after classes are applied to elements, etc? I think this would allow some more flexibility with the script.

I’m really loving it – using it on everything.

**Comment by michalsnik** [comment]
Hi again @nathanaelphilip

Yeah, it would probably be a cool feature, I'm considering it in future releases.
However I think this is of a duplication of request #17, and therefor I'm closing this one.

Feel free to join discussion there :)

Cheers
