### ISSUE TITLE
AOS inside tabs with "once" option enabled

### ISSUE THREAD

**Issue by tonymihay** [michalsnik/aos#380]
If to place AOS inside tabs with option "once: true" then for all hidden tabs it adds respective classes (e.g. aos-animated, fade-in). As a result: all elements that should be animated are displayed initially. Both refresh methods do not help.

**Comment by michalsnik** [comment]
AOS is only detecting whether elements are in the viewport, but not whether they are actually visible (in current tab) or not. It should've worked if content of your tabs was rendered after switching the tab, and not prematurely, as AOS detects mutations in DOM and triggers animation on newly appeared elements.
