### ISSUE TITLE
AOS with Angular [Only animate when resizing instead on scrolling]

### ISSUE THREAD

**Issue by ghost** [michalsnik/aos#383]
Hello, Firstly thank you for the cool animations.

I am trying to implement AOS with Angular 6.

But i have run into some minor issue, as the animations is working but the animations will only 

trigger when i resize my window screen instead of scrolling. 

## This is:

- Bug

## Specifications
 -  AOS with Angular6
  - AOS version:  aos@3.0.0-beta.5
  - Browser: Most Browser 

Shown below is my code

**Home.component.ts @ /src/app/home/home.component.ts**

` import { Component, OnInit } from '@angular/core'; `
` import AOS from 'aos'; `

` @Component..... `

` export class HomeComponent implements OnInit { `
` ngOnInit() { `
` AOS.init({ `
       ` duration: 400, `
`})`
`} ` 
`}`

**Home.component.ts @ /src/app/home/home.component.html**

**home.component.html**
` <div class="box" data-aos="fade-in"></div> `
` <div class="box" data-aos="flip-up"></div> `
` <div class="box" data-aos="fade-in"></div> `

**home.component.css @ /src/app/home/home.component.css**
`.box { `
`  width: 400px; `
`   height: 100px;  `
`    background: red;`
`  } `

**Comment by mahesh-44** [comment]
Hey, why did u close this issue? Did u find the solution ?

**Comment by rahulcool1910** [comment]
I have the same issue can anyone help ??????

**Comment by Vsumskyi** [comment]
has anyone found a solution?

**Comment by alemupx** [comment]
I've try anythin to solve this problem, but omg it seems like no one knows yet whats it's going on with this issue. I hope someone helps us.

**Comment by Regestea** [comment]
all of your code is right except import
replace this line in your import 
import * as AOS from 'aos';
if it doesn't work run this command 
npm i --save-dev @types/aos

**Comment by NMishchenko** [comment]
If anyone still needs a solution, try to execute AOS.init() again.
In my case, when the user clicks a button, a large amount of content is added to the page, so its height changes. I'm executing AOS.init() in button (click) event method.
Maybe, it isn't the perfect solution, but if works for me and I hope it will work for you.
