### ISSUE TITLE
AOS Animation Causing Bottom Scroll Thing

### ISSUE THREAD

**Issue by showment** [michalsnik/aos#388]
## This is:
- Bug

## Specifications

  - AOS version: Newest (I Imported Through HTML)
  - OS: Windows
  - Browser: Google Chrome

## Expected Behavior
It should've just done the animation and not caused any scroll bars to appear

## Actual Behavior
A scroll bar appears in the bottom of the screen of the browser

## Steps to Reproduce the Problem
I do not know.

## Detailed Description
For the animation not to cause the bottom scroll thing to appear.

**Comment by MarioPerini** [comment]
I can confirm: if you have an element which goes outside the viewport (only on right side) it will cause a scrollbar on x because the translate transform.
This issue can easy be fixed with a overflow-x:hidden on the body element.

I do not think it is an issue of the plugin. You should fix it in your own css.

**Comment by SoulSen** [comment]
Doesn't fix anything

**Comment by MarioPerini** [comment]
SoulSen i got a mail with your statement: 

> Doesn't fix anything

You have deleted this answer, so does it fix your issue or not?

**Comment by michalsnik** [comment]
It is known problem and indeed you should solve it yourself with `overflow-x: hidden`. I'll put it in FAQ. Closing for now.

**Comment by paulvladmuresan** [comment]
it's not solveable with overflow-x:hidden; Stop saying things that you haven't tried first this is very frustrating.

**Comment by luisvisintini** [comment]
> Puedo confirmar: si tiene un elemento que sale de la ventana gráfica (solo en el lado derecho), provocará una barra de desplazamiento en x debido a la transformación de traducción. Este problema se puede solucionar fácilmente con overflow-x:hidden en el elemento del cuerpo.
> 
> No creo que sea un problema del plugin. Deberías arreglarlo en tu propio css.

solved!! Thank you very much, very good input!

**Comment by luisvisintini** [comment]
solved!! Thank you very much, very good input!

**Comment by sHimelCSE** [comment]
[MarioPerini](https://github.com/MarioPerini) Thanks. overflow-x:hidden worked.
