### ISSUE TITLE
Mobile format has an blank space added to the right outside of viewport after adding AOS

### ISSUE THREAD

**Issue by djneill** [michalsnik/aos#390]
## This is:

- Bug / - Question
## Specifications

  - AOS version: aos V 2.0
  - OS: Mobile format galaxy S8+, iPhone 8+, samsung galaxy tab
  - Browser: Chrome / Samsung internet browser

## Expected Behavior

Pages were mobile responsive before using AOS

## Actual Behavior

AOS is creating a blank space to the right of page of mobile devices. Laptop screens work as expected

## Steps to Reproduce the Problem

http://dninstalls.com/

![image](https://user-images.githubusercontent.com/19987403/44639851-bd81a400-a983-11e8-8990-36b130c36a8d.png)

## Possible Solution

Tried aos@next, did not fix.
Tried adding this to CSS / HTML did not fix
CSS
.aos-init:not(.aos-animate):after {
position: fixed;
}
HTML
< div class="aos-init" data-aos="zoom-in-up" data-aos-duration="3000" >

**Comment by ledones** [comment]
Hi there, I came here to search the exactly same problem haha

I used the CSS code above and indeed don't work, but when I tried to set overflow-x: hidden on the body tag, worked, the only thing is that the scrollbar still appears above the page. But I guess that's a beggining!

body{overflow-x: hidden}
.aos-init:not(.aos-animate):after {position: fixed;}

**Comment by djneill** [comment]
@ledones, when I set the body overflow-x to hidden all the content that has AOS features, is hidden.

**Comment by damnpradeep** [comment]
Hi ,
I had the same problem when I used this long back. It was a simple solution and it had nothing to do with editing CSS. If I remember correctly it was not ending the div or missing an ">". If I look at your website, when that sticky header appears, the website will not have white space on the right. 

I believe, the problem is that you made a simple mistake in syntax.  What you can do is remove all the occurrence of AOS and start by adding one section at a time. Find out where the problem starts. I will let you know if I remember exactly how i fixed the problem.

**Comment by djneill** [comment]
Thanks @damnpradeep the syntax is good but I was able to some what figure it out, some of the animations like zoom out where blowing the content out of the box until it was done animating and back to normal size. I changed some of the animations and no longer have the problem.

**Comment by lazehang** [comment]
I guess the css transform: translateX while using fade-right animation is also creating this issue. Any solution? Tried changing the position to fixed but doesn't work.

**Comment by djneill** [comment]
@lazehang There were three aos that were causing the problem, fade-up-right, fade-up-left, and zoom-in-up. The zoom-in-up was applied to an entire row with four columns, I am using the zoom-in-up on a single column row that is the title line with no problem. 
I did try hiding the overflow on the X axis based on someone's recommendation but it caused all the aos elements to disappear.

**Comment by matteomelotti** [comment]
The same here.
I have a two section tags, the one below with a negative padding to give a nice effect and the aos is applied on this one.
Everything works fine if i set overflow-x: hidden but in this way i lose the section effect

**Comment by damnpradeep** [comment]
@djneill Yes, That was the problem. I remember now. I used the effect Fade from Right. Which was creating the issue. Later I used Fade from Down, which rectified the problem.

**Comment by michalsnik** [comment]
This is a known issue, and you got to solve it yourself by adding `overflow-x: hidden` on body or other parent container. I'll put this information in the FAQ section :) 

If overflow hides your elements in a weird way it means you used `floats` and didn't use clearfix on the container.

**Comment by bobbyarcher** [comment]
For some reason using "overflow-x: hidden" on both body and html elements messed up my animations, causing some to not appear, so I've instead used the following jQuery to add "overflow: hidden" to all parents of animated elements, which seems to have done the trick:

$('[data-aos]').parent().addClass('hideOverflowOnMobile');

And then in CSS:

@media (max-width: 768px) {
    .hideOverflowOnMobile {
        overflow: hidden;
    }
}

**Comment by tomihbk** [comment]
> body{overflow-x: hidden}

Worked perfectly.

**Comment by mowens86** [comment]
Yessir, I can also attest to this. I had the exact same problem with extra white spacing to the right on mobile.

In the mobile @media queries just use the 
body {
overflow-x: hidden
}

**Comment by fabiosilvanet** [comment]
Hi,

I've the same problem. :-(  I try use:

body {
overflow-x: hidden
}

But not solve the problem. Any idea? Thank you so much.

**Comment by lazehang** [comment]
Could you provide more info?

**Comment by mitchobrian** [comment]
> This is a known issue, and you got to solve it yourself by adding `overflow-x: hidden` on body or other parent container. I'll put this information in the FAQ section :)

NOT or o not put it into the body section! Use the .container or .wrapper oder the #app or #root DIV's your page is using! That will work...

**Das einzige was wirkt:  `overflow-x: hidden;` in einen Übergeordneten Container einfügen!**

**Comment by b1gh3ro** [comment]
> For some reason using "overflow-x: hidden" on both body and html elements messed up my animations, causing some to not appear, so I've instead used the following jQuery to add "overflow: hidden" to all parents of animated elements, which seems to have done the trick:
> 
> $('[data-aos]').parent().addClass('hideOverflowOnMobile');
> 
> And then in CSS:
> 
> @media (max-width: 768px) {
> .hideOverflowOnMobile {
> overflow: hidden;
> }
> }

you my guy are a smart man

**Comment by HayfordEdward77** [comment]
> For some reason using "overflow-x: hidden" on both body and html elements messed up my animations, causing some to not appear, so I've instead used the following jQuery to add "overflow: hidden" to all parents of animated elements, which seems to have done the trick:
> 
> $('[data-aos]').parent().addClass('hideOverflowOnMobile');
> 
> And then in CSS:
> 
> @media (max-width: 768px) {
> .hideOverflowOnMobile {
> overflow: hidden;
> }
> }

Your solution worked perfectly. Thanks

**Comment by sachinmail223** [comment]
> overflow-x: hidden

tnx

**Comment by tdraper-dev** [comment]
Want to flag that using 
```
body {
  overflow-x: hidden;
}
```

then prevented me from being able to scroll vertically on mobile (overflow: hidden obviously had the same effect).
For the time being, I've had to remove my sideways fade in and slide animations, as this seemed to rectify the issue. If anyone has any insight, I'd be so grateful to hear it.

*Issue does NOT appear on my partner's iPhone. Only seems to occur on my android device

**Comment by iamsabbirsobhani** [comment]
> For some reason using "overflow-x: hidden" on both body and html elements messed up my animations, causing some to not appear, so I've instead used the following jQuery to add "overflow: hidden" to all parents of animated elements, which seems to have done the trick:
> 
> $('[data-aos]').parent().addClass('hideOverflowOnMobile');
> 
> And then in CSS:
> 
> @media (max-width: 768px) {
> .hideOverflowOnMobile {
> overflow: hidden;
> }
> }

Works perfectly!

**Comment by pohadkove** [comment]
using sveltekit and had everything wrapped in a main tag and this ended up working perfectly because nothing else did I thought id add this even though the thread is closed

```
@media only screen and (max-width: 600px) {
  main {
    overflow-x: hidden;
  }
}
```

**Comment by maged21** [comment]
make data-aos-once=true it will make it appear once but it will make the right space disapear its always there because its always active until i can figure out another solution

**Comment by Ekbal41** [comment]
thanks for the solution  🥹

**Comment by Nitinsingh08** [comment]
There was empty space on right in mobile view while using the aos library .I fixed it using 
body {
overflow-x:hidden ; } 
in the media queries for the mobile version 
and it solved the problem

**Comment by mahmudaakterdisa** [comment]
After using AOS I faced some issues with responsive for mobile and tab view. but I  fixed it using.
body{
overflow-x: hidden;
}

**Comment by TanjimulSabbir** [comment]
"body{
overflow-x: hidden;
}"
It may not always work. Best to add "overflow" with Root div. And "overflow-x" creates a new scroll bar sometimes in right side.
So, If possible, should use " RootDiv{ overflow: hidden;}.

**Comment by Weng-B0829022** [comment]
'body > *{
  overflow-x: hidden;
}' 
can be executed, but 
'body{
overflow-x: hidden;
}' 
cannot.

**Comment by Carina-F** [comment]
This worked for me: 
 html {
    overflow-x: hidden;
  }
