### ISSUE TITLE
Animations on scroll up

### ISSUE THREAD

**Issue by roweena** [michalsnik/aos#395]
In your blog post on CSS-tricks https://css-tricks.com/aos-css-driven-scroll-animation-library/ you mention both way animations, I can only seem to get animations working on scroll down, not scroll up. What do you need to do to make them work on scroll up too?

Thank you! 

## This is:

- Question

## Specifications

  - AOS version:
  - OS:
  - Browser:

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by roweena** [comment]
Fixed it.

**Comment by irinna77** [comment]
I am having the same issue. how did you fix it?
