### ISSUE TITLE
Error when MutationObserver is not supported

### ISSUE THREAD

**Issue by ncoden** [michalsnik/aos#404]
This is a bug.

## Specifications

  - AOS version: `v2.2.0`, `master`, `next`
  - OS: macOS 10.13.6
  - Browser: [jsdom](https://npmjs.com/package/jsdom) via [uncss](https://npmjs.com/package/uncss)

## Expected Behavior

If MutationObserver is not availaible (not defined), AOS should ignore it and works like if it was disabled.

## Actual Behavior

AOS crashes with the following error:
```
Error: Uncaught [TypeError: ((window.MutationObserver || window.WebKitMutationObserver) || window.MozMutationObserver) is not a constructor]
```

This comes from the following lines (in both `master` and `next`) that uses the Mutation Observer without checking if it is defined. There is no others checks elsewhere in the codebase.

https://github.com/michalsnik/aos/blob/68a0d523620c76eee5a4fd3b0ca161367a9dfb1e/src/js/libs/observer.js#L25-L30

## Steps to Reproduce the Problem

1. Install jsdom.
2. Start it on a page where AOS is imported.
3. Profit.

## Possible Solution

Check for `MutationObserver` in [src/js/libs/observer.js](https://github.com/michalsnik/aos/blob/68a0d523620c76eee5a4fd3b0ca161367a9dfb1e/src/js/libs/observer.js) or provide an utility to test if Mutation Observer is supported and use it in [src/js/aos.js](https://github.com/michalsnik/aos/blob/next/src/js/aos.js).

**Comment by ncoden** [comment]
@michalsnik I can submit a pull request if you want. Please just confirm me that this repo is still maintained.

**Comment by michalsnik** [comment]
Hey @ncoden, thanks for posting this issue! Yes - this repo is still maintained. Feel free to submit PR to the v2 branch. I can release a bug fix.

**Comment by ncoden** [comment]
Fixed by https://github.com/michalsnik/aos/pull/405.
