### ISSUE TITLE
aos.js:122 Uncaught TypeError: Cannot read property 'setAttribute' of null

### ISSUE THREAD

**Issue by iTayGNR** [michalsnik/aos#42]
I put the CDN imports, and added the init at the `<head>` of the page, but animation doesn't work and that's what I get on chrome console:

`aos.js:122 Uncaught TypeError: Cannot read property 'setAttribute' of null`

**Comment by natlus** [comment]
@iTayGNR 
The script is being initiated before the elements you want to animate are created.

Put the init at the bottom of your page and see if that helps.

**Comment by michalsnik** [comment]
Yes, the issue here is definitiely that you initiate AOS in HEAD @iTayGNR .

Line 122 is:
```
document.querySelector('body').setAttribute('data-aos-easing', options.easing);
```

And there is no element like `body` in your DOM yet.
Move `AOS.init()` right before `</body>` and it'll be all right.

**Comment by gianmarcodelfreo** [comment]
thanks
