### ISSUE TITLE
PageSpeed on specific animations

### ISSUE THREAD

**Issue by RiccardoB** [michalsnik/aos#43]
This is not properly a bug/error but more a warning: when you check your website with Google PageSpeed (this could also affect other applications that parse the website similarly to it) and you use an AOS animation that resize the image (like the flip-) the insight alerts you to "compress and resize your image",  meanwhile using animations that don’t resize the image (like the fade-) no alerts are shown.

PageSpeed also suggest you the image size to use instead and for a 220x220px having flip-left it suggests you to use a 38x188px image.

**Comment by michalsnik** [comment]
Thanks a heads up! however I don't think that we can do anything about this ;/
