### ISSUE TITLE
AOS animations not working when element is shown/hidden using jQuery

### ISSUE THREAD

**Issue by Jake-Thomas-Hall** [michalsnik/aos#436]
Hey there, I'm facing an issue when using AOS and jQuery, and there doesn't seem to be anything relevant anywhere on StackOverflow etc so I hope you guys can help.

I'm using mdboostrap, jQuery and AOS on a small project page I'm working on. AOS is working brilliantly apart from in one section. In this section I've set it up so that clicking a button will show another element further up the page, which looks like so:

```javascript
$(document).ready(function(){
    $("#element1").hide();
    $("#button1").click(function(){
        $("#element1").fadeIn();
        $("#element2").hide()
    });
});
```

As you can see it's nothing complex, just shows one element while hiding another upon a button click. The problem I'm facing is that the AOS animations aren't working on this element that is shown using jQuery, the element being targeted has all the needed data-aos components, and works fine when not being shown using jQuery.

Is this something to do with how jQuery is already using CSS animation components to show the element, which is then causing issues when AOS tries to animate an element?

Is there something obvious I'm missing? I'm pretty new to this, sorry in advance if I'm being a little stupid here.

Here is the element that is being shown and which I'm trying to animate with AOS:

```html
<div class="container" id="element1" data-aos="fade-up" data-aos-anchor-placement="center-bottom" data-aos-duration="600">
    <div class="row" data>
        <div class="col-md-6 col-sm-12 margin20">
            <!-- Card -->
                <div class="card card-image rounded h-100" style="background-image: url(Images/BlockDodgeLogo.png);">
                    <!-- Content -->
                    <div class="text-white text-center d-flex align-items-stretch rgba-black-strong py-5 px-4 rounded h-100">
                        <div>
                            <h3 class="card-title pt-2"><strong>Government</strong></h3>
                            <p>
                                Follow the below link to learn more about our government and how it works.
                            </p>
                            <a class="btn btn-amber"><i class="fa fa-clone left"></i> View page</a>
                        </div>
                    </div>
                    <!-- Content -->
                </div>
            <!-- Card -->
        </div>
        <div class="col-md-6 col-sm-12 margin20">
            <!--Card -->
            <div class="card card-image rounded h-100" style="background-image: url(Images/RaspberryPi.jpg);">
                <!-- Content -->
                <div class="text-white text-center d-flex align-items-stretch rgba-black-strong py-5 px-4 rounded h-100">
                    <div>
                        <h3 class="card-title pt-2"><strong>Voting System</strong></h3>
                        <p>
                            Follow the below link to learn more about our voting system, including how and why it works.
                        </p>
                        <a class="btn btn-amber"><i class="fa fa-clone left"></i> View page</a>
                    </div>
                </div>
                <!-- Content -->
            </div>
            <!-- Card -->
        </div>
    </div>
</div>
```

Greatly appreciate any help you can provide!

**Comment by Jake-Thomas-Hall** [comment]
Figured out my problem, turns out when you show previously hidden content via jQuery or JavaScript you need to use AOS.init or AOS.refresh within whichever script you are using to show the new page content, so in my case like so:

```javascript
$(document).ready(function(){
    $("#element1").hide();
    $("#button1").click(function(){
        $("#element1").fadeIn();
        $("#element2").hide();
        $("#element3").hide();
        AOS.refresh();
    });
});
```

**Comment by Narek42** [comment]
Hi everyone  help me please how i can hide element on click with aos

**Comment by chambyal** [comment]
> Hi everyone help me please how i can hide element on click with aos
HI @Narek42

Please review  & replace  hide element  with you  element  


    $(function() {
      AOS.init({
       duration : 1200,
     });

     $('#investorbtn .slider.round, .navborrow').click(function(){  
          
              $(this).toggleClass('switchbtn');
              $('body').addClass('borrower-page');
              $('.borrowerpage').fadeIn(500);
              $('.investorPage').fadeOut(100);
              $('html, body').animate({ scrollTop: 0 }, 'slow');
              localStorage.setItem('userType', 'borrower');
             // return false;
            });
          
$('#borrowerbtn .slider.round, .navinvest').click(function(){
                $(this).toggleClass('switchbtn');
              $('body').removeClass('borrower-page');
              $('.borrowerpage').fadeOut(500);
              $('.investorPage').fadeIn(500);
              $('html, body').animate({ scrollTop: 0 }, 'slow');
              localStorage.setItem('userType', 'investor');
                   
          });

    onElementHeightChange(document.body, function(){
        AOS.refresh();
      });
    });

    function onElementHeightChange(elm, callback) {
        var lastHeight = elm.clientHeight
        var newHeight;
     (function run() {
            newHeight = elm.clientHeight;      
            if (lastHeight !== newHeight) callback();
            lastHeight = newHeight;
    
            if (elm.onElementHeightChangeTimer) {
              clearTimeout(elm.onElementHeightChangeTimer); 
            }
    
            elm.onElementHeightChangeTimer = setTimeout(run, 200);
        })();
      }
