### ISSUE TITLE
Cannot get the animations to fire.

### ISSUE THREAD

**Issue by Creagaia** [michalsnik/aos#44]
Hello! I am having problems with getting the animations to fire. What am I doing wrong? 

Issue is here:
http://www.worklemon.com/

Thanks!

Mike

**Comment by sharden** [comment]
**I had a similar issue but was able to resolve. If you're reading this and used the provided CDN's please read.**

Crack open inspect element in your browser and do the following: 

1. Check the DOM element where you added data-aos="blah" and scroll. If JS is loaded you'll see the class names change dynamically. If that works, your JS file is good but your css may be missing.

2. Select Sources to verify 'cdn.rawgit.com/michalsnik/aos/2.*(version you're on) is there and loads both aos.js and aos.css. My css didn't load even using the provided CDN so I manual placed the css file.

Hope this helps.

**Comment by Creagaia** [comment]
Thank you very much for your reply! I was doing some troubleshooting and figured it out in the end. I ended up including the files locally as well.
