### ISSUE TITLE
aos.js:122 Uncaught TypeError: Cannot read property 'setAttribute' of null

### ISSUE THREAD

**Issue by alopez25** [michalsnik/aos#45]
Hi, 
I'm trying to use AOS but I can't make it work.

The divs disappear completely from the webpage and I get this error in the console: 
'aos.js:122 Uncaught TypeError: Cannot read property 'setAttribute' of null'

I'm referencing the JS file to:
<script src="https://cdn.rawgit.com/michalsnik/aos/2.0.4/dist/aos.js"></script>

I've tried to do it locally and I get the same error. I'm quite new with CSS and JS so I wonder if this is some kind of bug in AOS or I'm simply doing something wrong.

I wonder if this is a know issue and if you could guide me to the appropriate way to solve it.

Thanks

**Comment by michalsnik** [comment]
Hi @alopez25 

I answered recently the same question here #42

Let me know if that was the case, so I can close this issue.

And in the future please take a look at closed issues first, it's possible that someone already had similar problem :)

**Comment by alopez25** [comment]
Hi Michalsnik,

Yes it seems to be the same issue. You can close it now.

Sorry for not checking other issues before hand I'll definitely do it next time.

Thanks for your time and your wonderful script. Very useful!!

Andres
