### ISSUE TITLE
Question: Continuously Animate While Scrolling

### ISSUE THREAD

**Issue by katart** [michalsnik/aos#450]
## This is:

- Question

## Specifications

  - AOS version: latest
  - OS: N/A 
  - Browser: N/A

## Expected Behavior

Can this AOS library allow for animating an element WHILE scrolling? So if I wanted an element to Fade-In-Left, the element would only move left to it's final position WHILE I scroll and NOT move to it's final position when I scroll to a position. (functional example: https://www.ateliergymnase.com - scroll down to l'équipe)

**Comment by patrick-mcdougle** [comment]
This library does not do that. You're possibly wanting something like scrollmagic.
