### ISSUE TITLE
[Question] How to change the 'date-to-offset' on mobile screens?

### ISSUE THREAD

**Issue by jonasmarco** [michalsnik/aos#462]
**[Question] How to change the 'date-to-offset' on mobile screens?**

Example

I have a div where the animation has one 'data-aos-offset=800', to load on the desktop, but on the mobile, I run the entire div for the animation to occur, how do I set up a date-aos-offset for the small screens?

```
<div class="sobre xlarge-padding-left-1" data-aos="fade-up" data-aos-offset="800">
...
</div>
```

**Comment by spogulis** [comment]
Do you mind sharing how you resolved this?

**Comment by jonasmarco** [comment]
> Do you mind sharing how you resolved this?

Hi dude, I probably did a 'hack' with javascript using [resize()](https://api.jquery.com/resize/), and applying the value I wanted according to the width of the screen ([window.innerHeight](https://api.jquery.com/innerHeight/))
