### ISSUE TITLE
AOS fade-left on all mobile responsiveness whitespace to the left Bootstrap 4

### ISSUE THREAD

**Issue by conradKE** [michalsnik/aos#472]
## This is:

- Bug

## Specifications

  - AOS version:2.3.1
  - OS:linux
  - Browser:chrome

## Expected Behavior

animation to fade from left 

## Actual Behavior
it fades from left but leaves a white to the left on bootstrap

## Steps to Reproduce the Problem
add this on body bootstrap 4
```html
<div data-aos="fade-left" data-aos-duration="2000" class="col-lg-4">
					<div class="work_item">
						<a href="#">
							<h4>head</h4>
						</a>
						<p>paragraphi.</p>
					</div>
				</div>
```

other work fine expect this fade from left

## Possible Solution
margin-left should be removed or set to zero because it creates a whitespace on css aos

**Comment by iaghapour** [comment]
I have the same problem.

**Comment by mkfizi** [comment]
hi, is there a way to fix this?

**Comment by nicanorsuarez01** [comment]
add overflow: hidden to the parent class

**Comment by infabo** [comment]
This is not a suitable solution. This has multiple side-effects.

**Comment by volkandkaya** [comment]
Agreed, we're using this in a website builder where customers have no coding experience.

Is there anyway to fix this without relaying on adding overflow: hidden to parent classes?

**Comment by TasneemDahlan** [comment]
overflow-x: hidden for the div or section or body, this solving working well

**Comment by arrahmanbd** [comment]
Simply add those line on your stylesheet and see magic

```
* {
  margin: 0px;
  padding: 0px;
  overflow-x:unset;
} 
```

**Comment by infabo** [comment]
```css
* {
  display: none;
} 
```

**Comment by ogunnergizal** [comment]
*{
overflow-x:clip;
}

**Comment by Andrewdev21** [comment]
> *{ overflow-x:clip; }

I love youuuuuuuuuu <3

**Comment by karkarrahil** [comment]
there is no way to any solution
