### ISSUE TITLE
Modifying Distance

### ISSUE THREAD

**Issue by thewinger** [michalsnik/aos#48]
Right now all movement (translate, flip, etc) are static. 

Is there a way of specifying them different for some elements? 

p.e. data-aos-distance.

**Comment by michalsnik** [comment]
Hi @thewinger. There is no such an option, but if you need custom animation, you can easily add your own and use it with `data-aos="your-animation-name"`.
Check out this codepen http://codepen.io/michalsnik/pen/WxvNvE
