### ISSUE TITLE
Working AOS in with React.

### ISSUE THREAD

**Issue by teesloane** [michalsnik/aos#49]
Love the looks of this little library. I'm unsure if I'm missing something completely obvious, but haven't had any luck implementing this with react.

I'm using [create-react-app](https://github.com/facebookincubator/create-react-app).

I have a long product page, with lots of sections, each one being rendered by it's own react functional component, that looks relatively like this:

```javascript
import React from 'react';
import './XYZ.css';
import XYZImg from './assets/XYZ.png';
import AOS from 'aos'

const ProductXYZ = () => {

  AOS.init()

  return(
  <section className="Product-XYZ">
    <div className="content XYZ-container">

      <img className="product-img" data-aos="fade-zoom-in" alt="XYZ" src={XYZImg} />

      <section className="XYZ-details">
        <h2 className="product-header">  Lorem ipsum etc. </h2>
        <p className="product-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, .</p>
      </section>

    </div>
  </section>
  )

}

export default ProductXYZ;
```

I've tried `init`ing AOS on the parent level component and in a per component basis but neither have had any luck getting an image / html element to animate in on scroll.

Anything I'm missing?

Thanks!!

edit: extra notes

- create react app uses webpack - but the `.config` file is not exposed unless you `eject` your project. So I haven't looked into how that might make a difference...

**Comment by michalsnik** [comment]
I didn't try to use it with react, but tried it with different frameworks like Meteor and I didn't have any problems.

Please import AOS in parent level component and init it there. This should be called only once.
AOS has implemented observer, so whenever new item appears in DOM it should animate it properly.

I noticed that the animation in your snippet is wrong, unless you created a custom animation. There is no `fade-zoom-in` by default. This might be your issue. Please confirm if it's working using simple `fade-in`.

**Comment by teesloane** [comment]
Ah, of course. Made the changes you suggested and all good. Thanks for the help!

**Comment by ericvrp** [comment]
This only worked for me once I copied dist/aos.css to my project directory and import it.

**Comment by Roshdy** [comment]
Can you please provide steps to setup on Meteor. I did install it by npm, did the import client side, but it gives me AOS is undefined.

**Comment by davidecarpini** [comment]
My working code:
`
import AOS from 'aos';
import 'aos/dist/aos.css';

class App extends React.Component {
  constructor(props){
    super(props);
  }
  componentDidMount(){
    AOS.init({
      duration : 2000
    })
  }
  render(){
    return(
        <div data-aos='fade-up'>
          Helloooo!
        </div>
    )
  }
};

export default App;
`

**Comment by sanjoggit** [comment]
@davidecarpini does it also works every-time when scrolling up/ down? If not do you have any idea how to make it happen?

**Comment by davidecarpini** [comment]
@sanjoggit yes, it works!

**Comment by dsmklda** [comment]
Great, thanks

**Comment by physixpro** [comment]
I tried to do it as you did, but my constructor(props) keeps getting an error. I'm not sure what to do.

import React, { Component } from "react";
import AOS from 'aos';
import 'aos/dist/aos.css';

class Blaque extends Component {
  constructor(props){
    super(props);
  }
  componentDidMount(){
    AOS.init({
      duration : 2000
    })
  }
  render() {
    return (
      <div className="Blaque">
        <h1 className="club" id="club-one">
          {this.props.value}
        </h1>
        <h2 className="health" id="pageonehealth">
          {this.props.health}
        </h2>
        <ul id="pageone-list">
          <li>
            <a href="#information">{this.props.about}</a>
          </li>
          <li>
            <a href="#waitlist-box">{this.props.join}</a>
          </li>
          <li>
            <a href="mailto:esorts.k990@gmail.com">{this.props.contact}</a>
          </li>
        </ul>
      </div>
    )
  }
};


export default Blaque;

**Comment by TesLake** [comment]
You also need AOS css.

import "aos/dist/aos.css"

**Comment by imranali4264** [comment]
not worked on mobile view any help

**Comment by anshumandikshit** [comment]
> Ah, of course. Made the changes you suggested and all good. Thanks for the help!

Have you fixed the issue....i am facing problem ...i have defined in AOS.init() and trying to animate the child components but not working...any suggestions that might be helpful??

**Comment by thamanchand** [comment]
Yeah it doesn't seem to work in mobile view

**Comment by emre-edu-tech** [comment]
Hey there! I'm trying to use it while developing a laravel application and naturally using laravel framework version of webpack as Laravel Mix. But no luck I almost tried every way of importing this library and not working.

**Comment by emre-edu-tech** [comment]
It just happened to me. I guess finally succeed in making it work.
I use
`import AOS from 'aos';`
in the same file that I was using AOS.init method and it worked. As I said before I'm using laravel version of webpack.
Hope it helps.

**Comment by sysprim** [comment]
Actually I'm working with create-react-app  and Material UI, I'm trying to animate some components but doesn't work any. I tried with initialize in parent component and doesn't work also. Can someone help me with it?

**Comment by GabenGitHub** [comment]
I made like this:

```
import React, { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";

function App() {
  useEffect(() => {
    AOS.init();
    AOS.refresh();
  });

  return (
    // your components
  );
}

export default App;
```

**Comment by emre-edu-tech** [comment]
@GabenGitHub normally this should work like this. I use webpack with browserify in a Laravel project. Maybe it is a React thing. I'm not a React user so maybe you can search the answers that uses React.

**Comment by jAbusama** [comment]
> My working code:
> on terminal:
> 
> ```
> npm install aos
> 
> or
> 
> yarn add aos
> ```
> 
> in root component:
> 
> ```
> import AOS from 'aos';
> import 'aos/dist/aos.css';
> 
> class App extends React.Component {
>   constructor(props){
>     super(props);
>   }
>   componentDidMount(){
>     AOS.init({
>       duration : 2000
>     })
>   }
>   render(){
>     return(
>       <div data-aos='fade-up'>
>         Helloooo!
>       </div>
>     )
>   }
> };
> 
> export default App;
> ```

this is work for me. Thanks!

**Comment by Vetrivel-VP** [comment]
Hai I'm facing problem with this AOS. Its working only for a single component inside the APP. For instance in my  app I'm having multiple components like HOME, WORK, Service ...Its working fine in Home but when its comes to work or services its not showing the content...Can any help me to get throygh this

**Comment by andresa** [comment]
> Hai I'm facing problem with this AOS. Its working only for a single component inside the APP. For instance in my app I'm having multiple components like HOME, WORK, Service ...Its working fine in Home but when its comes to work or services its not showing the content...Can any help me to get throygh this

Hey @Vetrivel-VP , I'm facing this same issue, did you manage to find a solution?

**Comment by tusharjain365** [comment]
I am using aos in reactjs app but it doesn't working.
I have used module.css file in react and maybe aos doesn't work with module.css as when I import it in the main file, all the divs that were using it, become invisible.

**Comment by timmellis** [comment]
> I am using aos in reactjs app but it doesn't working. I have used module.css file in react and maybe aos doesn't work with module.css as when I import it in the main file, all the divs that were using it, become invisible.

This is precisely the problem I'm having in my React App, too. 
The elements in "Home.jsx" are fading in on load, but everything below that (e.g. "About.jsx") is just invisible. I assume they get hidden by AOS so that they will fade in later, but nothing hidden below the viewport window ever gets triggered on scroll.

**Comment by CheloNeo** [comment]
Hi, I have problems with AOS, in react I import aos.css, AOS from aos, then in useEffect I do AOS.init, but it turns out that the animations are not reflected until I restart the component.
