### ISSUE TITLE
AOS Attributes doesn't work with svg tags. (IE)

### ISSUE THREAD

**Issue by ozturkcangokkaya** [michalsnik/aos#50]
When i add aos attributes to my svg elements  IE doesn't render my html and doesn't show the elements with aos attributes.
Here is my code.

-- HTML --
`<svg height="72" width="72" stroke-dasharray="220" stroke-dashoffset="221" data-aos="fill" data-aos-duration="600" data-aos-delay="600" data-aos-anchor=".content">
      <circle cx="36" cy="36" r="35" stroke="#999FAF" stroke-width="1" fill="transparent"></circle>
</svg>`

-- CSS --
`[data-aos='fill'] {
        stroke-dashoffset: 221;

        &.aos-animate {
            stroke-dashoffset: 0;
        }
    }`

**Comment by GroFinJarryd** [comment]
I have a similar issue where the HTML is being hidden with IE10 IE 11 works

**Comment by michalsnik** [comment]
@ozturkcangokkaya Can you confirm It only happens with SVG's on IE? Which versions?
If you could provide me with a codepen example I could easily debug this and find a solution.

**Comment by ozturkcangokkaya** [comment]
Yes it only happens with svg tags. 
Im not sure about the versions i have IE 10 on my mac.

Here are the pens.

http://codepen.io/anon/pen/ORgqkE
http://codepen.io/anon/pen/gwREBz // My solution

**Comment by michalsnik** [comment]
Thanks for a reply @ozturkcangokkaya. It looks however like a more global problem with SVG's. Calculating offset of SVG elements and elements inside them is not working the same way as for usual DOM elements so it won't work properly anyway.

Your solution with wrapping SVG inside a div seems like a best solution for now.

Thanks for your time, but unfortunately according to this offset issue I'm not going to support SVGs natively for now.
