### ISSUE TITLE
Please create a codepen example of aos.js with animate.css because I tried as your guides but did not get success.

### ISSUE THREAD

**Issue by skwebs** [michalsnik/aos#525]
## This is:

- Request

## Specifications

  - AOS version:

## Detailed Description

 - I tried to use aos.js with animate.css according to your guidelines and using your demo script [animatecss.html](https://github.com/michalsnik/aos/blob/next/demo/animatecss.html) on codepen ([Link](https://codepen.io/sk05/pen/gObpPEP)) but didn't get success. 
- Please fix bugs or errors of my codepen if found or create a fresh codepen.

- My Codepen Link.
 [AOS with AnimateCSS](https://codepen.io/sk05/pen/gObpPEP)
## Possible Solution

- I requested to you please create a codepen aos.js with animate.css for better understanding.

**Comment by BenQuirk** [comment]
This code pen might be helpful:

https://codepen.io/michalsnik/pen/WxNdvq

**Comment by srmahmud2** [comment]
> 
> 
> This code pen might be helpful:
> 
> https://codepen.io/michalsnik/pen/WxNdvq

This is the default AOS. Can somebody please give us a codepne link for AOS integrated with latest animate.css which has changed their default calls name. like this: " animate__ "

**Comment by linuxguist** [comment]
Hi @srmahmud2 

Here is a working codepen link for AOS with Animate.css : https://codepen.io/nathan-sr/pen/KKYOype

Thanks & Credits to the excellent AOS Library and its contributors !

Best Regards,

Nathan S.R.
