### ISSUE TITLE
"aos" does not work if imported locally as a bundled module

### ISSUE THREAD

**Issue by stefanobartoletti** [michalsnik/aos#528]
## This is:

- Bug

## Specifications

  - AOS version: `2.3.4`
  - OS: `Linux`
  - Browser: tested both on `Chromium` and `Firefox`, doesn't seem to be browser-related

## Expected Behavior

Animations should happen as intended, like shown on the [demo page](https://michalsnik.github.io/aos/)

## Actual Behavior

The Javascript part of `aos` isn't working when imported and loaded from local, the elements that should be animated don't render on the page, it seems that the animations doesn't even start. If I load the Javascript part of `aos` from CDN it works correctly, so I can rule out problems with the `AOS.init()` function, it is not the part that causes problems.

## Steps to Reproduce the Problem

*Please see below for a detailed description*

## Detailed Description

`aos` isn't working correctly if imported from local files, retrieved with `npm install --save-dev aos`; it works if loaded from a CDN.

I'm using `Gulp` for my tasks and `Rollup` as a bundler.

I'm importing `aos` in the following way:

**CSS:**

```css
// content of my custom style.scss

/* some other code */

@import "node_modules/aos/src/sass/aos";

/* some other code */
```

**JS:**

```js
// content of my custom scripts.js

/* some other code */

import "aos";

AOS.init({
    offset: 200,
    delay: 100,
    duration: 1000,   
});

/* some other code */
```

**TASK:**

```js
// content of my gulpfile.js

/* some other code */

const rollup = require('gulp-better-rollup');
const babel = require('rollup-plugin-babel');
const resolve = require('@rollup/plugin-node-resolve');

const jsSrc = './src/js/';
const jsDist = './dist/js/';

function js() {
    return src(jsSrc)
        .pipe(rollup({plugins: [babel(), resolve()]}, 'umd'))
        .pipe(dest(jsDist))
};

exports.js = js;

/* some other code */

```

After running my Gulp tasks, the CSS part works correctly, while the JS not;  I get the following notice during the execution of the `Gulp`/`Rollup' tasks: `The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten`.
This happens only with `aos`, other Javascript modules (like, in example `lazysizes`) are imported correctly and work as expected, so my reasoning is that the problem should not be in my setup.

The CSS part works both if loaded from local files and from CDN, but the Javascript part only works if loaded from CDN (of directly from the `node_modules/aos/dist` folder) but when trying to bundle it, it doesn't.

## Possible Solution

I don't know  :)
But this is possibly related to #518 / #422 / #423

**Comment by tripy37** [comment]
Just checking you haven't missed a typo but should your script.js import statement be:
`import AOS from 'aos';`

**Comment by stefanobartoletti** [comment]
Thank you, I actually managed to solve this by modifying my export statement to `import AOS from "aos";` as you suggest, and I also had to use `rollup-plugin-commonjs` in addition to the other plugins that I mentioned on my previous post.

This can be considered solved I think.

**Comment by SAM-BAMKOLE** [comment]
Aos isn't working when installed locally.
It works with the cdn link but when installed using nom, it just isn't working.
Am working on a basic file without a web bundler.
