### ISSUE TITLE
[improvement] Use less generic variables names

### ISSUE THREAD

**Issue by wujekbogdan** [michalsnik/aos#53]
`$val-sm`, `$val-md`, `$val-lg` and especially `$easing` are IMO too generic. It would be good to add prefixes, like `$aos-val-sm`.

**Comment by michalsnik** [comment]
I agree, this is a good idea. The initial assumption was to use `dist/aos.css`, but if you'd like to change animation distance - it makes sense to use source file in order to override default variable.

**Comment by michalsnik** [comment]
Check out new version of AOS `2.1.1`

**Comment by wujekbogdan** [comment]
thanks!
