### ISSUE TITLE
AOS not working with Bootstrap collapse.js

### ISSUE THREAD

**Issue by andreanepori** [michalsnik/aos#530]
## This is a

- Bug

## Specifications

  - AOS version: latest
  - OS: Mac OS
  - Browser: Chrome, Safari

## Expected Behavior

I have a few animated divs that are contained inside a wrapper I'm collapsing with class="collapse", which is the usual Bootstrap div toggle, nothing fancy. 
The collapsed div should open, and the div inside should animate as usual. 

## Actual Behavior

If I don't un-collapse the div, everything works fine. 
When I open the collapsed div by clicking on the trigger element, AOS stops working inside the whole page. What's weird is that if I resize the window of even 1px, the script starts working again. I tried to hack a solution with a fake window resizing to reset aos, but I couldn't make it work. Any idea how I could solve this? 

## Possible Solution
Maybe triggering a reset of the script init could work, but I haven't tested it yet. Anyone had the same issue? Any ideas? 

Thanks

**Comment by andreanepori** [comment]
Solved. 

I put AOS.init(); at the end of my toggle jQuery function. 
Apparently re-initializing AOS is sufficient to fix the issue.

**Comment by aakashe2dev** [comment]
I have using AOS and after that I use Toggle of jquery.
In default active section it working fine but in next toggle it not working
