### ISSUE TITLE
[improvement] Add !default to SASS variables

### ISSUE THREAD

**Issue by wujekbogdan** [michalsnik/aos#54]
At the moment it's not possible to override `$val-sm`, `$val-md` and `$val-md` variables. It could be easily fixed by adding the `!default` statement.

The `!default` statement makes it possible to override variables before a SASS file is @imported. Reference: https://robots.thoughtbot.com/sass-default

**Comment by michalsnik** [comment]
It's related with #53 . I got your point, it makes sense. I'll make it possible to extend source styles and override default variables.
