### ISSUE TITLE
Not working with Next.js Link

### ISSUE THREAD

**Issue by asimhafeezz** [michalsnik/aos#544]
i created a layout page and imported there and initialized in useEffect hook... when the whole page refreshes it works awesome... but when i use client side routing mea Link then ...i think it just work for first... then boom... no animation... and when again i refresh the page it starts working awesome again..
so , is it initializing issue...if it is , then where should i do it?

**Comment by muco-rolle** [comment]
I have the same problem

**Comment by memorysd2013** [comment]
I just meet same problem and I've resolved that, all you need to do is trigger AOS.init() again when you back to same page, here is what I do:

First, my project is builded on Nuxt.js, I use keep-alive let my component has the lifecycle called "activated()", the function in the activated() will be triggered when every time you load same page but not refresh. And just run AOS.init() in activated() and it work!

layout:
```
keep-alive
  my-component
```
component: (which using aos animate)
```
activated() {
  AOS.init()
}
```
Don't forget keep-alive or you won't trigger the activated lifecycle.
Hope those can help you guys!

**Comment by muco-rolle** [comment]
Thank you @memorysd2013

**Comment by abdulimr** [comment]
Check out #574 if you'd like another approach!
