### ISSUE TITLE
Animate dinamically during scroll

### ISSUE THREAD

**Issue by wassy83** [michalsnik/aos#559]
Hi to all,
I love AOS and I'm using it in all my projects, but I'm trying to understand if there is a way to animate my elements during the scroll dinamically, I mean that the animation doesn't starts end finish after  reaching the trigger position, but runs and stops simultaneously with the movement of my scroll up and down. I found scrollmagic.js that is doing this, but maybe there is way to obtain the same effect with AOS, or at least a suggestion on how to avoid the use of another library.
many thanks

**Comment by evankford** [comment]
You're right on that this is usually done with scrollmagic.js. 

Depending on how heavy the animation is, you can set a CSS variable with javascript and dynamically update it on scroll/resize. Then set your transform value in CSS to equal the variable set on the body/wrapper element. You could theoretically even use a `[data-aos]` CSS selector to combine the two.

As for any native AOS functionality, this library only really checks for the moment the item enters your screen/leaves, and doesn't update anything in between.

**Comment by wassy83** [comment]
thank you so much for your support.
regards from Italy
