### ISSUE TITLE
Separate the core SCSS from the animations SCSS

### ISSUE THREAD

**Issue by wujekbogdan** [michalsnik/aos#56]
IMO it would be good to split SCSS files into:
- aos.scss - this file will include the following files:
- _core.scss - core styles only (so basically variables and [data-aos] only). 
- _animations.scss - animations only.

This will allow to include all the styles at once (by including the aos.scss file) or to include the core styles only - without animations. I will not break the backward compatibility.

**Comment by michalsnik** [comment]
It seems like a good idea. It's been a long time since the last work on styles. I'll clean them a little bit soon.
