### ISSUE TITLE
Elements aren't showing at all.

### ISSUE THREAD

**Issue by thevipinmishra** [michalsnik/aos#562]
Added aos.css to head tag
Added aos.js to the before the closing body tag

Added `AOS.init()`; after aos.js occurance.

Added `data-aos="fade-up"` to my element and its completely invisible. (Opacity: 0)

I don't have any overflow:hidden on concerned element or head/body tag. Also tried` AOS.init();` on page load, tried `AOS.refresh` on page load but its just not working.

**Comment by ghost** [comment]
**Uh,**
Can you try do use the stable version instead of aos next?
You can find it [here](https://github.com/michalsnik/aos/tree/v2).
Try to use it, and see if it work or not.

*Note: Please control also if your css go in conflicts with aos.*

**Comment by CreateSean** [comment]
Same issue

Using AOS 2.3.4

**Comment by ghost** [comment]
@CreateSean can you reproduce the error in codepen? (or js fiddle, whatever you want)?

**Comment by CreateSean** [comment]
I tried on a different site and it works fine. there must be somthing on this one site causing issues. so let's put this down to user error on my part.

**Comment by thevipinmishra** [comment]
Not gonna use it again. It always conflicts with your CSS & there's no way to debug and see what'a going on.
