### ISSUE TITLE
AOS IE (Internet Explorer) 10 not displaying HTML on Scroll - Opacity still 0

### ISSUE THREAD

**Issue by GroFinJarryd** [michalsnik/aos#57]
I have a problem with IE10 (or IE 10 render mode) where the elements are created but hidden with opacity 0, some how its not changing them on scroll 
![image](https://cloud.githubusercontent.com/assets/21123434/18645892/61a834ec-7eaf-11e6-8cdf-91cf9dbe1de2.png)

**Comment by michalsnik** [comment]
It happens with all elements on IE10? Or a specific one?

**Comment by michalsnik** [comment]
No confirmation since September and no other issues like this. I presume it's working fine, there was some work regarding IE's in the meanwhile.

**Comment by demyan1411** [comment]
I have the same issue, class aos-animate not added in ie10

**Comment by Mackenzierae** [comment]
I'm having the same issue. Exactly what the original message was.

**Comment by jacoob1406** [comment]
me too

**Comment by esbenjuul** [comment]
me too

**Comment by yuuk** [comment]
me too

**Comment by rehamwael** [comment]
me too :(

**Comment by JDEscobar** [comment]
Having the same issue on E10.

**Comment by nadinezein** [comment]
Me too... Has anyone found a solution to this?

**Comment by maexen** [comment]
Edit message:
I apologize, Console signaled AOS, but problem was caused by another script.

**Comment by cmachanic** [comment]
Any luck with this issue IE 10 issue? I'm using the basic installation, and the first element on the page will animate just fine, but the others remain hidden on scroll. Note: IE 11 and Edge work fine.

**Comment by lindsayweb** [comment]
I have the same issue. The first element animates in. None of the other elements will animate.

**Comment by dohoonk** [comment]
Same issue.

**Comment by devule** [comment]
Same

**Comment by Ryeadkhan** [comment]
same problem.whai i do plz suggest me!
