### ISSUE TITLE
Remove element to be able to have shorter animation

### ISSUE THREAD

**Issue by J-Kallunki** [michalsnik/aos#58]
If animation duration is long enough, scrolling element out of the view (opacity: 0) animation lasts too long. If you scroll back to elements position it could be still doing the hiding animation.

Maybe setting hiding animation duration to smaller fixed value or with new data-attribute.

I quickly handled it with this css:

```
[data-aos][data-aos][data-aos-remove='100']:not(.aos-animate)
  transition-duration 100ms
```

Also option to hide (opacity: 0) faster than doing the movement `transition-duration 100ms, 500ms`

**Comment by michalsnik** [comment]
Hi @J-Kallunki,

Thanks for a heads up. I'll take a look at this somewhere around this weekend :)
