### ISSUE TITLE
Only call animation on page load/first time the user scroll down?

### ISSUE THREAD

**Issue by AbreezaSaleem** [michalsnik/aos#587]
I only want the animations to be called once. When the user scrolls down for the first time on page load. 

## This is:
- Question

Right now the animation gets called again every time I slightly scroll up and back down.

**Comment by 119402282** [comment]
Hi,
did you find a way of calling the function without scrolling?

**Comment by joshangehr** [comment]
@119402282 This is controlled by the [`once`](https://github.com/michalsnik/aos#1-initialize-aos) key in the initialized object.

If you want to control the setting on a per-element basis, use the [`data-aos-once`](https://github.com/michalsnik/aos#2-set-animation-using-data-aos-attribute) attribute on the element itself.
