### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by ManagerCat** [michalsnik/aos#607]
## This is:

- Bug

## Specifications

  - AOS version: 2.3.1
  - OS: MacOS
  - Browser: Google Chrome

## Expected Behavior
Div should display.

## Actual Behavior
Recieved error: ```aos.js:1 Uncaught TypeError: Cannot read property 'setAttribute' of null
    at Object.A [as init] (aos.js:1)
    at (index):22``` causing divs to not display. Index:22 is AOS:init()

## Steps to Reproduce the Problem

1. Run AOS:init()

**Comment by ManagerCat** [comment]
Here is the pen: https://codepen.io/ManagerCat/pen/bGpEQMN

**Comment by terrencechambers** [comment]
I have the same problem and using the CDN urls as well. I tried downloading the files and use that but the same error.

**Comment by terrencechambers** [comment]
> Here is the pen: https://codepen.io/ManagerCat/pen/bGpEQMN

Move this below your elements that get created. Put it above your  `</body>`
```
<script>
    AOS.init();
  </script>
 </body>
```

**Comment by ManagerCat** [comment]
Ok
