### ISSUE TITLE
Custom animation using aos

### ISSUE THREAD

**Issue by rahuljha12527** [michalsnik/aos#620]
Hi i an using custom animation using data-aos attribute but it not work on scrolling ?

`.classFile {
  position: absolute;
  top: 5%;
  right: 10%;

  .bar1,
  .bar2,
  .bar3 {
    width: 35px;
    height: 5px;
    background-color: #333;
    margin: 10px 0;
  }
}
@keyframes fadeInLeftBig {
  0% {
    transform: translateX(-2000px);
  }

  100% {
    transform: translateX(0);
  }
}

@keyframes changePosition {
  from {
    /* transform:translateX(0px)  */
    margin-left: 0%;
   
  }
  to {
    /* transform: translateX(100px); */
    margin-left: 90%;
   
  }
}

[data-aos="example-anim1"] {
  animation-name: changePosititon, fadeInLeftBig;
  animation-duration: 1s;
  animation-iteration-count: 1;
  /* animation-direction: alternate; */
}

[data-aos="example-anim2"] {
  animation-name: changePosititon, fadeInLeftBig;
  animation-duration: 2s;
  animation-iteration-count: 1;
  /* animation-direction: alternate; */
}
[data-aos="example-anim3"] {
  animation-name: changePosititon, fadeInLeftBig;
  animation-duration: 3s;
  animation-iteration-count: 1;
  /* animation-direction: alternate; */
}
`
`.classFile {
  position: absolute;
  top: 5%;
  right: 10%;

  .bar1,
  .bar2,
  .bar3 {
    width: 35px;
    height: 5px;
    background-color: #333;
    margin: 10px 0;
  }
}
@keyframes fadeInLeftBig {
  0% {
    transform: translateX(-2000px);
  }

  100% {
    transform: translateX(0);
  }
}

@keyframes changePosition {
  from {
    /* transform:translateX(0px)  */
    margin-left: 0%;
   
  }
  to {
    /* transform: translateX(100px); */
    margin-left: 90%;
   
  }
}

[data-aos="example-anim1"] {
  animation-name: changePosititon, fadeInLeftBig;
  animation-duration: 1s;
  animation-iteration-count: 1;
  /* animation-direction: alternate; */
}

[data-aos="example-anim2"] {
  animation-name: changePosititon, fadeInLeftBig;
  animation-duration: 2s;
  animation-iteration-count: 1;
  /* animation-direction: alternate; */
}
[data-aos="example-anim3"] {
  animation-name: changePosititon, fadeInLeftBig;
  animation-duration: 3s;
  animation-iteration-count: 1;
  /* animation-direction: alternate; */
}
`

please see my code it not work?

**Comment by rahuljha12527** [comment]
when I am using aos-animate then it work correctly..

**Comment by mobiusint** [comment]
hi there, how did you get it to work?
