### ISSUE TITLE
AOS stops working in the middle of the interface

### ISSUE THREAD

**Issue by tmwebwizard** [michalsnik/aos#628]
AOS works on my home page entirely:

https://tanjamedic.com

On the project page, AOS works but stops animating in the middle:

https://tanjamedic.com/project1

Does anyone have any suggestions why this is occurring and how to fix it?

I followed the instructions on this page when implementing:

https://github.com/michalsnik/aos

## This is:
- Question

## Specifications

  - OS: Windows 10
  - Browser: Google Chrome and Mozilla Firefox

## Expected Behavior
animations when scrolling down - animations should stop when scrolling up

## Actual Behavior
animations start and then stop in the middle

## Steps to Reproduce the Problem

1. Go to https://tanjamedic.com/project1
2. Start scrolling down

**Comment by ronca85** [comment]
@tmwebwizard i believe you need to wait for the whole page (including iframes) to load before executing aos init. when i'm in the lower part of the page and i hit refresh the animations are triggering but parts of the page are still being loaded. this changes the page height and page offsets which might be the reason why some animations appear to trigger late or not at all.
i don't think you can pause the animation once it was triggered. maybe only repeat the animation every time the animated section comes into view.

**Comment by tmwebwizard** [comment]
@ronca85 Thank you. I'll start experimenting now to see what's causing the issue.

**Comment by tmwebwizard** [comment]
So this is the page with the unminified code and without defer image load script:

https://tanjamedic.com/project1_unminified_nodeffer

All animations activate in view. 

This is the page with the minified code and without defer image load script:

https://tanjamedic.com/project1_minified

Animations activate on time, so it seems that the defer image load script is causing issues with animations.

**Comment by tmwebwizard** [comment]
@ronca85 

This simple solution worked for me. Thank you @Aziz-JH

So I kept the defer image load script and added this small script. 

"I got the same problem currently with <img> and the loading="lazy" attribute.

This fix works fine for me after AOS.init():"

```
document.querySelectorAll('img')
    .forEach((img) =>
        img.addEventListener('load', () =>
            AOS.refresh()
        )
    );
```
