### ISSUE TITLE
Pseudo element ::before overlapping when hover

### ISSUE THREAD

**Issue by dariomgonzalez** [michalsnik/aos#632]
I have the ::before psudo element before another div element, but when i hover the main div, the other overlaps and i want it to stay behind.

I was playing around with z-index and I can't make it work.

this is my code:

HTML:

`<div class="box"></div>`

CSS:

.box {
    width: 250px;
    height: 250px;
    background: rgb(255, 0, 0);
    position: relative;
    transition:.3s;
}

.box::before {
    content:'';
    display: block;
    position: absolute;
    width: 100%;
    height: 100%;
    top:5%;
    left:5%;
    background: #000;
    z-index: -1;
}

.box:hover {
    transform: scale(1.1);
}

Your help will be very helpful to me.

This is the url: https://unruffled-poincare-439988.netlify.app/

**Comment by awcoetzer** [comment]
Hi, I started facing a similar issue as of lately, did you ever find an answer as to why this happens?
