### ISSUE TITLE
slide animation is not working properly

### ISSUE THREAD

**Issue by YashDubeyOfficial** [michalsnik/aos#638]
## This is:

- Bug
- Feature request

## Specifications

  - AOS version:  aos@next 
  - OS: windows
  - Browser: chrome 86

## Expected Behavior

 I used ```data-aos="slide-up"``` but the transition needs to be smooth.

 
## Actual Behavior

 For eg:-  I added all slide animation on a div and saved it but while scrolling the div slides in with not so smooth transition 
 In other words, the div first stuck from the starting point of the animation and then comes back to its original position 

## Steps to Reproduce the Problem

0.use bootstrap
1.add div 
2.then add data-aos="slide-up"
3.save it and see the animation on the browser

## Detailed Description

 <div class="col-lg-4 col-md-6" data-aos="slide-up">
## Possible Solution

I don't know how to fix this but perhaps there is some issue with the starting point of the animation or DOM or opacity while starting...

**Comment by CofeeDev** [comment]
try:

html, body{
   display: block;
   margin: 0px;
   padding: 0px;
   overflow-x: hidden;
   width: 100%;
}

**Comment by paulvladmuresan** [comment]
This plugin in seems to be perfect, You create your website, you're happy with your result then you discover you forgot to add overflow-x: hidden; no problem! you add it and then you realise that the creator of the plugg-in never actually tought about this little detail. IS NOT WOOOOOORKING ! Don't rely on this plugg-in is not working properly and you will be disappointed, nobody here around who claims they solve it actually did i tried every solution around here nothing works.  OVERFLOW-X and AOS        D O N ' T      W O R K !

**Comment by YashDubeyOfficial** [comment]
SOLVED
