### ISSUE TITLE
AOS generates a horizontal scroll bar 

### ISSUE THREAD

**Issue by CofeeDev** [michalsnik/aos#640]
![Capture](https://user-images.githubusercontent.com/71831342/99599312-7901d900-29d1-11eb-9fad-f7ce7127c7e7.PNG)

## This is:

- Feature request

## Specifications

  - AOS version: aos@next
  - OS: windows
  - Browser: chrome 86

## Steps to Reproduce the Problem

1.use data-aos = "slide-left" on an element which applies a margin-right

## Possible Solution

I don't know how to solve it but I suppose, it is because of the margins that I apply to the elements

**Comment by mathiasribeiro** [comment]
I'm with the same problem in my website.

**Comment by mathiasribeiro** [comment]
I'm with the same problem in my website.

It's because of the fade left, don't use the fade left for a while.

**Comment by Casper64** [comment]
You could use overflow-x: hidden on the container in which the horizontal scrollbar appears. Depends of course if you already have horizontal scrolling.

**Comment by Mitesh13** [comment]
Use overflow-x:hidden on immediate parent element. Also, do not put overflow-x: hidden on root element as it will stop the scroll event listener and other aos animations will not work.

**Comment by CofeeDev** [comment]
> Puede usar overflow-x: hidden en el contenedor en el que aparece la barra de desplazamiento horizontal. Por supuesto, depende de si ya dispone de desplazamiento horizontal.

Thanks

**Comment by jubaer-hossen** [comment]
in my case overflow-x hidden not work

**Comment by jubaer-hossen** [comment]
in my case overflow-x hidden not work

**Comment by jubaer-hossen** [comment]
in my case overflow-x hidden not work
