### ISSUE TITLE
Is it possible to set an iteration count for my animation?

### ISSUE THREAD

**Issue by kaitlynchristensen** [michalsnik/aos#68]
I want my animation to run a number of times rather than just once, but I can't find a place where this is done in all of the demos. Is this possible?

**Comment by kaitlynchristensen** [comment]
I figured out a way around this! Looks like aos attaches the class 'aos-animate' to the element when it's in view, and I'm able to apply a regular css animation to my element when it has that class. Works just the way I was hoping.

**Comment by michalsnik** [comment]
Hey @kaitlynchristensen. Imo it's not hacky, my intent while doing this plugin was to make it easy for anyone to create own animations and play with existing ones. Looks like you did what I was hoping the community will do! :) by default I provide only basic animations, and if you need anything unusual you can write it on your own not worrying about the logic.
