### ISSUE TITLE
how to run AOS animation on div scrollbar not body or browser scrollbar?

### ISSUE THREAD

**Issue by Northout-Salman** [michalsnik/aos#69]
Hey Michalsnik,
http://northout-dev.us-east-1.elasticbeanstalk.com/wemod-site/pro.html
this is the website we're working. aos animation was working fine untill i've disable body scroll. for some reasons i have to disable body/html scrollbar and make inside div (.wrapper) scrollable. it is not working on page loads, it starts working when we resize browser window.
my question is 
how can we make aos scrolling work on any div's scrollbar rather than default browser scrollbar

**Comment by QuentinNolan** [comment]
This was already answered in #9 and #15 
This is currently not possible but I hope this feature will be added in a future release.

**Comment by Northout-Salman** [comment]
Hey QuentinNolan,
Thankyou for your quick reply. any other library like this which can work with div scrollbar. please let me know.
thanks.

**Comment by michalsnik** [comment]
Thanks for replying in this issue @QuentinNolan. Like it's been already answered aos does not provide this feature yet. It's something that I might add in future releases.

@Northout-Salman you can check `scroll reveal`, I think they may have this feature already.

**Comment by tipsclick** [comment]
is it fixed or not? because i am facing same issue. if yes please send me code

**Comment by bootexe** [comment]
you can use $(<selector>).on('scroll',AOS.refreshHard);
