### ISSUE TITLE
The debugger keeps showing "Uncaught TypeError".

### ISSUE THREAD

**Issue by u00337018** [michalsnik/aos#691]
## This is:

- Question

## Specifications

  - AOS version:  aos master and 3.0.0-beta.6
  - OS: Win 10
  - Browser: Chrome and FireFox

## Expected Behavior

Fade up and show the items

## Actual Behavior

sorry I am Taiwanese. I'm not good at English.
Thank you for providing this.I really appreciate it.

1. - It doesn't show up and animation doesn't work. 
2. - The browser debug shows "Uncaught TypeError: document.querySelector(...) is null"

## Steps to Reproduce the Problem

1.I put  localhost links and jq in files. Though the item came out but the scroll function not working and didn't show the transition effect.
![圖片](https://user-images.githubusercontent.com/86407602/123245024-07fe4300-d517-11eb-8f25-0b5b6688e27a.png)
![圖片](https://user-images.githubusercontent.com/86407602/123244828-d8e7d180-d516-11eb-9857-4a4446a4020c.png)

2.So I put the cdn source but the animation didn't come out. It stop in this situation.
![圖片](https://user-images.githubusercontent.com/86407602/123244764-cb324c00-d516-11eb-9195-fcb4e6cf6a32.png)![圖片](https://user-images.githubusercontent.com/86407602/123245513-7fcc6d80-d517-11eb-92e5-f8ba8fdb03b2.png)

```
[data-aos^=fade][data-aos^=fade] {
    opacity: 0;
    transition-property: opacity,transform;
}
```

3.I checked out the Debugger, There are some errors.

![圖片](https://user-images.githubusercontent.com/86407602/123244648-b5248b80-d516-11eb-8dee-c81a2350f60b.png)

**Comment by laneparton** [comment]
Are you running `AOS.Init` after the script tag?

Have you tried following these [instructions](https://github.com/michalsnik/aos#basic) where you:

1. Add styles in `<head>`
2. Add script right before closing `</body>` tag, and initialize AOS

**Comment by u00337018** [comment]
> Are you running `AOS.Init` after the script tag?
> 
> Have you tried following these [instructions](https://github.com/michalsnik/aos#basic) where you:
> 
> 1. Add styles in `<head>`
> 2. Add script right before closing `</body>` tag, and initialize AOS

**Comment by u00337018** [comment]
Thank you. I found the problem.
