### ISSUE TITLE
AOS with NextJS - Document is not defined

### ISSUE THREAD

**Issue by trupakufi** [michalsnik/aos#709]
- BUG

## Specifications

  - AOS version: 3.0
  - OS: Windows 10
  - Browser: Google Chrome

## Document is Not Defined
So, I throug that the aos work normaly with nextjs, but I met with a problem in document, my eslint says that document is not defined

![Captura de ecrã de 2021-08-22 21-38-00](https://user-images.githubusercontent.com/72455038/130369384-5559b9eb-dede-49dc-945a-764a3b29c7f3.png)

And in the browser a see this.!

![Captura de ecrã de 2021-08-22 21-40-50](https://user-images.githubusercontent.com/72455038/130369424-39e9fe03-6644-461f-9f15-c18dd9f5ee12.png)

I try catch the bug using dynamic import but nothing instead.!

**Comment by GeniusHawlah** [comment]
I am facing the same problem right now. Were you able to solve it?

**Comment by aman-maharshi** [comment]
Calling the init() inside useEffect worked for me

```javascript
useEffect(() => {
        AOS.init()
}, [])
```

**Comment by Princekrampah** [comment]
``` javascript
import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/globals.css';
import '../styles/header.css';
import Layout from "../components/Layout";
import { useEffect } from "react";

import AOS from 'aos';
import 'aos/dist/aos.css'; 




function MyApp({ Component, pageProps }) {
  
  useEffect(() => {
    AOS.init({
      startEvent: 'DOMContentLoaded', 
      initClassName: 'aos-init',
      animatedClassName: 'aos-animate'
    });
  }, [])

  return (
    <>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}

export default MyApp
```

**Comment by nicefella** [comment]
> Calling the init() inside useEffect worked for me
> 
> ```js
> useEffect(() => {
>         AOS.init()
> }, [])
> ```

You are an amazingly maniac problem solver! Thank you!

**Comment by htamagnus** [comment]
I try:

**Comment by htamagnus** [comment]
I try: 
`import { useEffect } from "react";
import AOS from 'aos';
import 'aos/dist/aos.css';

useEffect(() => {
  AOS.init({
    startEvent: 'DOMContentLoaded', 
    initClassName: 'aos-init',
    animatedClassName: 'aos-animate'
  });
}, [])`

and now I have this error:
`TypeError: Cannot read properties of null (reading 'useEffect')

`

**Comment by apophis51** [comment]
> Calling the init() inside useEffect worked for me
> 
> ```js
> useEffect(() => {
>         AOS.init()
> }, [])
> ```

YOU ARE A BRO!
