### ISSUE TITLE
Transitions start happening immediately after console is brought up

### ISSUE THREAD

**Issue by chanrt** [michalsnik/aos#725]
On my website: https://visualize-it.github.io/, I have implemented AOS transitions almost everywhere.

The transitions are not seen immediately after the page loads. They only happen after some time (10 - 15 seconds)

However I noticed this peculiar bug wherein if you bring up the console on firefox (by pressing Ctrl-Shift-K) immediately after the page loads, transitions start taking place all of a sudden and there is no waiting period involved

Why does this happen?

**Comment by Air-Sidney** [comment]
I think you need run AOS init after DOMContentLoaded, and div.container is displayed
