### ISSUE TITLE
Angular 12 AOS is loading on page load not on Scroll

### ISSUE THREAD

**Issue by BogdanPetrovic5** [michalsnik/aos#727]
AOS is loading on page load and not on Scroll, any solutions?

**Comment by BogdanPetrovic5** [comment]
apparently I had Whole body and html tags in component's html so it hasn't worked

**Comment by EdoriAtiri** [comment]
hey! What does this mean "apparently I had Whole body and html tags in component's html so it hasn't worked". How were you able to solve this.

**Comment by BugProg** [comment]
Hi ! @EdoriAtiri 

Have you tried to import AOS in your app.component.ts like this: `import * as AOS from 'aos';`

And then in `ngOnInit` add :
```ts
      AOS.init({
        once: true
      });
```
