### ISSUE TITLE
Additional space on right side on all mobile devices

### ISSUE THREAD

**Issue by jmich41** [michalsnik/aos#73]
Probably bug is connected with `data-aos="fade-left"`
Please open: http://michalsnik.github.io/aos/
and in chrome inspect settings change to iPad or any mobile device on right side is additional space, till you display all "fade-left" effects

**Comment by michalsnik** [comment]
You have add `overflow-x: hidden;` or `overflow: hidden` on some elements to prevent them to enlarge your container in strange way. I added `overflow: hidden` to `.section` on demo and it works fine. That's one of downsides using horizontal translate on animated elements :) I hope this answers your issue.

**Comment by ClauGarfiasMx** [comment]
thank you very much @michalsnik !!
