### ISSUE TITLE
AOS ReactJs White Space on Mobile

### ISSUE THREAD

**Issue by fleecyeth** [michalsnik/aos#731]
- Question
I use AOS to animate my react website and when viewing my site on mobile some white space appears on the right of the screen.

I've seen the solution like add 
html, body 
{
overflow-x: hidden;
}

But the problem is that I use position: sticky on my navbar. These two css properties are not compatible, that is why my navbar disappears on scroll.
Is there some other solution to this problem? 
Thank u for your answers :)

**Comment by LinuxKunaL** [comment]
but is working one problem

**Comment by Shaman-1975** [comment]
> 

I had the same issue.
Use another div as html, body to solve this.

E.g.:
HTML Structure:`
-html
  -body
    -navbar/navbar
    -main/main
  /body
/html
`
Then put the following on the main div in CSS:
`main {
    position: relative;
    overflow-x: hidden;
}`

That worked for me!
