### ISSUE TITLE
Not animate elements already visible

### ISSUE THREAD

**Issue by nathanaelphilip** [michalsnik/aos#74]
Would it be hard to add an option, or is there something I can do to prevent elements which are already on the screen from not animating it. Because of difference screen sizes, it’s not always easy to determine which will be on screen before the JS fires.

**Comment by digitall-it** [comment]
I second that request, I played with various offset settings but did not manage to have all initial elements in viewport stay put and indeed animate the others only if they get into view.

**Comment by michalsnik** [comment]
It sounds like an interesting idea. It might however be a bit tricky but I think doable and most of the work will be in styles, though I think it would be a major change.
The only way I see for it right now is that we only show those elements without animating, but it will happen at the same time as animation would anyway. Are you aware of that and you only what to prevent from firing animation?

**Comment by michalsnik** [comment]
I just look at it once again. And I think your problem @digitall-it was actually regarding too early `AOS.initialization`, probably calling `AOS.refresh()` on window load event would solve your problem. About not animating elements that are already in viewport - it's not going to be solved I'm afraid - I don't want AOS elements to `flash` after initialization.
