### ISSUE TITLE
Help me I have a problem

### ISSUE THREAD

**Issue by Archetipo95** [michalsnik/aos#75]
I'm testing AOS on this site: https://archetipo95.github.io/Material.Design.Site/
As you can see animations are not working and I don't know why.

![senza nome0](https://cloud.githubusercontent.com/assets/11798239/20227466/ad582d2c-a84c-11e6-8896-8ff282fc73ed.png)

![senza nome](https://cloud.githubusercontent.com/assets/11798239/20227465/ad5713ec-a84c-11e6-8ae1-52595a0d7436.png)

Can you help me, sorry I'm new to web design maybe it's just my fault.

**Comment by Archetipo95** [comment]
This is an other example: http://codepen.io/anon/pen/WowrJp
I can't animate even this.

**Comment by Archetipo95** [comment]
<script src="js/aos.js"></script>
    <script>
      AOS.init({
        easing: 'ease-in-out-sine'
      });
    </script>

Solved my problem

**Comment by sharden** [comment]
**I had a similar issue but was able to resolve. If you're reading this and used the provided CDN's please read.**

Crack open inspect element in your browser and do the following: 

1. Check the DOM element where you added data-aos="blah" and scroll. If JS is loaded you'll see the class names change dynamically. If that works, your JS file is good but your css may be missing.

2. Select Sources to verify 'cdn.rawgit.com/michalsnik/aos/2.*(version you're on) is there and loads both aos.js and aos.css. My css didn't load even using the provided CDN so I manual placed the css file.

Hope this helps.
