### ISSUE TITLE
Mutation events deprecated

### ISSUE THREAD

**Issue by Archetipo95** [michalsnik/aos#76]
Firefox is telling me that this Mutation Event is deprecated and to use MutationObserver. If this can help someone.

aos.js 1:2238

**Comment by michalsnik** [comment]
Hi, thanks for heads up. I'm aware of that and will ship an update soon.

**Comment by jonatasu** [comment]
Hello, any news about this issue?

**Comment by Tusko** [comment]
+1

**Comment by depositado** [comment]
+1 ....

**Comment by demomohawk** [comment]
+1

**Comment by arzurchris** [comment]
+1
