### ISSUE TITLE
Disable some animation on mobile

### ISSUE THREAD

**Issue by Archetipo95** [michalsnik/aos#77]
There are some animations that are messing with my site but others are working well.
Is it possible to disable just some animation on mobile not all?

**Comment by kasperientje** [comment]
It's in the docs. Use the option `disable` on initialization. Set it to 'mobile' or use `window.innerWidth` like below to disable it on certain screen sizes.

```
AOS.init({
  disable: window.innerWidth < 768,
});
```

**Comment by michalsnik** [comment]
No, you can only disable all animations. If you want something more custom you can always override AOS styles with your own :)
