### ISSUE TITLE
Fix <link> tag in the docs

### ISSUE THREAD

**Issue by pietrofxq** [michalsnik/aos#79]
In the docs, the css CND has a wrong "rel" value:

<link href="https://cdn.rawgit.com/michalsnik/aos/2.0.4/dist/aos.css" rel="stylsheet">

"stylsheet" needs to be changed to "stylesheet" - a lot of people are reporting that the library isn't working because of this.

**Comment by michalsnik** [comment]
Yeah, thanks @pietrofxq for pointing this. I had to miss this one. Fixed!
