### ISSUE TITLE
how do i use aos in next js?

### ISSUE THREAD

**Issue by aaronteamAAR** [michalsnik/aos#799]
## This is:

- Bug
- Feature request
- Question
- Idea

## Specifications

  - AOS version:
  - OS:
  - Browser:

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by HNTQ** [comment]
Hi, 

To use AOS with Nextjs, it's pretty easy: 

Install dependency: 
```
yarn add aos
```

then in your _app file add this lines: 
```js
import AOS from "aos";
import "aos/dist/aos.css";
```
and in your app component: 
```js
  useEffect(() => {
    AOS.init();
  }, []);
```

and now it's work you can use it:

```html
<div data-aos="fade-up"></div>
```

**Comment by aaronteamAAR** [comment]
thanks
