### ISSUE TITLE
disable: tablet causes problems on laptop & desktop

### ISSUE THREAD

**Issue by adskinner** [michalsnik/aos#80]
Hi! Loving the AOS scroll library! The only issue I'm having is that when I disable the animation on 'tablet' it disables it on window width _and_ device width. On my ipad, it looks great--no animations but the text and images appear. But on my laptop, if I resize my window to under 1024px, none of the text or images appear that have animations (so kind of a blank website). Also I checked this problem out on Safari, Chrome & Firefox -- all have the same error.
Do you know what may be causing this/do you have a fix for this? Thanks!

**Comment by michalsnik** [comment]
Hi @adskinner, I tried to replicate this issue, but with no luck. Everything seems to be working fine. What version of AOS are you using?

**Comment by michalsnik** [comment]
I didn't receive an answer so I assume it's working fine. Feel free to reopen this issue if the problem still exists.
