### ISSUE TITLE
AOS needs to be updated to maintain health！

### ISSUE THREAD

**Issue by SeaEpoch** [michalsnik/aos#825]
## This is:

- Bug[warning]

## Specifications

  - AOS version:2.3.4
  - OS: WIN 10
  - Browser: EDGE

## Expected Behavior

The browser will not issue any warnings！

## Actual Behavior

The browser has provided the following warning content：
```
aos.js:1  [Deprecation]Listener added for a synchronous 'DOMNodeRemoved' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.
```

## Detailed Description

I suggest updating some functions of Aos.js to maintain the health of Aos.

## Possible Solution

Please consider using `MutationObserver` instead.

**Comment by eaugustine** [comment]
Agreed!

<img width="1153" alt="image" src="https://github.com/michalsnik/aos/assets/3731424/2a0a81d9-3824-4950-afca-77bca8fa9622">

**Comment by frugan-dev** [comment]
I think we should consider switching to this most popular fork https://github.com/ammannbe/simple-aos

**Comment by MushroomScientist** [comment]
@eaugustine @SeaYJ 

The Mutation events references in the js file are replaced by `MutationObserver` in the js file I grabbed from this GitHub repository. I'm also using version 2.3.4 and took the  aos.js from the dist folder. I'm a bit confused for what reasons you get these warning in your console. I do not have the same issues.

![devtool-js](https://github.com/michalsnik/aos/assets/101217903/db37227c-9a6b-4237-9042-e8131f50f826)

**Comment by SeaYJ** [comment]
> @eaugustine @SeaYJ
> 
> The Mutation events references in the js file are replaced by `MutationObserver` in the js file I grabbed from this GitHub repository. I'm also using version 2.3.4 and took the aos.js from the dist folder. I'm a bit confused for what reasons you get these warning in your console. I do not have the same issues.
> 
> ![devtool-js](https://private-user-images.githubusercontent.com/101217903/294166838-db37227c-9a6b-4237-9042-e8131f50f826.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMTc4NDcsIm5iZiI6MTcwNzAxNzU0NywicGF0aCI6Ii8xMDEyMTc5MDMvMjk0MTY2ODM4LWRiMzcyMjdjLTlhNmItNDIzNy05MDQyLWU4MTMxZjUwZjgyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwMzMyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmMzNDRkOWMwZjEwNGNhNjhiYTU0OTIzNTc4NmUxMjVmZTM3YjQ4Mzc5MTZhMDRhZDBlOTE5MWNhZjgyNmMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vr4D9TunUwsqxpIKkGWWro89YSnf6Ac4dzjj8aYcZl4)

Yes, but the issue does exist. I am using the latest version of the EDGE browser, and the operating system is WIN10 22H2.

**Comment by SeaEpoch** [comment]
> @eaugustine @SeaYJ
> 
> The Mutation events references in the js file are replaced by `MutationObserver` in the js file I grabbed from this GitHub repository. I'm also using version 2.3.4 and took the aos.js from the dist folder. I'm a bit confused for what reasons you get these warning in your console. I do not have the same issues.
> 
> ![devtool-js](https://private-user-images.githubusercontent.com/101217903/294166838-db37227c-9a6b-4237-9042-e8131f50f826.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMTg0NDksIm5iZiI6MTcwNzAxODE0OSwicGF0aCI6Ii8xMDEyMTc5MDMvMjk0MTY2ODM4LWRiMzcyMjdjLTlhNmItNDIzNy05MDQyLWU4MTMxZjUwZjgyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwMzQyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Yzg4YTYxYzk5OWJiMTI2Y2U4Y2Y3NTA3MzdkMDBkYjcxMjcxNDMxMTgzMzJhM2Y4OTY3MzU2NzY0NmY0ZDJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JG3QLmwvngMsiK6kILch1Nyodp8Q-7A-zBL1GPeoVto)

太棒了，似乎你是对的

> @eaugustine @SeaYJ
> 
> The Mutation events references in the js file are replaced by `MutationObserver` in the js file I grabbed from this GitHub repository. I'm also using version 2.3.4 and took the aos.js from the dist folder. I'm a bit confused for what reasons you get these warning in your console. I do not have the same issues.
> 
> ![devtool-js](https://private-user-images.githubusercontent.com/101217903/294166838-db37227c-9a6b-4237-9042-e8131f50f826.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMTg0NDksIm5iZiI6MTcwNzAxODE0OSwicGF0aCI6Ii8xMDEyMTc5MDMvMjk0MTY2ODM4LWRiMzcyMjdjLTlhNmItNDIzNy05MDQyLWU4MTMxZjUwZjgyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwMzQyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Yzg4YTYxYzk5OWJiMTI2Y2U4Y2Y3NTA3MzdkMDBkYjcxMjcxNDMxMTgzMzJhM2Y4OTY3MzU2NzY0NmY0ZDJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JG3QLmwvngMsiK6kILch1Nyodp8Q-7A-zBL1GPeoVto)

Great, it seems you're right! Today I tried getting `aos.js` from the `dist` folder as you suggested, and surprisingly, the issue disappeared. I don't recall how I originally obtained the `aos.js` file (it might have been directly downloaded from the npm package link in the README, and the issue could be there), but the file obtained from the GitHub Release Tag for version 2.3.4 indeed doesn't have this problem.

So, it's wise to get AOS from here:
[AOS 2.3.4](https://github.com/michalsnik/aos/releases/tag/v2.3.4)

**Comment by SeaEpoch** [comment]
It is a wise choice to obtain AOS from here: [AOS v2.3.4](https://github.com/michalsnik/aos/releases/tag/v2.3.4). You need to unzip it first and then get `aos.js` from the `dist` folder.

As of February 4, 2024, the issue still persists when obtaining AOS from npm.
