### ISSUE TITLE
AOS.refresh(); recalculate all offsets and positions - Doesnt work

### ISSUE THREAD

**Issue by bele2016** [michalsnik/aos#83]
Hi

Im trying to use the AOS.refresh(); because my website is dynamic and the height of the page often changes, which is an issue for the animation scroll.

Im using a social media feed in my website ->https://www.juicer.io/
which embeds all my facebook and instagram posts. The visitors on my webpage can then click "show more" which expands the height of the page, to show more posts. Thats a small problem for the AOS animation, because it ruins the scroll calculator.

I've been trying to add the AOS refresh and the refreshHard, but it doesn't work. Maybe im not doing it right.

So far I only have this before my </body>
  <script>
    AOS.init();
  </script>

Any solutions?

Thanks :)

**Comment by michalsnik** [comment]
Hey,

In your case `AOS.refresh()` should do the job just fine. It is well known example and it was already battle tested. You have to make sure, you're calling this **after** height of some sections of your page have changed.

I prepared working example with your problem, resolved by using `AOS.refresh()`. Take a look:
http://codepen.io/michalsnik/pen/ENraWZ

**Comment by bele2016** [comment]
Thanks for your answer.
I tried to change the classes, so it was fitting to my classes, but doesn't work. The Juicer platform has its own button. The class is called "juicer-button", so I replaced your class with the one from Juicer. Im missing something. Still trying.

**Comment by bele2016** [comment]
This is how my html looks like:

<div id="wall">
<div id="juicer-platform>JUICER SCRIPT</div></div>

<div id="aos">AOS ANIMATION</div>

Can I call the height of the #wall? How to script that? The Juicer platform has its own button. So the only thing I need is the height.

**Comment by michalsnik** [comment]
Hmm, in that case if they don't provide an event that is being triggered after loading your feed, then you'll have to watch for a height change on that container and when it happens - refresh AOS. It will be hacky though..

Quick working example: http://codepen.io/michalsnik/pen/ENraWZ

**Comment by michalsnik** [comment]
I'm closing this issue now. Feel free to reopen if you still have a problem with this.

**Comment by yogeshwattamwar** [comment]
Hey michalsnik can you tell me how i make aos animation with infinite looping.

**Comment by aminsmartsense** [comment]
I also need aos animation with infinite looping.
