### ISSUE TITLE
AOS just work with first element

### ISSUE THREAD

**Issue by atukilham** [michalsnik/aos#84]
Hi, i've problem with AOS.
i have list element with card item and used data-aos attribute, but just first item working.
others item to be hidden.
any solutions?

(*sorry for my bad english)

**Comment by michalsnik** [comment]
I can't guess what might be wrong. Please prepare codepen that will illustrate your problem and then I'll be able to help you @atukilham :)

**Comment by nileshmahaja** [comment]
I am facing same kind of issue at my end, 

Animation for few elements works fine, but not for all. I tried and inspect issue in browsers developer tool and found that "aos-animate" class does not get applied to those elements.

Any Guess why it is happening?

More facts
- I am using the latest version of aos i.e. 2.1.1
- Entire markup is valid and no closing or opening brackets are missing.
- Elements which are not working are getting "aos-init" class but not "aos-animate"

Many thanks for making this beautiful plugin.

**Comment by michalsnik** [comment]
Hi @nileshmahaja, please try to add:
```
$(window).on('load', function() {
    AOS.refresh();
});
```

It looks like some elements' positions depend on previous elements (most likely images), so you'd probably need to recalculate position of animation's trigger points after all of them finished loading.

Let me know if that helps ;)

**Comment by nileshmahaja** [comment]
Hello Michalsnik,

Thanks for quick help! It worked for me..

**Comment by michalsnik** [comment]
I bet it will work for @atukilham as well. If not - feel free to reopen this issue :)

**Comment by edvinmolla** [comment]
Hi, weirdly I do not have conflicting JS files but It still only animates the landing section only. The refresh snippet didn't work as well.
Also for a certain reason, animations don't get called when I change screen size. Weird.

**Comment by Amounaim** [comment]
> Hello Michalsnik,
> 
> Thanks for quick help! It worked for me..

Hi @nileshmahaja , I hope you doing well , I face the same problem but i did not know **where** to add ```
$(window).on('load', function() {
    AOS.refresh();
});  
```

btw , i have ```
ngOnInit(){
    AOS.init();
    
  }
```
in app.component.ts
