### ISSUE TITLE
AOS Animating each time a user visit to section

### ISSUE THREAD

**Issue by imhamad** [michalsnik/aos#847]
## This is:

- Question

## Expected Behavior

Actually i want to AOS to only animate once a user go through the page and redo the same behaviour only as of when the page reload

## Actual Behavior
At the moment it's doing it everytime we faff through the sections

I hope it's been addressed before, any help on this would be a pleasure!

Cheers,

**Comment by ZuzannaFilipkowska** [comment]
Hi,

set atribute 'once' to true in global config  or add it per animation. It makes animation run only once which seems like your desired behaviour. Check out documentation Everything is described in README: https://github.com/michalsnik/aos

**Comment by imhamad** [comment]
Hey @ZuzannaFilipkowska ,

Really appreciate your take on it, Yes i rattled over the documentation, all is clear there!

Fondest Regards,
H
