### ISSUE TITLE
aos doesn't work when elements are placed in custom container of fixed height

### ISSUE THREAD

**Issue by itaditya** [michalsnik/aos#85]
aos doesn't work when elements are placed in custom scrollable container of fixed height.
Check this pen which I forked from the examples - [Codepen](http://codepen.io/itaditya/pen/bBzRVr)
Notice that only the first element is getting animated but no other element inside .mainPage div is animated on scroll. **I couldn't find any config for defining custom container either.**

**Comment by michalsnik** [comment]
Hi @itaditya,

AOS doesn't work within custom containers. It doesn't have this feature implemented yet, and I can't promise it's something that will be added in near future either..

**Comment by itaditya** [comment]
Ok ..
