### ISSUE TITLE
how to integrate with vue.js

### ISSUE THREAD

**Issue by gantulgan** [michalsnik/aos#87]
I have html page with AOS animation. The page is complete static.
Then I tried to integrated to vue.js to dynamically change some text and html components.
But when add vue,js app then AOS stopped working.
Are there anyone who already figured out how to integrate AOS and VUE together?

**Comment by aozora** [comment]
Hi, I've created a little directive for Vue 2, I'm still working on this but the following code should work:
directives/aos.js:
`
import AOS from 'aos';
export default {
  bind(el, binding, vnode) {
    // add listener
    AOS.init({
      duration: 1200
    });
  },

  // // When the bound element is inserted into the DOM...
  // inserted(el, binding) {
  // },

  update(el, binding) {
    AOS.refresh();
  },

  unbind(el, binding) {
    // window.stroll.unbind(el);
  }
};
`

to use it, add these line in main.js:

`
import aos from  './directives/aos';
Vue.directive('aos', aos);
`

**Comment by aozora** [comment]
forgot, to use the directive apply it on the element container of the ones to be animated:
```<div class="container" v-aos>```

**Comment by nucamoz** [comment]
I've added this code, but error shows up:

```
Vue.js error

Error: Module build failed: SyntaxError: Unexpected token, expected , (16:2)

  14 |   }
  15 | 
> 16 |   bind(el, binding, vnode) {
     |   ^
  17 |   // add listener
  18 |   AOS.init({
  19 |   duration: 1200

    at Object.<anonymous> (__vue_ssr_bundle__:2077:7)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at Object.module.exports.module.exports.render._vm (__vue_ssr_bundle__:3817:3)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at Object.module.exports.Object.defineProperty.value (__vue_ssr_bundle__:1616:5)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at Object.<anonymous> (__vue_ssr_bundle__:1117:69)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at Object.<anonymous> (__vue_ssr_bundle__:4230:65)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
```

Using .vue components. So I install AOS from npm then added that code in script tag of .vue:

```
  bind(el, binding, vnode) {
  // add listener
  AOS.init({
  duration: 1200
  });
  },

  // // When the bound element is inserted into the DOM...
  // inserted(el, binding) {
  // },

  update(el, binding) {
  AOS.refresh();
  },

  unbind(el, binding) {
  // window.stroll.unbind(el);
  }
```
Doesn't work.

**Comment by nucamoz** [comment]
That code doesn't work. Using .vue components.

```
Vue.js error

ReferenceError: window is not defined
    at Object.defineProperty.value (/home/zman/pkr-crdrz/node_modules/aos/dist/aos.js:1:5429)
    at t (/home/zman/pkr-crdrz/node_modules/aos/dist/aos.js:1:378)
    at Object.n (/home/zman/pkr-crdrz/node_modules/aos/dist/aos.js:1:771)
    at t (/home/zman/pkr-crdrz/node_modules/aos/dist/aos.js:1:378)
    at e.__esModule.default (/home/zman/pkr-crdrz/node_modules/aos/dist/aos.js:1:470)
    at /home/zman/pkr-crdrz/node_modules/aos/dist/aos.js:1:475
    at o (/home/zman/pkr-crdrz/node_modules/aos/dist/aos.js:1:143)
    at Object.<anonymous> (/home/zman/pkr-crdrz/node_modules/aos/dist/aos.js:1:249)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

Installed from npm, then add the code above to script tag in .vue

**Comment by molysama** [comment]
Doesn't work

**Comment by michalsnik** [comment]
This works for me:
```
// main.js
import AOS from 'aos'
import 'aos/dist/aos.css'

new Vue({
  el: '#app',
  created () {
    AOS.init()
  },
  render: h => h(App)
})
```

**Comment by molysama** [comment]
oh, It works when I import css. Thank you!

**Comment by codejunkers1** [comment]
// main.js
import 'aos/dist/aos.css'

//App.vue
import AOS from 'aos'
export default {
created ( ) {
AOS.init()
}
}

**Comment by pvenableh** [comment]
Any advice on how to use this with nuxt.js as a plugin?  I can't seem to get it to work.

**Comment by samrose3** [comment]
@pvenableh I had to import AOS after mounting so it had access to the `window`. Did this using lazy loading.

```js
async mounted() {
  const AOS = await import('aos');
  AOS.init();
}
```

or without async/await

```js
mounted() {
  import('aos').then(AOS => AOS.init());
}

**Comment by saeedhemmati** [comment]
Sorry, I don't know what you can do for your problem...    On Saturday, May 26, 2018, 10:33:19 PM GMT+4:30, Sam Rose <notifications@github.com> wrote:  
 
 
@pvenableh I had to import AOS after mounting so it had access to the window. Did this using lazy loading.
async mounted() {
  const AOS = await import('aos');
  AOS.init();
}
or without async/await
mounted() {
  import('aos').then(AOS => AOS.init());
}

**Comment by Musbell** [comment]
@samrose3  Thanks. You safe my day :+1:

**Comment by PrimozRome** [comment]
@samrose3 I am also trying to use with nuxt.js. Tried importing AOS in the mounted method of my component, just like you, but the items with `data-aos="fade"` are not visible. 

My code in the myComponent.vue:

```
import 'aos/dist/aos.css'
...
 mounted() {
    import('aos').then(AOS => AOS.init())
  }

```
Any idea?

**Comment by sam-b-rose** [comment]
@PrimozRome my initial thoughts are that they are starting hidden and the fade in animation is never being triggered, causing them to stay hidden.

I would check which element is being scrolled on your page and ensure AOS is watching the correct scrolling container. I had this issue as well, just had to modify my AOS configuration

**Comment by qky1412** [comment]
What if I want disable AOS in some conditions? Currently using 'disable: true' will cause items stay hidden, 'cause the css is imported before, I dont't want control the 'data-aos' attribute or append a new class in global.

**Comment by Tes3awy** [comment]
I'd like to recommend that you also add 
```js
AOS.refresh();
```
within the `destroyed` life-cycle hook.

**Comment by dekadentno** [comment]
> Any advice on how to use this with nuxt.js as a plugin? I can't seem to get it to work.

Making it work with Nuxt:

1. make a js file in your ```plugins``` directory with the following content:
```js
// aos.js
import Vue from 'vue';
import AOS from 'aos';
import 'aos/dist/aos.css';

Vue.use(
  AOS.init({
      // add your settings here
  })
);
```

2. include the file from step 1 in ```nuxt.config.js```in the ```plugins```section:
```js
  plugins: [
    '~/plugins/aos.js',
  ],
```

**Comment by MuhaddiMu** [comment]
@dekadentno  Thanks for sharing! That's working !!

**Comment by fliprubin** [comment]
@dekadentno's code is a good start, but it can break vue if you use anything other than `false` for the `disable` option. This is because when AOS is disabled, the `AOS.init` function returns `undefined`, and a vue plugin can't be undefined. 

I also found I needed to use `if (process.client)` to prevent AOS from trying to do document queries on the node side.

Here's my modified version:
```js
// aos.js
import Vue from 'vue';
import AOS from 'aos';
import 'aos/dist/aos.css';

const aosPlugin = {
  install: () => {
    AOS.init({
      // add your settings here
    })
  },
}

if (process.client) {
  Vue.use(aosPlugin);
}
```

For `nuxt.config.js`, it should be the same. If that doesn't work, you may want to try this instead:

```js
  plugins: [
    {
      src: '~/plugins/aos.js',
      mode: 'client',
    },
  ],
```
Hope this helps future lurkers!

**Comment by MrSunshyne** [comment]
@fliprubin 

>Hope this helps future lurkers!

It absolutely did. Thanks

**Comment by purrplingcat** [comment]
The animation can be reset on an element which is animated when vue component updated. This caused deffect the element hide. I solved it with init Vue plugin (in Nuxt) in this way:

```js
// ~/plugins/aos.js
import Vue from 'vue'
import AOS from 'aos'
import 'aos/dist/aos.css' // If you need load compiled AOS css here in plugin

class AosPlugin {
  config = {
    // Your AOS config here
  }

  install(Vue) {
    AOS.init(this.config)

    Vue.mixin({
      updated() {
        this.$nextTick(function () {
          AOS.refreshHard() // This is needed to avoid the un-animate aos effect
        })
      }
    })
  }
}

Vue.use(new AosPlugin())
```

You can probably use it in vanilla vue project, just register this plugin with `Vue.use()`.

**Comment by MrSunshyne** [comment]
@purrplingcat would you have a solution for this problem in Nuxt by any chance as you seem to have been using aos with nuxt? 
see [this](https://github.com/michalsnik/aos/issues/336#issuecomment-583859140) and all replies that follow. 

I haven't been able to get it working till now. I tried the code snippet in your reply above, but i'm getting the same result. i.e when the site is generated, aos stops working.

will appreciate any hint. thanks !

**Comment by LindaOjo** [comment]
//index.html

```
  <head>
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css"/>
  </head>
  <body>
        <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
        <script> AOS.init(); </script>
  </body>

```
I  integrated AOS in Gridsome by adding the script and CDN above in my index.html. It worked for me

**Comment by simondoescode** [comment]
I am having an issue where the AOS event is triggered twice. Once on the page init and then again once the page has been fully loaded. This only happens on the first load.

**Comment by decypherr** [comment]
any solution for vue3???

**Comment by megasanjay** [comment]
> any solution for vue3???

You could just do it the same way. This is what I'm using:

```javascript 
//main.js
import AOS from "aos";
import "aos/dist/aos.css";

const app = createApp(App);

app.use({
  install: () => {
    AOS.init({ duration: 500, anchorPlacement: "top-center" });
  },
});

app.mount("#app");
```

**Comment by Syahruzein** [comment]
> The animation can be reset on an element which is animated when vue component updated. This caused deffect the element hide. I solved it with init Vue plugin (in Nuxt) in this way:
> 
> ```js
> // ~/plugins/aos.js
> import Vue from 'vue'
> import AOS from 'aos'
> import 'aos/dist/aos.css' // If you need load compiled AOS css here in plugin
> 
> class AosPlugin {
>   config = {
>     // Your AOS config here
>   }
> 
>   install(Vue) {
>     AOS.init(this.config)
> 
>     Vue.mixin({
>       updated() {
>         this.$nextTick(function () {
>           AOS.refreshHard() // This is needed to avoid the un-animate aos effect
>         })
>       }
>     })
>   }
> }
> 
> Vue.use(new AosPlugin())
> ```
> 
> You can probably use it in vanilla vue project, just register this plugin with `Vue.use()`.

thanks a lot, this worked in my case.
