### ISSUE TITLE
Refresh Animation on Bootstrap Carousel

### ISSUE THREAD

**Issue by helmiaditya14** [michalsnik/aos#88]
I tried to have some text animations every time the carousel finish sliding, but it seems they are animated on page load, so only first slide animated.

Is there a way to refresh the animation inside the Bootstrap's Carousel Jquery events? I tried to put `AOS.refresh();` inside it, but doesn't seem to work.

Any ideas what I did wrong?

Thank you.

**Comment by michalsnik** [comment]
Hi, sorry for the delay in response.

I'm afraid it's out of the scope of this library..
