### ISSUE TITLE
Not working inside a popup

### ISSUE THREAD

**Issue by Warface** [michalsnik/aos#9]
Seems like many test I've done before testing your code that the scroll detection inside a div (like a popup) is not working. So the script isn't either.

Here's a little fiddle to represent what I'm talking about.

https://jsfiddle.net/Warface/tgv0rmj2/

As you can see, there's 5 element inside that popup and only the first 3 are visible, the next ones stay hidden since the script don't detect the scroll inside that popup. Any clue on how to fix this?

**Comment by michalsnik** [comment]
Hi @Warface,
Currently AOS doesn't support scrolling inside other element than window.

And there seems to be a problem with JSFiddle -> it doesn't fire DOMContentLoaded event AOS isn't initialized.
I pasted you're code on codepen and it works fine: http://codepen.io/michalsnik/pen/PzPLGq
But you had to eliminate some styles, as right now it scrolls content inside window, not popup.

However it sounds like an interesting feature. For now the only way to provide AOS inside popup is to put popup's content in iframe ;/
