### ISSUE TITLE
Fade Out

### ISSUE THREAD

**Issue by mungle** [michalsnik/aos#90]
Hello,
If you need to hide elements or if you are looking for a fadeout add this in aos.css:

```
[data-aos^=hide][data-aos^=hide] {
    opacity: 1;
    transition-property: opacity, transform
}

[data-aos^=hide][data-aos^=hide].aos-animate {
    opacity: 0;
    transform: translate(0)
}
```

and use like a normal animation with: `data-aos="hide"`

Hope @michalsnik could add this in the main repo. 🎉

**Comment by michalsnik** [comment]
Hey @mungle, I think this is not as common scenario that I should put it in repository. If anyone needs it - this can be easily added in application's styles based on the example in README :)

**Comment by shikkaba** [comment]
@michalsnik It would be awesome if you added a simple way for this to be added. For example, if one item that was faded in got to a certain point where it was not required anymore, then it would fade out.
