### ISSUE TITLE
How to disable animate.css for mobile

### ISSUE THREAD

**Issue by DEMZL25** [michalsnik/aos#92]
Hello

 I have difficulties with disabling animate.css for mobile screens. I have animated my h3 title to zoomin. On my front page animations are turn of on mobile but  on all others pages are turn on. I have found this this css code to turn of animations here on github "turn of animate.css on mobile" but  this css code  has no affect. animations are still turn on on mobile screens  i need help.
 
/* Small Devices, Tablets */
@media only screen and (max-width : 768px) {
	.animated {
		/*CSS transitions*/
		-o-transition-property: none !important;
		-moz-transition-property: none !important;
		-ms-transition-property: none !important;
		-webkit-transition-property: none !important;
		transition-property: none !important;
		/*CSS transforms*/
		-o-transform: none !important;
		-moz-transform: none !important;
		-ms-transform: none !important;
		-webkit-transform: none !important;
		transform: none !important;
		/*CSS animations*/
		-webkit-animation: none !important;
		-moz-animation: none !important;
		-o-animation: none !important;
		-ms-animation: none !important;
		animation: none !important;
	}
}
Thanks

**Comment by michalsnik** [comment]
Hey, have you tried this: https://github.com/michalsnik/aos#disabling-aos ?
