### ISSUE TITLE
When I disable AOS on mobile I see nothing.

### ISSUE THREAD

**Issue by MichalZmu** [michalsnik/aos#95]
Hi, 

I disabled AOS on mobile in my JS file and I don't see div's where I turned on AOS. 

[Screen](http://imgur.com/a/4P87V)

How can I fix it?

Code:

[Click](https://github.com/MichalZmu/CV-page)

**Comment by michalsnik** [comment]
Have you tried to init AOS on document ready or just put your script at the very bottom of index.html before `</body>`?

**Comment by michalsnik** [comment]
I'm closing this issue, as it most likely was problem with initializing AOS. Feel free to reopen if you still have this issue.
