### ISSUE TITLE
Script only works in Developer Mode

### ISSUE THREAD

**Issue by eisteeverschluss** [michalsnik/aos#96]
Hi,

if i load the page normally the script does not work. if I go in developer mode it works fine.

any suggestions? I have got no idea

**Comment by michalsnik** [comment]
This may have something to with resizing window while you're opening developer tools. Try to refresh AOS on window load:
```
$(window).on('load', function() {
  AOS.refresh();
});
```

**Comment by eisteeverschluss** [comment]
the following worked. thanks for your tip. I really do not know why this came up. in other examples it worked without any refresh - so I guess it is not an issue of pos itself.
```
                jQuery(document).ready(function () {
                    setTimeout(function () {
                        AOS.refresh();
                    }, 250);
                });
```
