### ISSUE TITLE
The elements with aos data hides with lightbox

### ISSUE THREAD

**Issue by nikmauro** [michalsnik/aos#98]
I use this lightbox http://dimsemenov.com/plugins/magnific-popup/ for image gallery, when open the modal the data with aos disapear and when close the lightboxt he data remain disappeared. 

Demo url http://www2.domainpanel.gr/agorafresh.gr/el/food-product/%CE%B5%CE%BE%CF%89%CF%84%CE%B9%CE%BA%CE%B1-%CF%86%CF%81%CE%BF%CF%85%CF%84%CE%B1-%CE%B5%CE%B9%CF%83%CE%B1%CE%B3%CF%89%CE%B3%CE%B7%CF%82.html

Any suggestion?

**Comment by michalsnik** [comment]
Not sure, but maybe you should `AOS.refresh()` after closing popup. It's not happening right now on the provided demo.
